### ISSUE TITLE
How to use Redisson Quarkus with application.properties

### ISSUE THREAD

**Issue by maranza** [redisson/redisson#4939] opened 2023-03-29 07:21 UTC
In the Maven dependecy for Redisson Quarkus, there is an example as shown below it could either be the example is misleading or I am not doing it correctly, As such i would like to request or ask how should we use this library on Quarkus application:

```
quarkus.redisson.single-server-config.address=redis://localhost:6379
quarkus.redisson.single-server-config.password=null
quarkus.redisson.threads=16
quarkus.redisson.netty-threads=32
```

The configs above are not recognized by the application. Please assist.

**Comment by mrniko** [comment] 2023-03-29 07:55
Can you share sample to reproduce the issue?

**Comment by mrniko** [comment] 2023-03-31 06:08
Did you use quarkus native image?

**Comment by alexcatit** [comment] 2023-05-02 07:11
I think the question is referring to Quarkus log warning "Unrecognized configuration"

![image](https://user-images.githubusercontent.com/18626945/235602424-5ac0c13c-5ea7-477f-8ff3-3966a5977a6a.png)

**Comment by mrniko** [comment] 2023-05-02 07:19
It's expected behavior, since configuration read in dynamic way. Redisson should run correctly.

**Comment by wjw465150** [comment] 2023-07-12 05:52
I also encountered this error here, can not run the program properly.

**Comment by mrniko** [comment] 2023-07-12 07:56
@wjw465150 

Can you share more details? do you see these warnings https://github.com/redisson/redisson/issues/4939#issuecomment-1530993724 ? what is the reason of incorrect program run?

**Comment by mrniko** [comment] 2023-07-12 08:30
@wjw465150 

which version of quarkus do you use?

**Comment by wjw465150** [comment] 2023-07-12 08:32
> @wjw465150
> 
> which version of quarkus do you use?

Quarkus 3.2.0
implementation "org.redisson:redisson-quarkus-30:3.22.1"

**Comment by mrniko** [comment] 2023-07-12 09:08
Unable to reproduce issue with the example attached. Can you check it as well?

[fj-demo-quarkus.zip](https://github.com/redisson/redisson/files/12026045/fj-demo-quarkus.zip)

**Comment by mrniko** [comment] 2023-07-12 09:09
Just run follow scripts one by one.

1.build.cmd
2.run-redis.cmd
3.run.cmd
4.check.cmd -> you should see "Hello from RESTEasy Reactive" output

**Comment by wjw465150** [comment] 2023-07-12 09:25
I find this way don't  work!

```java
import java.time.Instant;

import org.jboss.logging.Logger;
import org.redisson.api.RedissonClient;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Promise;
import jakarta.annotation.PostConstruct;
import jakarta.annotation.PreDestroy;
import jakarta.enterprise.context.Dependent;
import jakarta.inject.Inject;

@Dependent
public class MyVerticle extends AbstractVerticle {
  @Inject
  Logger log;

  @Inject
  RedissonClient redisson;

  String youName;

  @PostConstruct
  void init() {
    youName = "MyVerticle:" + Instant.now().toString();
  }

  @PreDestroy
  void destroy() {
    // ...
  }

  @Override
  public void start(Promise<Void> startPromise) throws Exception {
    log.info(youName);
    log.info("redisson:"+redisson.getConfig().toYAML());
  }
}
```

**Comment by wjw465150** [comment] 2023-07-12 09:30
@Dependent 改成 @ApplicationScoped is OK!

**Comment by mrniko** [comment] 2023-07-12 10:31
@wjw465150 

Does it resolve the issue?

**Comment by wjw465150** [comment] 2023-07-12 11:35
> @wjw465150
> 
> Does it resolve the issue?

Problem solved! However, I am still using my own Produces method. It is too cumbersome to configure these things in the properties file, so I can just use redisson's JSON or YAML configuration file!
```java
@SuppressWarnings("deprecation") 
public class BeansProducer {
  
  @Produces
  @ApplicationScoped
  RedissonClient redisson() throws IOException {
    String activeProfile = ProfileManager.getActiveProfile();
    
    String str = StringUtil.convertInputStreamToString(this.getClass().getResourceAsStream("/config/redisson_conf-"+activeProfile+".json"), "UTF-8");

    JsonObject     jsonObject = new JsonObject(str);
    Config         config     = Config.fromJSON(jsonObject..encode());
    return Redisson.create(config);
  }
}
```

**Comment by mrniko** [comment] 2023-07-12 11:43
You can use `quarkus.redisson.file` setting to specify path to config file. Did you try it?

**Comment by wjw465150** [comment] 2023-07-12 11:54
> You can use `quarkus.redisson.file` setting to specify path to a config file. Did you try it?
Thank you. I still want to control how redisson is generated!

**Comment by mrniko** [comment] 2023-07-12 12:49
I'm closing the issue as it has been resolved.

**Comment by mrniko** [comment] 2023-07-17 05:35
Fixed. Thanks for report

**Closed by mrniko** 2023-07-17 05:35 UTC
Labels: bug, quarkus
