### ISSUE TITLE
Client suddenly spikes in latency and then does not recover until Redisson connections are reset

### ISSUE THREAD

**Issue by nathanielhsu** [redisson/redisson#4224] opened 2022-04-12 01:49 UTC
### Expected behavior
Redisson client should not all of a sudden have persistent latency spikes

### Actual behavior
Every so often, I see latency for GETs all of a sudden spike up from ~4ms to well over 100ms and then stay there until I reset the connections to cache by doing a forced deployment on the application to create new Redis connections. I see this behavior several times every week. See screenshot below for latency spike which recovers only after connections have been reset: 
![Screen Shot 2022-04-11 at 6 02 49 PM](https://user-images.githubusercontent.com/12907522/162857779-11db2444-3aa8-467f-b3e7-3ea95a0e8cbf.png)

When checking the logs, I found a bunch of the following error: `org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (20 ms) occured after 1 retry attempts. Increase nettyThreads and/or timeout settings.`

For our use case, since latency is a priority, we don't want to set the response timeout much higher than this or have too many retry attempts. At the same time though, timeout aside, we shouldn't be seeing such long lasting latency impact here.

I'm currently using Redisson version 3.16.3 with [this fix mentioned here](https://github.com/redisson/redisson/issues/3871#issuecomment-943176694) and this is the Redisson configuration:
```
ClusterModeEnabled: true
ReadMode: Slave
TimeoutMilliSeconds: 100
RetryAttempts: 3
RetryIntervalMilliSeconds: 100
MasterConnectionMinimumIdleSize: 2
MasterConnectionPoolSize: 2
ReplicaConnectionPoolSize = 24
ReplicaConnectionMinimumIdleSize: 24
PingConnectionInterval: 1000
FailedSlaveReconnectionInterval: 3000
FailedSlaveCheckInterval: 5000
```

We are using batched get calls with `org.redisson.api.BatchOptions` with the following configuration:
```
TimeoutMilliSeconds: 20
RetryAttempts: 1
RetryIntervalMilliSeconds: 3
```

Another thing to note is that when this issue happens, it happens only on 1 or 2 Redis nodes, so it seems to be all the channels connected to those tasks going bad all at once and then not recovering.

Two questions here:
1. I just want to understand why this is happening in the first place. Why is it that all of a sudden, we will see a sudden jump in latency that stays high until connections are reset. Is this just a channel going bad? And if that's the case, why isn't Redisson client recovering quickly from the bad channel? From investigation, this doesn't seem to be related to TPS at all.
2. Could this be related to our configuration settings? And if not, is this a bug in Redisson client? I've checked with Elasticache/Redis support and they've confirmed that there's no underlying problem with the Redis cluster/node.

Any help or direction here would be appreciated. Thanks!

**Comment by micr0farad** [comment] 2022-04-14 11:38
same issue for me after azure redis failover

**Comment by mrniko** [comment] 2022-04-14 12:20
> I found a bunch of the following error: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (20 ms) occured after 1 retry attempts. Increase nettyThreads and/or timeout settings.

Are these errors occur until the application redeployment?

**Comment by mrniko** [comment] 2022-04-14 12:20
@micr0farad 

Which Redisson version?

**Comment by micr0farad** [comment] 2022-04-14 12:51
@mrniko which error stacktraces? My services experience increase of latency on any redis query after redis cluster failover. Redis client settings are following: 
```
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 128
  readMode: "MASTER"
  subscriptionMode: "SLAVE"
  scanInterval: 1000
  pingConnectionInterval: 3000
  keepAlive: true
  tcpNoDelay: true
checkLockSyncedSlaves: false
threads: 16
nettyThreads: 128
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"
```

**Comment by micr0farad** [comment] 2022-04-14 13:58
@mrniko no, I don't see any errors after failover. Latency increased to a master node, I haven't tested with a  readMode: "SLAVE".

**Comment by nathanielhsu** [comment] 2022-04-14 17:10
> Are these errors occur until the application redeployment?

@mrniko These errors occur until the  #application redeployment yes.

**Comment by micr0farad** [comment] 2022-04-15 07:13
@mrniko after some investigation I've found that the issue is related to redisson distributed locks which my service using around redis queries. I've set checkLockSyncState: true and this has resulted in latency spike after azure cache failover. The issue reproduce on every failover and can be resolved by service restart. Without locks everything looking good.

**Comment by mrniko** [comment] 2022-04-15 09:39
@micr0farad 

Thanks for update. I'll check that

**Comment by nathanielhsu** [comment] 2022-04-18 16:31
@mrniko For my issue, I do see errors after failover due to timing out which makes sense due to elevated latency. We are not using Redisson distributed locks, so it may be a different issue. Any insight here? Thanks!

**Comment by mrniko** [comment] 2022-04-19 06:59
@nathanielhsu 

It might be caused by redirect responses from Redis node to Master during loading data by Slave from Master node. Did you check that? Moved responses are visible if you use set `TRACE` logging level for `org.redisson` package.

**Comment by nathanielhsu** [comment] 2022-04-20 01:23
@mrniko let me try to enable TRACE logging with lower TPS and see. If this is the case though, what would be the resolution?

**Comment by mannitrkl2006** [comment] 2022-04-21 20:21
@mrniko 
Thanks for providing some direction.
Can you please elaborate on "redirect responses from Redis Node to Master"? Why are readOnly request redirected to "Master" in place. Is there a setting in Redisson where we can mark the requests as such to not cause "redirect"?

We are using `ReadMode.SLAVE` and only want to read from slaves ( replicas)

On the other hand, even if redirect happens, why would it lead Redisson to get into this state where all calls are failing?

**Comment by mrniko** [comment] 2022-05-10 13:41
> Why are readOnly request redirected to "Master" in place. Is there a setting in Redisson where we can mark the requests as such to not cause "redirect"?

It's managed on Redis side, since it reply with MOVED/ASK response. Please check your Redis configuration.

**Comment by mrniko** [comment] 2023-01-21 08:30
@jamesbury3 

https://github.com/redisson/redisson/wiki/2.-Configuration#checklocksyncedslaves

**Closed by mrniko** 2023-01-21 08:30 UTC
Labels: question
