### ISSUE TITLE
What is difference between Rmap and RLocalCachedMap

### ISSUE THREAD

**Issue by thiennguyen1308** [redisson/redisson#1376] opened 2018-04-06 06:26 UTC
I have a DB with 100k hashmap. And I run some 10k, 100k loop test to compare time between getting by RMap and getting by RmapCached
[redissonRMap.txt](https://github.com/redisson/redisson/files/1882888/redissonRMap.txt)
[redissonUseLocalCached.txt](https://github.com/redisson/redisson/files/1882889/redissonUseLocalCached.txt)

- I saw no differences in benchmark time. Am i make a wrong config or something

- When I use RMapLocalCached, why redisson keep getting result from my Redis DB, I think it should get result from some local variable instead of connecting to Redis DB and get result ?

- I use `LocalCachedMapOptions.defaults().cacheSize(0).timeToLive(100000)
            .evictionPolicy(LocalCachedMapOptions.EvictionPolicy.NONE)
            .syncStrategy(LocalCachedMapOptions.SyncStrategy.NONE)
            .reconnectionStrategy(LocalCachedMapOptions.ReconnectionStrategy.NONE)`,
But when i change a value in Redis DB by redis-cli, redisson immediately get a changed value. ?
Thanks.

JDK 1.8_0161
Redisson 3.6.3

**Comment by thiennguyen1308** [comment] 2018-04-06 06:37
* I use redisson 3.6.3.
It take 19.86s when I use RLocalCachedMap and 19.98s with RMap. Even when I test with 100k loop, the difference is always  +/- < 1 second.

**Comment by mrniko** [comment] 2018-04-06 06:58
The problem is that you're getting RLocalCachedMap each time instead of using shared instance.

**Comment by thiennguyen1308** [comment] 2018-04-07 02:52
Oh thanks, I finally get it. It's nice feature bro. I'm moving all from Jedis to your Redisson. Cheers.

**Comment by mrniko** [comment] 2018-04-09 10:05
Great! I'm closing it then.

**Closed by mrniko** 2018-04-09 10:05 UTC
