### ISSUE TITLE
RedissonDelayedQueue stop transfer timeout elements to destination queue

### ISSUE THREAD

**Issue by johnshawn-david** [redisson/redisson#4088] opened 2022-01-24 13:44 UTC
After using for a while, the RedissonDelayedQueue stop work。All added elements are backlogged in the queue，even if many elements have already timeout。
When I restarted the application，all the elements will transfer to the destination queue。

Even if I use the following code to force trigger the publish，it still doesn't work。Only restart can resolve.

```
public void forceTriggerRDelayedQueue() {
    if (redisson instanceof Redisson) {
        CommandAsyncExecutor commandExecutor = ((Redisson) redisson).getCommandExecutor();
        String delayQueueName = clearingChannelDelayedQueue.getName();
        String channelName = RedissonDelayedQueue.prefixName("redisson_delay_queue_channel", delayQueueName);
        Codec codec = clearingChannelDelayedQueue.getCodec();
        long timeout = System.currentTimeMillis();
        commandExecutor.evalWriteAsync(delayQueueName, codec, RedisCommands.EVAL_VOID,
                "redis.call('publish', KEYS[1], ARGV[1]); ",
                Collections.singletonList(channelName), timeout);

    } else {
        log.warn("Redisson Client type is {}", redisson.getClass().getName());
    }
}
```
My Redisson version is 3.15.5 ，And used in SingleServer mode.  Redis version is 6.0.0

**Comment by mrniko** [comment] 2022-01-25 11:18
Do you have an instance of RDelayedQueue all the time? Elements transfer stops to work if RDelayedQueue instance removed.

**Comment by johnshawn-david** [comment] 2022-01-25 11:28
Thank you for your reply. 
This instance is used as a field in the class，this instance should not have been removed.

**Comment by mrniko** [comment] 2022-01-25 12:26
Is it possible to reproduce this case?

**Comment by johnshawn-david** [comment] 2022-01-25 12:51
Sorry，it is hard to reproduce.

**Comment by lzy-125** [comment] 2024-01-14 05:57
> After using for a while, the RedissonDelayedQueue stop work。All added elements are backlogged in the queue，even if many elements have already timeout。 When I restarted the application，all the elements will transfer to the destination queue。
> 
> Even if I use the following code to force trigger the publish，it still doesn't work。Only restart can resolve.
> 
> ```
> public void forceTriggerRDelayedQueue() {
>     if (redisson instanceof Redisson) {
>         CommandAsyncExecutor commandExecutor = ((Redisson) redisson).getCommandExecutor();
>         String delayQueueName = clearingChannelDelayedQueue.getName();
>         String channelName = RedissonDelayedQueue.prefixName("redisson_delay_queue_channel", delayQueueName);
>         Codec codec = clearingChannelDelayedQueue.getCodec();
>         long timeout = System.currentTimeMillis();
>         commandExecutor.evalWriteAsync(delayQueueName, codec, RedisCommands.EVAL_VOID,
>                 "redis.call('publish', KEYS[1], ARGV[1]); ",
>                 Collections.singletonList(channelName), timeout);
> 
>     } else {
>         log.warn("Redisson Client type is {}", redisson.getClass().getName());
>     }
> }
> ```
> 
> My Redisson version is 3.15.5 ，And used in SingleServer mode. Redis version is 6.0.0

hi david. 
I have the same problem during this time. every once in a while, I used 
> pubsub numsub redisson_delay_queue_channel:{xxx} 
1) "redisson_delay_queue_channel:{xxx}"
2) (integer) 0
find that redission client and redis subscriptions are disconnected, it caused  RedissonDelayedQueue stop work. All added elements are backlogged in the queue, When I restarted the application，all the elements will transfer to the destination queue. My redission client version is 3.11.0, have you solved the problem?

**Comment by kangqing** [comment] 2024-06-17 10:13
After setting breakpoints in this code and confirming some parameters, I resumed the execution, and the issue reoccurred. After resuming, messages were only offered to the delayed queue and no longer moved to the target queue.
However, I'm still unsure what caused this issue in the production environment.
```java
public class QueueTransferService {

    private final Map<String, QueueTransferTask> tasks = new ConcurrentHashMap<>();
    
    public void schedule(String name, QueueTransferTask task) {
        QueueTransferTask oldTask = tasks.putIfAbsent(name, task);
        if (oldTask == null) {
            task.start();
        } else {
            oldTask.getLock().execute(() -> {
                oldTask.incUsage();
            });
        }
    }
}
```

**Comment by kangqing** [comment] 2024-06-17 13:35
## When executing this code, if an exception sqlException is thrown
```java
// RedissonDelayedQueue.java
QueueTransferTask task = new QueueTransferTask(commandExecutor.getConnectionManager()) {
            
            @Override
            protected RFuture<Long> pushTaskAsync() {
                return commandExecutor.evalWriteAsync(getName(), LongCodec.INSTANCE, RedisCommands.EVAL_LONG,
                        "local expiredValues = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); "
                      + "if #expiredValues > 0 then "
                          + "for i, v in ipairs(expiredValues) do "
                              + "local randomId, value = struct.unpack('dLc0', v);"
                              + "redis.call('rpush', KEYS[1], value);"
                              + "redis.call('lrem', KEYS[3], 1, v);"
                          + "end; "
                          + "redis.call('zrem', KEYS[2], unpack(expiredValues));"
                      + "end; "
                        // get startTime from scheduler queue head task
                      + "local v = redis.call('zrange', KEYS[2], 0, 0, 'WITHSCORES'); "
                      + "if v[1] ~= nil then "
                         + "return v[2]; "
                      + "end "
                      + "return nil;",
                      Arrays.<Object>asList(getName(), timeoutSetName, queueName), 
                      System.currentTimeMillis(), 100);
            }
            
            @Override
            protected RTopic getTopic() {
                return new RedissonTopic(LongCodec.INSTANCE, commandExecutor, channelName);
            }
        };

```
## This exception will result in a direct return and will not be scheduled again unless restarted

```java
private void pushTask() {
        RFuture<Long> startTimeFuture = pushTaskAsync();
        startTimeFuture.onComplete((res, e) -> {
            if (e != null) {
                if (e instanceof RedissonShutdownException) {
                    return;
                }
                log.error(e.getMessage(), e);
                scheduleTask(System.currentTimeMillis() + 5 * 1000L);
                return;
            }
            
            if (res != null) {
                scheduleTask(res);
            }
        });
    }
```
## Because even if the delay queue is initialized again, the following code will only perform usage++


```java
public class QueueTransferService {

    private final ConcurrentMap<String, QueueTransferTask> tasks = new ConcurrentHashMap<>();
    
    public synchronized void schedule(String name, QueueTransferTask task) {
        QueueTransferTask oldTask = tasks.putIfAbsent(name, task);
        if (oldTask == null) {
            task.start();
        } else {
            oldTask.incUsage();
        }
    }
    
    public synchronized void remove(String name) {
        QueueTransferTask task = tasks.get(name);
        if (task != null) {
            if (task.decUsage() == 0) {
                tasks.remove(name, task);
                task.stop();
            }
        }
    }
```

**Comment by ying3885** [comment] 2024-06-25 03:39
I have also encountered this issue and discovered the RedissonShutdownException issue, but how do I solve this problem

**Comment by mrniko** [comment] 2024-07-26 09:24
Fixed in https://github.com/redisson/redisson/issues/5947

**Closed by mrniko** 2024-07-26 09:24 UTC
Labels: question
