### ISSUE TITLE
RDelayedQueue 运行一段时间后队列内元素丢失

### ISSUE THREAD

**Issue by floor23** [redisson/redisson#1960] opened 2019-03-06 08:37 UTC
类似问题#1754
### Expected behavior
队列元素依然存在，并且能够在指定延迟后取到
### Actual behavior
队列元素丢失
### Steps to reproduce or test case
应该是必现的一个问题。运行大概两三天会出现延时队列元素丢失的问题。
队列创建代码：
 ```java
private static RBlockingQueue<Long> taskQueue = RedissonHelper.redisson.getBlockingQueue("WX_DELAYED_TASK_QUEUE");
private static RDelayedQueue<Long> delayedTaskQueue = RedissonHelper.redisson.getDelayedQueue(taskQueue);
 ```
入队列代码：
 ```java
delayedTaskQueue.offer(one, delayTime, TimeUnit.MILLISECONDS);
 ```
获取元素的代码：
 ```java
while (true) {
try {
    printQueue("before execute");
    execute(taskQueue.take());
    printQueue("after execute");
    } catch (Exception e) {
    log.error("由任务队列获取任务失败", e);
    }
}
 ```
printQueue代码：
 ```java
public static void printQueue(String hint) {
        log.info("taskTrace start: " + hint);
        delayedTaskQueue.readAll().forEach(one -> log.info(String.format("taskTrace: delayedTaskQueue 内容: %s", one)));
        log.info("taskTrace end: " + hint);
    }
```
在服务器运行一段时间后发现任务执行失败，查看日志发现delayedTaskQueue中的元素都不见了，日志如下：
```log
15:38:43,424  INFO TaskService:969 - taskTrace start: Thread pool check
15:38:43,425  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097757933673955328
15:38:43,425  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097758524814962690
15:38:43,425  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097458667441139716
15:38:43,425  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097692298050850818
15:38:43,425  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1098112565378068482
15:38:43,425  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1098113151238463493
15:38:43,426  INFO TaskService:971 - taskTrace remainTimeToLive: -2
15:38:43,426  INFO TaskService:972 - taskTrace end: Thread pool check
15:43:42,450  INFO TaskService:969 - taskTrace start: Thread pool check
15:43:42,451  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097757933673955328
15:43:42,451  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097758524814962690
15:43:42,451  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097458667441139716
15:43:42,451  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1097692298050850818
15:43:42,451  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1098112565378068482
15:43:42,451  INFO TaskService:970 - taskTrace: delayedTaskQueue 内容: 1098113151238463493
15:43:42,452  INFO TaskService:971 - taskTrace remainTimeToLive: -2
15:43:42,452  INFO TaskService:972 - taskTrace end: Thread pool check
15:48:41,483  INFO TaskService:969 - taskTrace start: Thread pool check
15:48:41,483  INFO TaskService:971 - taskTrace remainTimeToLive: -1
15:48:41,483  INFO TaskService:972 - taskTrace end: Thread pool check
15:53:40,507  INFO TaskService:969 - taskTrace start: Thread pool check
15:53:40,507  INFO TaskService:971 - taskTrace remainTimeToLive: -1
15:53:40,507  INFO TaskService:972 - taskTrace end: Thread pool check
15:58:39,533  INFO TaskService:969 - taskTrace start: Thread pool check
15:58:39,534  INFO TaskService:971 - taskTrace remainTimeToLive: -1
15:58:39,534  INFO TaskService:972 - taskTrace end: Thread pool check
```

这个问题在我这边是必现的。如果需要配合，我这边可以随时复现。谢谢。
### Redis version
4.0
### Redisson version
3.7.0
### Redisson configuration
```config
singleServerConfig:
  #连接空闲超时，单位：毫秒
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  #连接超时，单位：毫秒
  connectTimeout: 10000
  #命令等待超时，单位：毫秒
  timeout: 3000
  #命令失败重试次数
  retryAttempts: 3
  #命令重试发送时间间隔，单位：毫秒
  retryInterval: 1500
  #重新连接时间间隔，单位：毫秒
  reconnectionTimeout: 3000
  #执行失败最大次数
  failedAttempts: 3
  #单个连接最大订阅数量
  subscriptionsPerConnection: 5
  #客户端名称
  clientName: null
  #地址
  address: "redis://test"
  #数据库编号
  database: 0
  #密码
  password: 123456
  #发布和订阅连接的最小空闲连接数
  subscriptionConnectionMinimumIdleSize: 1
  #发布和订阅连接池大小
  subscriptionConnectionPoolSize: 50
  #最小空闲连接数
  connectionMinimumIdleSize: 32
  #连接池大小
  connectionPoolSize: 64
  #是否启用DNS监测
  #dnsMonitoring: false
  #DNS监测时间间隔，单位：毫秒
  #dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode : "NIO"
```

**Comment by floor23** [comment] 2019-03-14 14:40
No reply？
Fine，I close this issue now.

**Comment by mrniko** [comment] 2019-03-14 15:34
Could you provide some test case to run?

**Comment by floor23** [comment] 2019-03-18 06:11
> Could you provide some test case to run?

Sorry bro
I've delete all the code and implement on my own.
Thanks for your reply

**Comment by jackcooper2015** [comment] 2019-09-26 09:29
@mrniko I also encountered the same problem.  Is it  has fixed in the high version?  
  
Thank you very much

**Comment by mrniko** [comment] 2019-09-26 09:56
@jackcooper2015 

Could you provide some test case to reproduce this with the latest version?

**Comment by jackcooper2015** [comment] 2019-09-26 10:40
@mrniko  Do you mean that it has been fixed in 3.10.5?  I am having this problem at 3.7.5.  
I just saw the previous issue and found it closed in 3.10.5.  I am going to upgrade to 3.11.2.

Thank you!

**Comment by lidengke** [comment] 2019-09-29 18:40
> Could you provide some test case to run?

3.11.4 still has this bug

**Comment by mrniko** [comment] 2019-09-30 10:45
@lidengke 

Thanks for the shared code. Could you also share Message class?

**Comment by mrniko** [comment] 2019-10-02 08:53
@lidengke

Please find my output attached. Could you explain what is wrong?

[output.txt](https://github.com/redisson/redisson/files/3680242/output.txt)

**Comment by lidengke** [comment] 2019-10-05 16:10
@mrniko 

 I make a little change to my unitest：
1. `Add a message counter index to show whether the delay queue has lose some elements. `
2. `Two round loops to produce and consume elements, each round produce and consume 1000 messages. all messages consumed, program exits gracefully.`
3. `Some tips may be helpful `
> expectDelayMs means the delay time settings when putting into the queue
> actualDelayMs means the acutul delay interval time between input time to the delay queue and current time when consuming 





```java
@Test
    public void delayQueueTest() throws InterruptedException {
        int maxRoundCount = 2;
        int roundMessageCount = 1000;
        final CountDownLatch downLatch = new CountDownLatch(maxRoundCount);
        Config config = new Config();
        config.setNettyThreads(50);
        config.useSingleServer()
                .setTimeout(3000)
                .setSubscriptionConnectionMinimumIdleSize(3)
                .setConnectionMinimumIdleSize(3)
                .setSubscriptionConnectionPoolSize(30)
                .setKeepAlive(true)
                .setDatabase(1)
                .setPingConnectionInterval(3000)
                .setTcpNoDelay(true)
                .setRetryInterval(3000)
                .setRetryAttempts(4)
                .setIdleConnectionTimeout(5 * 60000)
                .setConnectionPoolSize(30)
                .setAddress("redis://127.0.0.1:6379");
        RedissonClient redissonClient = Redisson.create(config);
        Map<Integer, RedissonDelayedQueue<Message>> queueMap = new HashMap<>();
        for (int roundId = 0 ; roundId < maxRoundCount; roundId ++) {
            RBlockingQueue<Message> destinationQueue = redissonClient.getBlockingQueue("delay_shard2_queue_"+roundId);
            RedissonDelayedQueue<Message> delayedQueue = (RedissonDelayedQueue<Message>)redissonClient.getDelayedQueue(destinationQueue);
            queueMap.put(roundId,delayedQueue);
        }
        for (int roundId = 0 ; roundId < maxRoundCount; roundId ++) {
            final  int localRoundId = roundId;
            RedissonDelayedQueue<Message> delayedQueue = queueMap.get(localRoundId);
            try{
                logger.info("## round {} consumer start.",localRoundId);
                new Thread(() -> {
                    long maxDiff = 0L;
                    final AtomicInteger messageCount = new AtomicInteger(0);
                    final AtomicInteger currentMessageCount = new AtomicInteger(0);
                    //long sumDiff = 0L;
                    while (messageCount.get() < roundMessageCount) {
                        try {
                            Message ms = delayedQueue.poll();
                            if (ms == null) {
                                sleep(10);
                                continue;
                            }
                            Long actualDelayMs = (System.currentTimeMillis() - Long.valueOf(ms.getId()));
                            Long expectDelayMs = Integer.valueOf(ms.getData()) * 1000L;
                            Long diffDelayMs = Math.abs(actualDelayMs  - expectDelayMs);
                            maxDiff = maxDiff < diffDelayMs ? diffDelayMs : maxDiff;
                            //sumDiff += diffDelayMs;
                            logger.info("# roundId: {}-> message index: {}, expectDelayMs: {}, actualDelayMs: {}, diffDelayMs: {}",localRoundId,currentMessageCount.incrementAndGet(),expectDelayMs,actualDelayMs,diffDelayMs);
                            messageCount.incrementAndGet();
                        }catch (Throwable t) {
                            t.printStackTrace();
                        }
                    }
                    logger.info("## round: {}, message count: {}, maxDiff: {}",localRoundId,messageCount.get(),maxDiff);
                    downLatch.countDown();
                    logger.info("## round {} consumer end.",localRoundId);
                }).start();
            }catch (Throwable t) {
                t.printStackTrace();
            }
            new Thread(() -> {
                logger.info("## round {} producer start.",localRoundId);
                for (int i = 0 ; i < roundMessageCount; i++) {
                    long currentTime = System.currentTimeMillis();
                    Random r = new Random();
                    int n2 = r.nextInt(11);
                    Message message = new Message(currentTime + "", n2+"");
                    RFuture<Void> future = delayedQueue.offerAsync(message, n2, TimeUnit.SECONDS);
                    future.onComplete((x,throwable) -> {
                        if (throwable != null) {
                            throwable.printStackTrace();
                        }
                    });
                    try {
                        sleep(10);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
                logger.info("## round {} producer end.",localRoundId);
            }).start();
        }
        downLatch.await();
        logger.info("## performance test wait to end");
        redissonClient.shutdown(3000,6000,TimeUnit.MILLISECONDS);
```
benchMark result as follows:
[console.log](https://github.com/redisson/redisson/files/3693452/console.log)
As the console.log shows:

1. 
`## round 1 producer end.` 
`## round 0 producer end.`
-> Both producer-0 and produer-1 have put 1000 messages into delay queue.
2. 
`roundId: 1-> message index: 949, expectDelayMs: 3000, actualDelayMs: 11, diffDelayMs: 2989`
`# roundId: 0-> message index: 938, expectDelayMs: 7000, actualDelayMs: 0, diffDelayMs: 7000`
-> Program can not exit, because less than 2000 messages could be consumed. 

3. 
Delay queue do not delay enough times for consumer to poll elements.

**Comment by lidengke** [comment] 2019-10-05 23:49
> @lidengke
> 
> Thanks for the shared code. Could you also share Message class?

```java
public class Message implements Serializable {
    private static final long serialVersionUID = -3821000677893184583L;

    private String id;

    private String data;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public Message() {
    }

    public Message(String id, String data) {
        this.id = id;
        this.data = data;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Message message = (Message) o;
        return Objects.equals(getId(), message.getId());
    }

    @Override
    public int hashCode() {

        return Objects.hash(getId());
    }
}
`

**Comment by lidengke** [comment] 2019-10-05 23:52
> @lidengke
> 
> Thanks for the shared code. Could you also share Message class?

@mrniko  Message class is as follow:

```java
public class Message implements Serializable {
    private static final long serialVersionUID = -3821000677893184583L;

    private String id;

    private String data;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public Message() {
    }

    public Message(String id, String data) {
        this.id = id;
        this.data = data;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Message message = (Message) o;
        return Objects.equals(getId(), message.getId());
    }

    @Override
    public int hashCode() {

        return Objects.hash(getId());
    }
}

```

**Comment by lidengke** [comment] 2019-10-06 00:01
> @lidengke
> 
> Please find my output attached. Could you explain what is wrong?
> 
> [output.txt](https://github.com/redisson/redisson/files/3680242/output.txt)

From ur output log, only 9959 lines output, is it means 41 messages losed?

**Comment by lidengke** [comment] 2019-10-06 03:37
@mrniko 
delay queue is not stable enough. sometime delay enough but sometime neve delay.  unit test as follow
```java
@BeforeClass
    public static void init() {
        Config config = new Config();
        config.setNettyThreads(50);
        config.useSingleServer()
                .setTimeout(3000)
                .setSubscriptionConnectionMinimumIdleSize(3)
                .setConnectionMinimumIdleSize(3)
                .setSubscriptionConnectionPoolSize(30)
                .setKeepAlive(true)
                .setDatabase(1)
                .setPingConnectionInterval(3000)
                .setTcpNoDelay(true)
                .setRetryInterval(3000)
                .setRetryAttempts(4)
                .setIdleConnectionTimeout(5 * 60000)
                .setConnectionPoolSize(30)
                .setAddress("redis://127.0.0.1:6379");
        redissonClient = Redisson.create(config);
    }
 @Test
    public void simpleDelayQueueTest() throws InterruptedException {
        RBlockingQueue<String> blockingQueue = redissonClient.getBlockingQueue("dest_queue1");
        RDelayedQueue<String> delayedQueue = redissonClient.getDelayedQueue(blockingQueue);
        delayedQueue.offer("demo", 10, TimeUnit.SECONDS);
        Assert.assertFalse(blockingQueue.contains("demo"));
        TimeUnit.SECONDS.sleep(15);
        Assert.assertTrue(blockingQueue.contains("demo"));
    }
```

It seems that redisson delay queue do not always effective and available.

**Comment by lidengke** [comment] 2019-10-08 10:16
> > Could you provide some test case to run?
> 
> 3.11.4 still has this bug
> 
> ```java
> @Test
>     public void delayQueueTest() throws InterruptedException {
>         int maxRoundCount = 10;
>         int roundMessageCount = 1000;
>         final CountDownLatch downLatch = new CountDownLatch(maxRoundCount);
>         Config config = new Config();
>         config.setNettyThreads(200);
>         config.useSingleServer()
>                 .setTimeout(3000)
>                 .setKeepAlive(true)
>                 .setDatabase(1)
>                 .setPingConnectionInterval(3000)
>                 .setTcpNoDelay(true)
>                 .setRetryInterval(3000)
>                 .setRetryAttempts(4)
>                 .setIdleConnectionTimeout(5 * 60000)
>                 .setConnectionPoolSize(30)
>                 .setAddress("redis://127.0.0.1:6379");
>         RedissonClient redissonClient = Redisson.create(config);
>         Map<Integer, RedissonDelayedQueue<Message>> queueMap = new HashMap<>();
>         for (int roundId = 0 ; roundId < maxRoundCount; roundId ++) {
>             RBlockingQueue<Message> destinationQueue = redissonClient.getBlockingQueue("delay_shard_queue_"+roundId);
>             RedissonDelayedQueue<Message> delayedQueue = (RedissonDelayedQueue<Message>)redissonClient.getDelayedQueue(destinationQueue);
>             queueMap.put(roundId,delayedQueue);
>         }
>         for (int roundId = 0 ; roundId < maxRoundCount; roundId ++) {
>             final  int localRoundId = roundId;
>             RedissonDelayedQueue<Message> delayedQueue = queueMap.get(localRoundId);
>             try{
>                 new Thread(() -> {
>                     long maxDiff = 0L;
>                     final AtomicInteger messageCount = new AtomicInteger(0);
>                     //long sumDiff = 0L;
>                     while (messageCount.get() < roundMessageCount) {
>                         try {
>                             Message ms = delayedQueue.poll();
>                             if (ms == null) {
>                                 continue;
>                             }
>                             Long actualDelayMs = (System.currentTimeMillis() - Long.valueOf(ms.getId()));
>                             Long expectDelayMs = Integer.valueOf(ms.getData()) * 1000L;
>                             Long diffDelayMs = Math.abs(actualDelayMs  - expectDelayMs);
>                             maxDiff = maxDiff < diffDelayMs ? diffDelayMs : maxDiff;
>                             //sumDiff += diffDelayMs;
>                             logger.info("expectDelayMs: {}, actualDelayMs: {}, diffDelayMs: {}",expectDelayMs,actualDelayMs,diffDelayMs);
>                             messageCount.incrementAndGet();
>                         }catch (Throwable t) {
>                             t.printStackTrace();
>                         }
>                     }
>                     logger.info("## round: {}, message count: {}, maxDiff: {}",localRoundId,messageCount.get(),maxDiff);
>                     downLatch.countDown();
>                 }).start();
>             }catch (Throwable t) {
>                 t.printStackTrace();
>             }
>             new Thread(() -> {
>                 for (int i = 0 ; i < roundMessageCount; i++) {
>                     long currentTime = System.currentTimeMillis();
>                     Random r = new Random();
>                     int n2 = r.nextInt(11);
>                     Message message = new Message(currentTime + "", n2+"");
>                     RFuture<Void> future = delayedQueue.offerAsync(message, n2, TimeUnit.SECONDS);
>                     future.onComplete((x,throwable) -> {
>                         if (throwable != null) {
>                             throwable.printStackTrace();
>                         }
>                     });
>                     try {
>                         sleep(10);
>                     } catch (InterruptedException e) {
>                         e.printStackTrace();
>                     }
>                 }
>             }).start();
>         }
>         downLatch.await();
>         redissonClient.shutdown(3000,6000,TimeUnit.MILLISECONDS);
>     }
> ```
I have resolved this trouble.
Consume message from redisson delay queue shoud use api `RBlockingQueue.poll`, not `RDelayQueue.poll`,  delay queue's api is so confused

**Comment by lidengke** [comment] 2019-10-08 10:17
> > @lidengke
> > Please find my output attached. Could you explain what is wrong?
> > [output.txt](https://github.com/redisson/redisson/files/3680242/output.txt)
> 
> @mrniko
> From ur output log, only 9959 lines output, is it means 41 messages losed?

I have resolved this trouble.
Consume message from redisson delay queue shoud use api RBlockingQueue.poll, not RDelayQueue.poll, delay queue's api is so confused.

**Comment by mrniko** [comment] 2019-10-08 12:02
@lidengke 

Thanks for your comment I'll improve code sample.

**Closed by mrniko** 2019-10-08 12:02 UTC
