### ISSUE TITLE
Connection Leak Issue

### ISSUE THREAD

**Issue by ajax-yurchenko-v** [redisson/redisson#5752] opened 2024-04-03 11:16 UTC
I have recently updated the Redisson library in my production service from version 3.26.1 to 3.27.2. After the update, I have noticed an unusual increase in the number of connections to Redis that are not being closed. The increase is random but consistent, with every instance leading to an additional 25 connections. After 2 days running instance, we notice +3800 connections to redis on 1 host. With 3.26.1 all works as expected.

Upon further investigation, I found that this behavior started to reproduce after updating to Redisson version 3.27.0 and above. I have logs that reproduce this behavior on both 3.27.0 and 3.27.2 versions. It reproduced even when the service is up without any load and without any calls to redis.

To confirm the issue, I used the console command netstat -l -n -t | grep -E '6379' | wc -l. After some of the logs(in attachments), the count of connections increased by 25.

**Expected behavior**
The number of connections to Redis should remain consistent and connections should be closed appropriately.
**Actual behavior**
* execute console command `netstat -l -n -t | grep -E '6379' | wc -l `
  result =    53
* redisson reconnected to redis cluster(logs in attachments)
* The number of connections to Redis increases randomly by 25 and these connections are not being closed.
* execute console command `netstat -l -n -t | grep -E '6379' | wc -l `
  result =    78
**Steps to reproduce or test case**
Update Redisson library to version 3.27.0 or 3.27.2.
Monitor the number of connections to Redis.
Observe an increase in the number of connections that are not being closed.
**Redis version**
redis cluster without sharding with enabled tls
version 6.2.6
**Redisson version**
3.27.0/3.27.2
**Redisson configuration**
<img width="903" alt="image" src="https://github.com/redisson/redisson/assets/110694013/f1e57f2e-cb1b-41da-8f9e-152069c87f1f">

**Logs**
[connection_leak_issue_3.27.2.txt](https://github.com/redisson/redisson/files/14851262/connection_leak_issue_3.27.2.txt)

[connection_leak_issue_3.27.0.txt](https://github.com/redisson/redisson/files/14851266/connection_leak_issue_3.27.0.txt)

**Comment by mrniko** [comment] 2024-04-03 12:41
Can you try the master branch version?

**Comment by mrniko** [comment] 2024-04-03 12:46
Should be fixed with this commit https://github.com/redisson/redisson/commit/51b9444f512a21eb1538cf86a6e9c59f62da70a9

**Comment by ajax-yurchenko-v** [comment] 2024-04-03 13:37
[connection_leak_issue_3.27.3-SNAPSHOT.txt](https://github.com/redisson/redisson/files/14852967/connection_leak_issue_3.27.3-SNAPSHOT.txt)

reproduce on master branch

**Comment by mrniko** [comment] 2024-04-03 13:43
`2024-04-03 16:33:21,903 INFO  [,] [redisson-netty-3-4] o.r.connection.ConnectionsHolder.lambda$initConnections$1: 24 connections initialized for {replica1-ip}/{replica1-ip}:6379` 

these are idle connections for replica. 24 is default value for `slaveConnectionMinimumIdleSize`

**Comment by ajax-yurchenko-v** [comment] 2024-04-03 13:48
After log `2024-04-03 16:33:04,535 INFO  [,] [redisson-netty-3-8] o.r.cluster.ClusterConnectionManager.addRemoveSlaves: slave rediss://{replica1-ip}:6379 removed for slot ranges: [[0-16383]]
` redisson create new 24 connections, but old connections still alive. As result, all connections count always increased

**Comment by ajax-yurchenko-v** [comment] 2024-04-04 11:05
@mrniko can you help to understand why old connections do not close after reconnecting to the replica (logs with reconnecting in the comments above).

With using redisson 3.26.2 reconnects also existed in logs, but connections count remains unchanged.

We also noticed that the number of connections to replicas grows much faster than for the master, maybe it will help with investigate
![image](https://github.com/redisson/redisson/assets/110694013/41fc211c-2e7f-4651-90e2-bfb61f4c2207)

**Comment by mrniko** [comment] 2024-04-09 09:54
@ajax-yurchenko-v 

As I replied earlier this should be fixed with https://github.com/redisson/redisson/commit/51b9444f512a21eb1538cf86a6e9c59f62da70a9 commit

**Comment by mrniko** [comment] 2024-04-11 13:22
Can you try 3.28.0 version?

**Comment by ajax-yurchenko-v** [comment] 2024-04-11 16:30
Looks like same behavior with 3.28.0 version
![image](https://github.com/redisson/redisson/assets/110694013/07ea9515-cf5e-4dea-a472-07c6dd3698b4)

**Comment by mrniko** [comment] 2024-04-12 05:20
Can you set `trace` logging level for `org.redisson` package and share the output?

**Comment by ajax-yurchenko-v** [comment] 2024-04-12 07:31
Here are the application startup logs with the `TRACE` logging level with 3.28.0 redisson version
[redisson_3.28.0_start.txt](https://github.com/redisson/redisson/files/14955314/redisson_3.28.0_start.txt)

Also, here is the moment of reconnecting to the redis cluster and creating 25 new connections (old connections are still open) with the `TRACE` logging level with 3.28.0 redisson version
[3.28.0_reconnect.txt](https://github.com/redisson/redisson/files/14955385/3.28.0_reconnect.txt)

**Comment by mrniko** [comment] 2024-04-12 07:56
Thanks for the provided logs.

`2024-04-12 10:03:55,789 INFO  [,] [redisson-netty-3-13] o.r.cluster.ClusterConnectionManager.addRemoveSlaves: slave rediss://{replica1-ip}:6379 removed for slot ranges: [[0-16383]]`

Was the slave removed?

**Comment by mrniko** [comment] 2024-04-12 07:57
did you define subscriptionMode setting?

**Comment by mrniko** [comment] 2024-04-12 08:00
`2024-04-12 10:04:08,837 INFO  [,] [redisson-netty-3-9] o.r.cluster.ClusterConnectionManager.lambda$addRemoveSlaves$28: slave: rediss://{replica1-ip}:6379 added for slot ranges: [[0-16383]]`

Slave added again. So 25 connections were initialized.

**Comment by mrniko** [comment] 2024-04-12 08:03
I don't see ip address. Are they the same for replica host?

**Comment by ajax-yurchenko-v** [comment] 2024-04-12 08:05
> I don't see ip address. Are they the same for replica host?

Yeah, replica-1 IP is the same before removing and after re-adding

**Comment by mrniko** [comment] 2024-04-12 08:19
Can you try attached version?

I added additional log entry to find slave addresses change

[redisson-3.28.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/14956086/redisson-3.28.1-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment] 2024-04-12 08:24
>  here is the moment of reconnecting to the redis cluster and creating 25 new connections (old connections are still open) with the TRACE logging level with 3.28.0 redisson version

I don't see that old 25 connections were created. I see that new 25 connections were created for added slave. Connections amount look normal. Can you share more logs?

**Comment by mrniko** [comment] 2024-04-17 06:57
Any update?

**Comment by ajax-yurchenko-v** [comment] 2024-04-17 10:50
Sorry for the slow reply, here reproduce on your custom version from application startup to reconnecting
`2024-04-17 13:35:34,983 INFO  [,] [redisson-netty-3-7] o.r.cluster.ClusterConnectionManager.addRemoveSlaves: slave rediss://{replica2-ip}:6379 removed for slot ranges: [[0-16383]]
`
and further new 25 connection creation.
[3.28.1-snapshot_reconnect.txt](https://github.com/redisson/redisson/files/15009785/3.28.1-snapshot_reconnect.txt)

**Comment by ajax-yurchenko-v** [comment] 2024-04-17 11:29
> I don't see that old 25 connections were created. I see that new 25 connections were created for added slave. Connections amount look normal. Can you share more logs?

Here logs with 2 times initialization to {replica2-ip} and no logs about closing connections that were initialized before. Logs with DEBUG logging level, but I hope it will be enough for investigate

`2024-04-17 14:04:55,474 INFO  [,] [redisson-netty-3-25] o.r.connection.ConnectionsHolder.lambda$initConnections$1: 24 connections initialized for {replica2-ip}/{replica2-ip}:6379`

`2024-04-17 14:15:38,032 INFO  [,] [redisson-netty-3-19] o.r.connection.ConnectionsHolder.lambda$initConnections$1: 24 connections initialized for {replica2-ip}/{replica2-ip}:6379`
[3.28.1-snapshot_twice_reconnecting_to_same_node.txt](https://github.com/redisson/redisson/files/15010163/3.28.1-snapshot_twice_reconnecting_to_same_node.txt)

**Comment by mrniko** [comment] 2024-04-18 07:56
Even more logs added regarding cluster state parsing and closing connections. Please try it.

[redisson-3.28.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/15021645/redisson-3.28.1-SNAPSHOT.jar.zip)

**Comment by ajax-yurchenko-v** [comment] 2024-04-18 11:30
[3.28.1-reconnecting.txt](https://github.com/redisson/redisson/files/15024065/3.28.1-reconnecting.txt)
Logs with removing master and connecting to replica2
`2024-04-18 14:05:10,185 INFO  [,] [redisson-netty-3-25] o.r.cluster.ClusterConnectionManager.addRemoveSlaves: slave rediss://{master-ip}:6379 removed for master rediss://{replica2-ip}:6379 and slot ranges: [[0-16383]]
`

Is it will useful logs? Or do you need logs with reconnecting to the same replica/master 2+ times?

**Comment by mrniko** [comment] 2024-04-18 11:48
The issue is with the cluster ip resolution below. I don't see address. So please check it replica1-ip and replica2-ip has the same address overwise slaveAddresses wouldn't have replica1-ip in list. slaveAddresses  is HashSet object.

```
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-24] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: rediss://{cluster-name}-0001-001.{redis-cluster-url}.cache.amazonaws.com:6379 resolved to rediss://{master-ip}:6379
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-25] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: rediss://{cluster-name}-0001-003.{redis-cluster-url}.cache.amazonaws.com:6379 resolved to rediss://{replica1-ip}:6379
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-26] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: rediss://{cluster-name}-0001-002.{redis-cluster-url}.cache.amazonaws.com:6379 resolved to rediss://{replica2-ip}:6379
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-26] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: parsing. slave rediss://{replica2-ip}:6379 added to 157f3da23b598e7a90b74c122414c27714295551 
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-25] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: parsing. slave rediss://{replica1-ip}:6379 added to 157f3da23b598e7a90b74c122414c27714295551 
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-26] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: parsing. slave ClusterNodeInfo [nodeId=df89573fa42e67eb2e44e3b65b5c885fb4a4a419, address=rediss://{cluster-name}-0001-002.{redis-cluster-url}.cache.amazonaws.com:6379, flags=[SLAVE], slaveOf=157f3da23b598e7a90b74c122414c27714295551, slotRanges=[]] parsed
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-24] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: parsing. master ClusterNodeInfo [nodeId=157f3da23b598e7a90b74c122414c27714295551, address=rediss://{cluster-name}-0001-001.{redis-cluster-url}.cache.amazonaws.com:6379, flags=[MASTER, MYSELF], slaveOf=null, slotRanges=[[0-16383]]] parsed
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-25] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: parsing. slave ClusterNodeInfo [nodeId=9010d1a2a28c51ac833c0a290ee9aa28585cd7b4, address=rediss://{cluster-name}-0001-003.{redis-cluster-url}.cache.amazonaws.com:6379, flags=[SLAVE], slaveOf=157f3da23b598e7a90b74c122414c27714295551, slotRanges=[]] parsed
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-25] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$46: parsed partitions before: [ClusterPartition [nodeId=157f3da23b598e7a90b74c122414c27714295551, masterFail=false, masterAddress=rediss://{master-ip}:6379, slaveAddresses=[rediss://{replica1-ip}:6379], failedSlaves=[], slotRanges=[[0-16383]]]]
```

**Comment by ajax-yurchenko-v** [comment] 2024-04-18 12:04
`2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-24] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: rediss://{cluster-name}-0001-001.{redis-cluster-url}.cache.amazonaws.com:6379 resolved to rediss://10.***.***.11:6379
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-25] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: rediss://{cluster-name}-0001-003.{redis-cluster-url}.cache.amazonaws.com:6379 resolved to rediss://10.***.***.153:6379
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-26] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: rediss://{cluster-name}-0001-002.{redis-cluster-url}.cache.amazonaws.com:6379 resolved to rediss://10.***.***.146:6379
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-26] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: parsing. slave rediss://10.***.***.146:6379 added to 157f3da23b598e7a90b74c122414c27714295551
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-25] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: parsing. slave rediss://10.***.***.153:6379 added to 157f3da23b598e7a90b74c122414c27714295551
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-26] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: parsing. slave ClusterNodeInfo [nodeId=df89573fa42e67eb2e44e3b65b5c885fb4a4a419, address=rediss://{cluster-name}-0001-002.{redis-cluster-url}.cache.amazonaws.com:6379, flags=[SLAVE], slaveOf=157f3da23b598e7a90b74c122414c27714295551, slotRanges=[]] parsed
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-24] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: parsing. master ClusterNodeInfo [nodeId=157f3da23b598e7a90b74c122414c27714295551, address=rediss://{cluster-name}-0001-001.{redis-cluster-url}.cache.amazonaws.com:6379, flags=[MASTER, MYSELF], slaveOf=null, slotRanges=[[0-16383]]] parsed
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-25] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$43: parsing. slave ClusterNodeInfo [nodeId=9010d1a2a28c51ac833c0a290ee9aa28585cd7b4, address=rediss://{cluster-name}-0001-003.{redis-cluster-url}.cache.amazonaws.com:6379, flags=[SLAVE], slaveOf=157f3da23b598e7a90b74c122414c27714295551, slotRanges=[]] parsed
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-25] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$46: parsed partitions before: [ClusterPartition [nodeId=157f3da23b598e7a90b74c122414c27714295551, masterFail=false, masterAddress=rediss://10.***.***.11:6379, slaveAddresses=[rediss://10.***.***.153:6379], failedSlaves=[], slotRanges=[[0-16383]]]]
2024-04-18 14:05:10,183 DEBUG [,] [redisson-netty-3-25] o.r.cluster.ClusterConnectionManager.lambda$parsePartitions$46: parsed partitions after: [ClusterPartition [nodeId=157f3da23b598e7a90b74c122414c27714295551, masterFail=false, masterAddress=rediss://10.***.***.11:6379, slaveAddresses=[rediss://10.***.***.153:6379], failedSlaves=[], slotRanges=[[0-16383]]]]`

In this format, I think it will be clear that both replicas have different IP address

**Comment by mrniko** [comment] 2024-04-18 12:06
You're right!

I have found the cause - race condition with non thread-safe collections.

**Comment by mrniko** [comment] 2024-04-18 12:08
Please try attached version 
[redisson-3.28.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/15024580/redisson-3.28.1-SNAPSHOT.jar.zip)

And share the logs.

**Comment by ajax-yurchenko-v** [comment] 2024-04-18 13:53
> Please try attached version
[redisson-3.28.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/15024580/redisson-3.28.1-SNAPSHOT.jar.zip)

With this version, all works without any reconnections. Looks like fix works)
But one question still opened for me: why total connections count increase after each reconnection and connections to the removed replica still alive? Now we use redisson 3.26.1 and in logs reconnects are present, but total connections count still the same. After 3.27.0 version we received increasing connections count. Is the reason for such reconnections clear?

**Comment by mrniko** [comment] 2024-04-19 05:28
> Now we use redisson 3.26.1 and in logs reconnects are present, but total connections count still the same

That was a second issue. It's fixed now. Thanks for help in testing!

**Closed by mrniko** 2024-04-19 05:28 UTC
Labels: bug
