### ISSUE TITLE
Redisson cannot reconnect to Redis cluster after Redis service is bounced

### ISSUE THREAD

**Issue by stevenli1217** [redisson/redisson#2737] opened 2020-04-29 19:53 UTC
Hello, I'm current experiencing an issue with a Redis cluster(5.0.7) on Redisson 3.12.0 while testing how our system will handle the outage.

I'm using the springboot+Redisson. The test case will keep writing data to Redis Cluster(https://github.com/Grokzen/docker-redis-cluster).  On system startup, everything looks good and cache keys created in all the shards. However, if I take down the entire cluster and restart it again, I saw a bunch of following exception:
`"message":"[RedisException] Failed to set cache for key test_key_85. Node for slot: 13620 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command",`

Per the output of "CLUSTER NODES", all the nodes' status is "connected"
`47419e46ba8f413e5ffb027de3ff8b97afd62bce 127.0.0.1:7005@17005 slave 5a7405b1b79a541f41d489932a6b0eafdb065cd0 0 1588189646053 6 connected
8d8a5c840aace9863b4ba24bf085961159e85bd3 127.0.0.1:7001@17001 master - 0 1588189646000 2 connected 5461-10922
42454fa187444828c9ade52453126dec125e1a9b 127.0.0.1:7004@17004 slave 6aad6a7709c6f06fee8eee3f4d0e94f7e3d0e056 0 1588189647062 5 connected
5a7405b1b79a541f41d489932a6b0eafdb065cd0 127.0.0.1:7000@17000 myself,master - 0 1588189646000 1 connected 0-5460
6aad6a7709c6f06fee8eee3f4d0e94f7e3d0e056 127.0.0.1:7002@17002 master - 0 1588189646054 3 connected 10923-16383
221d400589bfdba00a9fac7181b4222eaed6e23f 127.0.0.1:7003@17003 slave 8d8a5c840aace9863b4ba24bf085961159e85bd3 0 1588189645045 4 connected`

**Expected behavior**
Redisson successfully reconnects to the cluster after the cluster restarts

**Actual behavior**
Throw exception every time the slot is in 2nd/3rd shard, which means slot number is larger than 5460.
`{"thread":"http-nio-9992-exec-1","level":"ERROR","loggerName":"com.doordash.merchantdataservice.common.cache.RedisCacheWrapper","message":"[RedisException] Failed to set cache for key test_key_140. Node for slot: 6285 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1588189837,"nanoOfSecond":770000000},"threadId":161,"threadPriority":5}
Set key test_key_140
Set key test_key_141
{"thread":"http-nio-9992-exec-1","level":"ERROR","loggerName":"com.doordash.merchantdataservice.common.cache.RedisCacheWrapper","message":"[RedisException] Failed to set cache for key test_key_142. Node for slot: 14543 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1588189844,"nanoOfSecond":170831000},"threadId":161,"threadPriority":5}
Set key test_key_142
{"thread":"http-nio-9992-exec-1","level":"ERROR","loggerName":"com.doordash.merchantdataservice.common.cache.RedisCacheWrapper","message":"[RedisException] Failed to set cache for key test_key_143. Node for slot: 10478 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1588189849,"nanoOfSecond":570894000},"threadId":161,"threadPriority":5}
Set key test_key_143
{"thread":"metrics-statsd-reporter-2-thread-1","level":"ERROR","loggerName":"com.codahale.metrics.ScheduledReporter","message":"Exception thrown from StatsDReporter#report. Exception was suppressed.","thrown":{"commonElementCount":0,"localizedMessage":"bound must be positive","message":"bound must be positive","name":"java.lang.IllegalArgumentException","extendedStackTrace":[{"class":"java.util.concurrent.ThreadLocalRandom","method":"nextInt","file":"ThreadLocalRandom.java","line":310,"exact":false,"location":"?","version":"?"},{"class":"com.doordash.util.metrics.StatsDPool","method":"nextIndex","file":"StatsDPool.java","line":28,"exact":false,"location":"dd-util-0.2.12.jar","version":"?"},{"class":"com.doordash.util.metrics.StatsDPool","method":"get","file":"StatsDPool.java","line":24,"exact":false,"location":"dd-util-0.2.12.jar","version":"?"},{"class":"com.doordash.util.metrics.StatsDReporter","method":"report","file":"StatsDReporter.java","line":230,"exact":false,"location":"dd-util-0.2.12.jar","version":"?"},{"class":"com.codahale.metrics.ScheduledReporter","method":"report","file":"ScheduledReporter.java","line":237,"exact":false,"location":"metrics-core-4.0.3.jar","version":"4.0.3"},{"class":"com.codahale.metrics.ScheduledReporter","method":"lambda$start$0","file":"ScheduledReporter.java","line":177,"exact":true,"location":"metrics-core-4.0.3.jar","version":"4.0.3"},{"class":"java.util.concurrent.Executors$RunnableAdapter","method":"call","file":"Executors.java","line":515,"exact":true,"location":"?","version":"?"},{"class":"java.util.concurrent.FutureTask","method":"runAndReset$$$capture","file":"FutureTask.java","line":305,"exact":true,"location":"?","version":"?"},{"class":"java.util.concurrent.FutureTask","method":"runAndReset","file":"FutureTask.java","line":-1,"exact":true,"location":"?","version":"?"},{"class":"java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask","method":"run","file":"ScheduledThreadPoolExecutor.java","line":305,"exact":true,"location":"?","version":"?"},{"class":"java.util.concurrent.ThreadPoolExecutor","method":"runWorker","file":"ThreadPoolExecutor.java","line":1128,"exact":true,"location":"?","version":"?"},{"class":"java.util.concurrent.ThreadPoolExecutor$Worker","method":"run","file":"ThreadPoolExecutor.java","line":628,"exact":true,"location":"?","version":"?"},{"class":"java.lang.Thread","method":"run","file":"Thread.java","line":835,"exact":true,"location":"?","version":"?"}]},"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1588189850,"nanoOfSecond":983894000},"threadId":22,"threadPriority":5}
{"thread":"http-nio-9992-exec-1","level":"ERROR","loggerName":"com.doordash.merchantdataservice.common.cache.RedisCacheWrapper","message":"[RedisException] Failed to set cache for key test_key_144. Node for slot: 6153 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1588189854,"nanoOfSecond":970959000},"threadId":161,"threadPriority":5}
Set key test_key_144`

**Steps to reproduce or test case**

**Redis version**
5.0.7

**Redisson version**
3.12.0

**Redisson configuration**
clusterServersConfig:
  idleConnectionTimeout: 30000
  pingTimeout: 1000
  connectTimeout: 3000
  timeout: 1000
  retryAttempts: 3
  retryInterval: 1000
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: null
  nodeAddresses:
    - "redis://localhost:7001"
  subscriptionsPerConnection: 5
  clientName: MyService
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 10
  slaveConnectionMinimumIdleSize: 1
  slaveConnectionPoolSize: 2
  masterConnectionMinimumIdleSize: 3
  masterConnectionPoolSize: 4
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  scanInterval: 1000
  pingConnectionInterval: 3000
  keepAlive: true
  tcpNoDelay: false
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"

**Comment by mrniko** [comment] 2020-04-30 05:58
Hi,

Set `TRACE` logging level for `org.redisson` package and share output.

**Comment by stevenli1217** [comment] 2020-04-30 22:11
The log is too big and I share it here: 
https://drive.google.com/file/d/196jXZPVgm-EG2Dc7mIy1L_uBfuBo7Q-G/view?usp=sharing

Summary:  My test case keeps writing cache key to Redis cluster. The keys will start from "test_key_0" to "test_key_30".
Step 1. From test_key_0 to teset_key_10, everything looks good.
Step 2. docker kill redis-cluste, and test_key_11 - test_key_18 failed
Steep 3. docker start redis-cluster, I verify that cluster looks good and each nod has connections. But all the cache key updating fails

connection status via "client list"
```
7000: 16
7001: 14
7002: 14
7003: 17
7004: 17
7005: 18
```

result of "Cluster Nodes":
```
af4bfc04dbea8a57c5e4b74f865430ca611729df 127.0.0.1:7003@17003 slave 911848e3e1e8b8325d902b4795012a1f17f14cf2 0 1588284219000 4 connected
911848e3e1e8b8325d902b4795012a1f17f14cf2 127.0.0.1:7000@17000 master - 0 1588284219772 1 connected 0-5460
cc356f0437fcf4d6213c778dc8f314a65c629e4c 127.0.0.1:7004@17004 slave 5f5dea344e5ffa7e55f4b5cc528b9afb95824fc5 0 1588284220576 5 connected
a44c998f6f3de6864f01d8fda22c9cc2ec5d975f 127.0.0.1:7005@17005 myself,slave 3e64ff49d56f822a67baffda1730cd82fa37cc14 0 1588284220000 6 connected
3e64ff49d56f822a67baffda1730cd82fa37cc14 127.0.0.1:7002@17002 master - 0 1588284220576 3 connected 10923-16383
5f5dea344e5ffa7e55f4b5cc528b9afb95824fc5 127.0.0.1:7001@17001 master - 0 1588284219000 2 connected 5461-10922
```

**Comment by stevenli1217** [comment] 2020-05-01 18:27
@mrniko  is this a bug or it's due to my bad configuration?

**Comment by wuwangben** [comment] 2020-05-12 04:06
I have the same problem

**Comment by mrniko** [comment] 2020-05-12 10:48
Unable to reproduce the issue. Please try it again with version attached. Also please attach CLUSTER NODES output before and after Redis cluster restart.

[redisson-3.12.6-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4615031/redisson-3.12.6-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment] 2020-06-04 09:24
Fixed in https://github.com/redisson/redisson/issues/2750

**Closed by mrniko** 2020-06-04 09:24 UTC
Labels: redis-cluster
