### ISSUE TITLE
List value in a RLocalCachedMap returns String

### ISSUE THREAD

**Issue by maddiemccoyyy** [redisson/redisson#1631] opened 2018-09-12 13:26 UTC
I have the following RLocalCachedMap defined:

```
RLocalCachedMap<String, List<String>> rLocalCachedMap;
```
When the following line gets executed:
```
String key = ...
List<String> value = rLocalCachedMap.get(key);
```
I get an exception:
``` 
 java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
```
Seems like may be related to previously submitted issue, however I am using List (not RList)
https://github.com/redisson/redisson/issues/1380

**Comment by mrniko** [comment] 2018-09-15 08:02
Sorry, it's a duplicate of #1380

**Closed by mrniko** 2018-09-15 08:02 UTC
