### ISSUE TITLE
Available permits for `RRateLimiter` not getting updated

### ISSUE THREAD

**Issue by lucifercr07** [redisson/redisson#4176] opened 2022-03-08 07:28 UTC
Using `RRateLimiter` if the thread which acquired the permit crashed or is long-running the permits never again become available again. Have created a rate limiter as below and once the permit is acquired even if the thread crashes or is closed the permit doesn't get available again. 
![image](https://user-images.githubusercontent.com/13472823/157179964-acf3faf0-4686-481a-979f-f6daf1aa4642.png)

**Expected behaviour**
Permits should get available again when the thread crashes or is closed

**Actual behaviour**
Permits not getting available

**Redis version**
`redis_version:6.2.4`

**Redisson version**
3.16.8

**Redisson configuration**

**Comment by sginabreda** [comment] 2022-04-21 18:15
I'll subscribe to this issue. I have a similar case in which I created a rate limiter of 10k per day, with the following command:

`rateLimiter.setRate(RateType.OVERALL, 10_000, 1, RateIntervalUnit.DAYS)`

The 10k permits are consumed during the day, that works correctly. However, I'd expect that at the 24h mark, the permits become available again, but this was not the case. I've been monitoring the available permits with the following command (I'm not sure if its correct, but I dived into Redisson code and I think this is the one being used):

`ZRANGE {rateLimiter}:permits 0 -1`

Let me know if I'm doing something incorrectly or this is something that is not yet delivered and will be part of this feature. Thanks!

**Comment by tyrantkhan** [comment] 2022-05-20 12:41
@mrniko i also see this quite often.. i often have to manually reset the permits on my redis cluster to avoid this issue :(

**Comment by mrniko** [comment] 2023-04-20 08:43
> Using RRateLimiter if the thread which acquired the permit crashed

Unable to reproduce it.

```java
        RRateLimiter rateLimiter = redisson.getRateLimiter("test1");
        rateLimiter.trySetRate(RateType.OVERALL, 5, 60, RateIntervalUnit.SECONDS);

        Thread t = new Thread(() -> {
            for (int i = 0; i < 4; i++) {
                rateLimiter.acquire();
            }
        });
        t.start();

        for (int i = 0; i < 5; i++) {
            System.out.println("i " + i);
            rateLimiter.acquire();
        }
```

**Comment by mrniko** [comment] 2023-04-20 08:49
@sginabreda 

Which version do you use?

**Comment by wclarkpk** [comment] 2023-04-20 14:32
I also experienced this bug.

I had `RRateLimiter` in place for months in production and it was working great (for each customer permit N number per hour, resetting every hour). But then I believe it was either the update to a new version of Redis (we use persistence) or a new version of Redisson when things went haywire (both updates occurred about the same time).

* redis: 6.2.5 -> 7.0.4
* redisson: 3.11.2 -> 3.17.6

After the updates, the rate limiter got into a state where it was not resetting every hour and eventually all permits were exhausted. I don't have the logs any more but at the time it seemed like something changed in the underlying Lua causing some sort of incompatibility. There were some `RedisonException: Lua script` errors thrown but given the async nature of the library the stack dumps didn't contain much info to cross reference to my code and I wasn't able to trace it back to the rate limiter soon enough. This went unreported for about a day and caused some chaos.

Unfortunately, I don't use the feature anymore so I can't really be of much help to debug further, but I thought I'd drop this note to corroborate the story. :-)

**Comment by mrniko** [comment] 2023-04-20 17:44
@wclarkpk 

> RedisonException: Lua script

Was thrown due to ratelimiter internal format change introduced in 3.16.4 version. Ratelimter instances created with previous versions would throw such error. So you need to delete them all before update to 3.16.4+ version.

**Comment by mrniko** [comment] 2023-05-18 07:44
Unable to reproduce the issue with the latest version

**Closed by mrniko** 2023-05-18 07:44 UTC

**Comment by SanyaSingh-Groww** [comment] 2024-03-18 12:04
@mrniko this is happening with new version too 3.26.0
