### ISSUE TITLE
[LoadBalancerManager:200][redisson-netty-2-48][]Unable to unfreeze entry

### ISSUE THREAD

**Issue by yinyansheng** [redisson/redisson#4830] opened 2023-02-01 01:58 UTC
redisson version: 3.18.1
redis env: aws elastic cache redis cluster

config as below
=========
clusterServersConfig:
idleConnectionTimeout: 30000
connectTimeout: 10000
timeout: 3000
retryAttempts: 3
retryInterval: 1500
subscriptionsPerConnection: 5
sslEnableEndpointIdentification: true
sslProvider: "JDK"
pingConnectionInterval: 30000
keepAlive: true
tcpNoDelay: true
nameMapper: !<org.redisson.api.DefaultNameMapper> {}
loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
slaveConnectionMinimumIdleSize: 24
slaveConnectionPoolSize: 64
failedSlaveReconnectionInterval: 3000
failedSlaveCheckInterval: 180000
masterConnectionMinimumIdleSize: 24
masterConnectionPoolSize: 64
readMode: "SLAVE"
subscriptionMode: "MASTER"
subscriptionConnectionMinimumIdleSize: 1
subscriptionConnectionPoolSize: 50
dnsMonitoringInterval: 5000
natMapper: !<org.redisson.api.DefaultNatMapper> {}
nodeAddresses: "xxx.xxx.amazonaws.com:6379"
scanInterval: 5000
checkSlotsCoverage: true
threads: 16
nettyThreads: 64
codec: !<org.redisson.codec.MarshallingCodec> {}
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 30000
checkLockSyncedSlaves: false
reliableTopicWatchdogTimeout: 600000
keepPubSubOrder: true
useScriptCache: false
minCleanUpDelay: 5
maxCleanUpDelay: 1800
cleanUpKeysAmount: 100
nettyHook: !<org.redisson.client.DefaultNettyHook> {}
useThreadClassLoader: true
addressResolverGroupFactory: !<xxx.xxx.xxx.DnsAddressResolverGroupFactory> {}

there are huge error logs as below
=========
`[LoadBalancerManager:200][redisson-netty-2-48][]Unable to unfreeze entry: [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:64:queue:0, freezeReason=MANAGER, client=[addr=redis://10.0.18.249:6379], nodeType=SLAVE, firstFail=1674898223183]
java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 24 were initialized. Server: 10.0.18.249/10.0.18.249:6379
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
    at java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1523) ~[?:?]
    at java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2409) ~[?:?]
    at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:197) ~[redisson-3.18.1.jar:3.18.1]
    at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:122) ~[redisson-3.18.1.jar:3.18.1]
    at org.redisson.connection.MasterSlaveEntry.slaveUpAsync(MasterSlaveEntry.java:467) ~[redisson-3.18.1.jar:3.18.1]
    at org.redisson.cluster.ClusterConnectionManager.addRemoveSlaves(ClusterConnectionManager.java:570) ~[redisson-3.18.1.jar:3.18.1]
    at org.redisson.cluster.ClusterConnectionManager.checkSlaveNodesChange(ClusterConnectionManager.java:496) ~[redisson-3.18.1.jar:3.18.1]
    at org.redisson.cluster.ClusterConnectionManager.lambda$updateClusterState$11(ClusterConnectionManager.java:473) ~[redisson-3.18.1.jar:3.18.1]
    at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183) ~[?:?]
    at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2299) ~[?:?]
    at org.redisson.cluster.ClusterConnectionManager.lambda$updateClusterState$14(ClusterConnectionManager.java:473) ~[redisson-3.18.1.jar:3.18.1]
    at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) [?:?]
    at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) [?:?]
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137) [?:?]
    at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:467) [redisson-3.18.1.jar:3.18.1]
    at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:461) [redisson-3.18.1.jar:3.18.1]
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:392) [redisson-3.18.1.jar:3.18.1]
    at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205) [redisson-3.18.1.jar:3.18.1]
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144) [redisson-3.18.1.jar:3.18.1]
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120) [redisson-3.18.1.jar:3.18.1]
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) [netty-codec-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) [netty-codec-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) [netty-codec-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [netty-transport-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [netty-transport-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.85.Final.jar:4.1.85.Final]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.85.Final.jar:4.1.85.Final]
    at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 24 were initialized. Server: 10.0.18.249/10.0.18.249:6379
    at org.redisson.connection.pool.ConnectionPool.createConnection(ConnectionPool.java:104) ~[redisson-3.18.1.jar:3.18.1]
    at org.redisson.connection.pool.ConnectionPool.initConnections(ConnectionPool.java:92) ~[redisson-3.18.1.jar:3.18.1]
    at org.redisson.connection.pool.ConnectionPool.initConnections(ConnectionPool.java:77) ~[redisson-3.18.1.jar:3.18.1]
    at org.redisson.connection.pool.SlaveConnectionPool.initConnections(SlaveConnectionPool.java:30) ~[redisson-3.18.1.jar:3.18.1]
    at org.redisson.connection.balancer.LoadBalancerManager.unfreezeAsync(LoadBalancerManager.java:194) ~[redisson-3.18.1.jar:3.18.1]
    ... 37 more`

**Comment by itsarraj** [comment] 2023-02-01 04:17
Hello sir ,
I am new to open source contribution.
I already know java , my tech stacks & tools includes C, C++ , Python , Java, JavaScript , HTML , CSS , SQL , Bootstrap, ReactJS, ExpressJS, NodeJS & Git . I need a little help from your side to contribute to these amazing projects.

**Comment by mrniko** [comment] 2023-02-01 07:33
Can you share full stack trace?

**Comment by yinyansheng** [comment] 2023-02-01 07:50
> > ... 37 more
> 
> Can you share full stack trace?

this is the prod logs, be truncated

**Comment by yinyansheng** [comment] 2023-02-02 05:18
@mrniko FYI,anyway thanks first
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/15724040/216238035-7ffcb8c2-fdb9-4ef9-806b-f58202e7cf4b.png">

**Comment by mrniko** [comment] 2023-02-06 07:19
we need a full stack trace to get the cause

**Comment by ofir-popowski** [comment] 2023-02-06 09:32
I'm not sure if this is the same or a separate issue, but yesterday I upgraded our Redisson version from 3.17.4 to 3.19.2. We're using AWS Elasticache (cluster mode disabled, engine version 6.0.5), with about 2000 instances of various services using this cluster. This whole thing happened on our 2 biggest regions.

Most of the configuration we're using is on default values, but we toned down the connection pool sizes (for both primary and replicas) a bit.

What we saw was:
1. millions of logs with `Unable to unfreeze entry` almost identical to the original post in this issue
2. CPU usage across entire cluster skyrocketed, which caused more and more instances to timeout when trying to resolve both primary and replicas
3. almost all GET type commands switched from hitting replicas to hitting primary

I suspect that the GET type commands switched to hitting primary node because the connection pool to replicas. Looking at the AWS metrics dashboard shows the CPU maxing out happened before the GET requests switched

Downgrading back to previous version and rolling it out to production seem to have resolved the issue. There were no other code changes in our deployment, only the Redisson version upgrade. I have never seen this happen before, all other deployments were smooth.

(blue is primary node)

<img width="1296" alt="Screen Shot 2023-02-06 at 10 50 40" src="https://user-images.githubusercontent.com/12687220/216928159-4317ef14-8d90-4b90-9586-b5fa54d6f8a1.png">
<img width="1296" alt="Screen Shot 2023-02-06 at 10 51 13" src="https://user-images.githubusercontent.com/12687220/216928560-6c08cccb-4a4a-442f-8077-a99799c9df1d.png">

Due to the size of our production environment, the increase was nearly instant on our biggest region, but on our 2nd biggest region it seems to have happened a bit more gradually over a couple of hours (which might point to some leak, of something)

I cannot reproduce this in live production environment with trace or debug level logs in this environment (due to the amount of logs being sent, and it hurting our production environment), but I hope this information was useful. I can provide more screenshots of different metrics if it will help.

**Comment by yinyansheng** [comment] 2023-02-07 01:26
> 

"We're using AWS Elasticache (cluster mode disabled, engine version 6.0.5), with about 2000 instances of various services using this cluster. This whole thing happened on our 2 biggest regions."

my production use case very similar to yours, there are about 200 instances connect to a aws redis cluster which contains 64 master and 64 slave nodes

hope helpful

**Comment by mrniko** [comment] 2023-02-07 06:13
@yinyansheng 

Can you try it with 3.17.6, 3.17.7 and 3.18.0 versions?

**Comment by mrniko** [comment] 2023-02-07 09:18
@ofir-popowski 

Can you share connections amount at that moment as well?

**Comment by mrniko** [comment] 2023-02-07 09:28
@ofir-popowski 

> millions of logs with Unable to unfreeze entry almost identical to the original post in this issue

Can you share couple of traces?

**Comment by ofir-popowski** [comment] 2023-02-07 11:06
@mrniko 
> Can you share couple of traces?

Sadly I do not have any trace level logs available. I can share other (error/warn) level logs if that would help, but stacktrace is identical in all of them, with several different "main" messages: unable to unfreeze entry, unable to add slave, io.netty.channel.ConnectTimeoutException: connection timed out.

The following is the very first error log, at 15:20:27

```
Unable to unfreeze entry: [freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=21, freeConnectionsCounter=value:64:queue:0, freezeReason=MANAGER, client=[addr=rediss://replica.REDACTED-HOST:6379], nodeType=SLAVE, firstFail=1675610427399]

java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 21 of 24 were initialized. Redis server: replica.REDACTED-HOST/REDACTED-IP:6379
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1423)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$0(ConnectionPool.java:155)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:318)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$6(ConnectionPool.java:277)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.redisson.client.RedisClient$1$2.run(RedisClient.java:250)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 21 of 24 were initialized. Redis server: replica.REDACTED-HOST/REDACTED-IP:6379
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$0(ConnectionPool.java:154)
	... 19 common frames omitted
Caused by: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: replica.REDACTED-HOST/REDACTED-IP:6379
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
	... 11 common frames omitted
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: replica.REDACTED-HOST/REDACTED-IP:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	... 8 common frames omitted
```

> Do you see this message "Hostname: {} has changed IP from" in logs?

No logs containing the string "hostname" at all. There was no node failure that we could see in the AWS dashboards

> Can you share connections amount at that moment as well?

![Screen Shot 2023-02-07 at 12 52 22](https://user-images.githubusercontent.com/12687220/217225523-9e912039-f210-4020-8c8b-7ea64e092d6a.png)
![Screen Shot 2023-02-07 at 12 52 34](https://user-images.githubusercontent.com/12687220/217225529-76e100dc-09c6-4518-956b-5764dde4d3b2.png)

**Comment by mrniko** [comment] 2023-02-07 11:16
Does this issue related to slave nodes only?

**Comment by ofir-popowski** [comment] 2023-02-07 11:19
Yes I think it was slave nodes only. While master node was under a lot of pressure from the increasing amount of operations, I did not see any errors connecting or working with the master node itself

**Comment by mrniko** [comment] 2023-02-07 13:38
@ofir-popowski 

Can you share your Redisson config?

**Comment by ofir-popowski** [comment] 2023-02-07 13:58
We're using replicated servers, with 2 nodes, one pointing to the primary endpoint and one pointing to the reader endpoint.
All of our Redisson config values are on default, except for the following:

```
masterConnectionPoolSize: 10
masterConnectionMinimumIdleSize: 1
slaveConnectionPoolSize: 10
slaveConnectionMinimumIdleSize: 1
timeout: 10000
```

**Comment by mrniko** [comment] 2023-02-07 14:02
do you see records below? how many?

"slave: {} is down"
"slave: {} added"
"slave: {} is up"

**Comment by ofir-popowski** [comment] 2023-02-07 14:04
0 search results for logs with these strings

**Comment by mrniko** [comment] 2023-02-07 15:21
@ofir-popowski 

When does the issue start happening? From the application start?

**Comment by ofir-popowski** [comment] 2023-02-07 15:33
The deployment with the upgraded Redisson version started at about 15:05. Seeing as it's somewhere between 1500-2000 instances, it took some time for the deployment to finish all of them (about 45 minutes). The first error log was at 15:20. By that time, we probably already had a hundred instances up.

I do not think it was from application start. If I had to guess, I think each instance starting with the upgraded version put more and more pressure on the replicas, until they started to fail connections

**Comment by yinyansheng** [comment] 2023-02-08 01:52
> 

sorry.  downgrade the version is not allowed in prod env

**Comment by yinyansheng** [comment] 2023-02-08 02:05
> @ofir-popowski @yinyansheng
> 
> When does the issue start happening? From the application start?

not from application start, we deploy the service many days and it occurs. 

firstly i guess the issue may cause by redis node failover. the error logs disappear after i restart the services

**Comment by mrniko** [comment] 2023-02-08 07:30
@yinyansheng @ofir-popowski 

Can you share logs since application start moment till the first exception?

**Comment by mrniko** [comment] 2023-02-08 08:12
@yinyansheng @ofir-popowski 

Do you see error "slave {} has been disconnected after {} ms interval since moment of the first failed connection" in logs?

**Comment by ofir-popowski** [comment] 2023-02-08 09:35
@mrniko I would like to apologize and correct a previous mistake. I said there were no logs like these:
> "slave: {} is down"
"slave: {} added"
"slave: {} is up"

But I was mistaken. I was looking at ERROR logs only and those seem to be INFO. Yes there are multiple logs like that.
The attached file is a log (in reverse order) from a single pod. It's the very first pod that was started with Redisson 3.19.2

> Do you see error slave {} has been disconnected after {} ms interval since moment of the first failed connection or info master {} used as slave in logs?

I do not see the "has been disconnected" in the logs, but there are "used as slave" logs

[log.log](https://github.com/redisson/redisson/files/10683894/log.log)

**Comment by mrniko** [comment] 2023-02-08 10:07
Thanks much for the logs. 

I see the cause, you specified `replica.CACHE-HOST.amazonaws.com` as slave which resolved to a single slave out of other slaves in round robin. This is caused slave up/down "slave: [addr=rediss://replica.CACHE-HOST.amazonaws.com:6379] is down"... "slave: replica.CACHE-HOST.amazonaws.com/***.***.43.33:6379 is up". 

https://github.com/redisson/redisson/issues/4437#issuecomment-1305253310

With `replica.CACHE-HOST.amazonaws.com` you won't be able to use all replicas with the same application instance. Hostname resolution in replica mode has been introduced since 3.17.7 version.

**Comment by mrniko** [comment] 2023-02-08 10:11
@ofir-popowski 

To resolve this issue I can introduce `scanHostNames` setting which will be `false` by default.

**Comment by yinyansheng** [comment] 2023-02-09 07:23
> 

thanks, could you describe the resolve solution in more detail.

**Comment by mrniko** [comment] 2023-02-09 09:31
@yinyansheng 

It's related to replicated servers mode. For cluster mode I need logs since application start moment till the first exception. Can you provide it?

**Comment by mrniko** [comment] 2023-02-09 10:29
@ofir-popowski 

`monitorIPChanges` setting has been added

**Comment by ofir-popowski** [comment] 2023-02-09 13:46
Thank you for the quick solution!
I'm not sure I understand what the issue was, and how it was resolved. I'm also unsure how should I decide whether this configuration should be false or true.
I can try it out and let you know if it helped or not.

Additionally, in the meantime, I managed to reproduce the same issue with version 3.17.7
![Screen Shot 2023-02-09 at 15 44 43](https://user-images.githubusercontent.com/12687220/217829498-680cdf6c-e8d2-4e63-9e38-7216a07b1a13.png)
The rise in CPU is from the moment of deploying the 3.17.7 version

**Comment by mrniko** [comment] 2023-02-09 17:11
> he rise in CPU is from the moment of deploying the 3.17.7 version

Hostname resolution during node scan process in replicated mode **has been introduced since 3.17.7 version**. You need to use 3.17.6 or wait for 3.19.3 release. monitorIPChanges is false by default. So you don't need to change configuration

**Comment by yinyansheng** [comment] 2023-02-10 01:04
> @yinyansheng
> 
> It's related to replicated servers mode only. For cluster mode I need logs since application start moment till the first exception. Can you provide it?

i got these error logs two weeks ago, and after restart services ,  do not occur again

**Comment by mrniko** [comment] 2023-02-10 05:32
@yinyansheng 

I'm closing it then. Let me know if you get it again and please attach the logs next time.

**Closed by mrniko** 2023-02-10 05:32 UTC
Labels: AWS

**Comment by yinyansheng** [comment] 2023-02-10 08:08
> @yinyansheng
> 
> I'm closing it then. Let me know if you get it again and please attach the logs next time.

sure thanks for your help

**Comment by mrniko** [comment] 2023-03-03 11:07
> Unable to unfreeze entry: [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:64:queue:0, freezeReason=MANAGER, client=[addr=redis://10.0.18.249:6379], nodeType=SLAVE, firstFail=1674898223183] java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 0 of 24 were initialized.

This error was fixed in https://github.com/redisson/redisson/issues/4902
