### ISSUE TITLE
RObjectLiveService # delete: Incorrect representation obtained by the proxy's RObject getName method

### ISSUE THREAD

**Issue by GenCloud** [redisson/redisson#3069] opened 2020-09-21 19:38 UTC
**Expected behavior**
Getting the correct object identifier to remove it.

**Actual behavior**
There is incorrect behavior when calling RLiveObjectService # delete (T) where T has a name field with an appropriate getter and setter.

**Steps to reproduce or test case**
1) Create simple entity

```java
@REntity
@Data // auto generated getName/setName/getId/setId/equals/hashCode
public class Entity implements Serializable {
    @RId(generator = LongGenerator.class)
    private Long id;
    
    private String name;
}
```

2) Persist and delete entity
```java
public void test() {
        final RLiveObjectService liveObjectService = PersistenceStateManager.getInstance()
                .getSyncClient().getLiveObjectService();
        liveObjectService.registerClass(Entity.class);
        
        Entity entity = new Entity();
        entity = liveObjectService.persist(entity);
        liveObjectService.delete(Entity.class, entity.getId());
}
```

3) See throwed exception:
```io.netty.CodecException: java.lang.NullPointerException``` 

on 

```RedissonLiveObjectService#delete(Object, Rmap, CommandBatchService)#597```

 in new RedissonKeys(ce).deleteAsync(map.getName()) because the proxy object calls its own RObject # getName method, which corresponds to the entity getter, and returns null. Also with the specified value, the entity is not deleted.

Solutions to the problem:
1) check the object for system getters and setters that the proxy object has before loading the class into the cache and registering it in the context
2) check the object for system getters and setters, and, if any, generate additional utility methods

**Redis version**
6.0.6

**Redisson version**
3.13.4

**Redisson configuration**
standard single server (only host and port)

**Comment by mrniko** [comment] 2020-09-24 08:36
Unable to reproduce using following code:

```java
    @REntity
    public static class TestEntity implements Serializable {
        @RId(generator = LongGenerator.class)
        private Long id;

        private String name;

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }

    @Test
    public void test1() {
        RLiveObjectService s = redisson.getLiveObjectService();
        s.registerClass(TestEntity.class);

        TestEntity t1 = new TestEntity();
        t1 = s.persist(t1);

        s.delete(TestIndexed.class, t1.getId());
    }
```

**Comment by GenCloud** [comment] 2020-09-24 10:32
> Unable to reproduce using following code:
> 
> ```java
>     @REntity
>     public static class TestEntity implements Serializable {
>         @RId(generator = LongGenerator.class)
>         private Long id;
> 
>         private String name;
> 
>         public Long getId() {
>             return id;
>         }
> 
>         public void setId(Long id) {
>             this.id = id;
>         }
> 
>         public String getName() {
>             return name;
>         }
> 
>         public void setName(String name) {
>             this.name = name;
>         }
>     }
> 
>     @Test
>     public void test1() {
>         RLiveObjectService s = redisson.getLiveObjectService();
>         s.registerClass(TestEntity.class);
> 
>         TestEntity t1 = new TestEntity();
>         t1 = s.persist(t1);
> 
>         s.delete(TestIndexed.class, t1.getId());
>     }
> ```

Hi, test to reproduce:
```java
public class REntityTest extends AbstractIT {
    @BeforeAll
    public static void before() {
        initialize();
    }

    @AfterAll
    public static void after() {
        defaultShutdownContextAfterTest();
    }

    @Test
    public void test() {
        // wrapper for RLiveObjectService methods
       // register(TestEntity.class)
        final TestRepo testRepo = PersistenceStateManager.getInstance().getRepository(TestRepo.class);

        final TestEntity testEntity = new TestEntity();
        // rLiveObjService.persist(testEntity)
        final TestEntity attached = testRepo.save(testEntity);

        // rLiveObjService.delete(testEntity)
        Assertions.assertThrows(NullPointerException.class, () -> 
                testRepo.delete(attached));
    }
}
```

Full stacktrace:
```
Caused by: org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=254, freeConnectionsCounter=value:510:queue:0, freezeReason=null, client=[addr=redis://localhost:32771], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@465233482 [redisClient=[addr=redis://localhost:32771], channel=[id: 0x0ebe40f0, L:/127.0.0.1:56007 - R:localhost/127.0.0.1:32771], currentCommand=null], command: null, params: null after 3 retry attempts
	at redisson@3.13.4/org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:271)
	at redisson@3.13.4/org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:58)
	at redisson@3.13.4/org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:156)
	at redisson@3.13.4/org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:153)
	at io.netty.common@4.1.50.Final/io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.common@4.1.50.Final/io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.common@4.1.50.Final/io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.common@4.1.50.Final/io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.common@4.1.50.Final/io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.common@4.1.50.Final/io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.common@4.1.50.Final/io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.common@4.1.50.Final/io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
	at io.netty.transport@4.1.50.Final/io.netty.channel.AbstractChannelHandlerContext.notifyOutboundHandlerException(AbstractChannelHandlerContext.java:814)
	at io.netty.transport@4.1.50.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:719)
	at io.netty.transport@4.1.50.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.transport@4.1.50.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.transport@4.1.50.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.transport@4.1.50.Final/io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
	at redisson@3.13.4/org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:88)
	at io.netty.transport@4.1.50.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.transport@4.1.50.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.transport@4.1.50.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.transport@4.1.50.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.netty.transport@4.1.50.Final/io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
	at io.netty.transport@4.1.50.Final/io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299)
	at redisson@3.13.4/org.redisson.client.handler.CommandsQueue.sendData(CommandsQueue.java:114)
	at redisson@3.13.4/org.redisson.client.handler.CommandsQueue.write(CommandsQueue.java:91)
	at io.netty.transport@4.1.50.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.transport@4.1.50.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.transport@4.1.50.Final/io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.common@4.1.50.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.common@4.1.50.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.transport@4.1.50.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.common@4.1.50.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.common@4.1.50.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.common@4.1.50.Final/io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.codec@4.1.50.Final/io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at redisson@3.13.4/org.redisson.client.handler.CommandBatchEncoder.write(CommandBatchEncoder.java:45)
	at io.netty.transport@4.1.50.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	... 23 common frames omitted
Caused by: java.lang.NullPointerException: null
	at redisson@3.13.4/org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:131)
	at redisson@3.13.4/org.redisson.client.handler.CommandEncoder.encode(CommandEncoder.java:100)
	at redisson@3.13.4/org.redisson.client.handler.CommandBatchEncoder.encode(CommandBatchEncoder.java:52)
	at redisson@3.13.4/org.redisson.client.handler.CommandBatchEncoder.encode(CommandBatchEncoder.java:32)
	at io.netty.codec@4.1.50.Final/io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 25 common frames omitted
```

Debug:
![debug](https://user-images.githubusercontent.com/7953029/94134218-66a06e80-fe6a-11ea-9b30-0e556b0064ad.png)

**Comment by mrniko** [comment] 2020-09-24 11:47
Could you share code example with Redisson API only? I can't use thrid-party api

**Comment by GenCloud** [comment] 2020-09-24 13:55
> Не могли бы вы поделиться примером кода только с Redisson API? Я не могу использовать сторонний API

```java
 private final RLiveObjectService rObjectLiveService;
....
    @Override
    public T save(T object) {
        return rObjectLiveService.persist(object);
    }

    @Override
    @SuppressWarnings("unchecked")
    public void delete(T object) {
        if (!rObjectLiveService.isLiveObject(object)) {
            throw new RepositoryException("The object to be deleted must be of type RLiveObject.");
        }

        final ID id = (ID) rObjectLiveService.asLiveObject(object).getLiveObjectId();
        try {
            rObjectLiveService.delete(entityType, id);
        } catch (ClassCastException ignored) {
        }
    }
```

**Comment by mrniko** [comment] 2020-09-25 05:25
Please try version attached

[redisson-3.13.5-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/5280757/redisson-3.13.5-SNAPSHOT.jar.zip)

**Comment by GenCloud** [comment] 2020-09-25 07:10
> Please try version attached
> 
> [redisson-3.13.5-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/5280757/redisson-3.13.5-SNAPSHOT.jar.zip)

This working fine, thx.

**Comment by mrniko** [comment] 2020-09-25 07:11
Thanks for your feedback. Fixed in https://github.com/redisson/redisson/commit/4ddc8ff6a3938fde3be4dda9ef6b8c49b00e4e2e

**Closed by mrniko** 2020-09-25 07:11 UTC
