### ISSUE TITLE
"redissonClient.getMap(redisKey, options)" will return empty after redis service restart

### ISSUE THREAD

**Issue by rexzhong79626** [redisson/redisson#2433] opened 2019-11-27 03:35 UTC
Scenario
Using DB as the persistence data of redis，after redis service restart, redis cache is empty, when "redissonClient.getMap(redisKey, options)", the loader in options is not called.
"redissonClient.getMap(redisKey, options).size()=0"

Expected behavior
the loader in options will called when redis cache is empty
after redis server restart, when calling "redissonclient.getmap (rediskey, options)", redisson finds that the redis cache is empty. It should read the data externally through the loader and load it into the redis cache

Actual behavior
the loader is not excuted, the data in the redis cache is incomplete after the redis server is restarted

Steps to reproduce or test case
restart redis server, do get operation with options, load data from DB

Redis version
any

Redisson version
3.10.1

Redisson configuration
any

**Comment by rexzhong79626** [comment] 2019-11-29 06:31
For this issue, our current temporary solution is to determine whether the size of redissonmap is equal to 0 (redissonClient.getMap(redisKey).size() == 0) before any operation. If it is equal to 0, it means that the redis service has been restarted, it need to call "redissonClient.getMap(redisKey, options).loadAll(true, 1)" to load DB data to redis cache. or query all keys from DB, and then cycle these keys and write the corresponding value back to redis cache by "get" method of "RedissonMap".
// first method:loadAll
// redissonClient.getMap(redisKey, options).loadAll(true, 1);

// the second method:loader options
Iterable<String/*managerid*/> keys = loaderOptions.getLoader().loadAllKeys();
for (String managerid : keys)
{
    redissonClient.getMap(redisKey, loaderOptions).get(managerid);
}
The reason why we only use "loaderoptions"(options has only contain loader, no contain writer)  here is because issue 2411 (https://github.com/redisson/redisson/issues/2411)

**Comment by mrniko** [comment] 2019-11-29 08:42
`size()` method doesn't invoke loader. Data will be loaded again during `RMap.get` method invocation.

**Comment by mrniko** [comment] 2019-11-29 08:43
> The reason why we only use "loaderoptions"(options has only contain loader, no contain writer) here is because issue 2411 (#2411)

this issue resolved in 3.11.6 version

**Comment by rexzhong79626** [comment] 2019-11-30 11:28
The data structure we store in redis is as follows:
key		value
rediskey  	RMap
		rmapkey		rmapvalue
Sometimes we need to get the data of the whole rmap, but if redis service is restarted, the rmap will be empty.
RMap.get() // This will get the data correctly, no matter whether redis is restarted or not, the loader will be called

ConcurrentHashMap<K, V> managers = new ConcurrentHashMap<K, V>();
managers.putAll(RMap); // after redis service restart, local ConcurrentHashMap will not copy any data from RMap, because RMap is empty.

For the redis restart scenario, when we need to get the whole rmap data, if we find that there is no data in redis cache, it means that rmap.size() is 0, we can load all the data related to rediskey from the DB, I don't know if this is a redisson bug, or whether redisson provides this function, or we can only use the above work around to solve this requirement.
Work Around:
// first method:loadAll
// redissonClient.getMap(redisKey, options).loadAll(true, 1);

// the second method:loader options
Iterable<String/managerid/> keys = loaderOptions.getLoader().loadAllKeys();
for (String managerid : keys)
{
redissonClient.getMap(redisKey, loaderOptions).get(managerid);
}

**Comment by rexzhong79626** [comment] 2019-12-02 08:27
@mrniko , could you give us some comments? Our team has been focusing on this issue for a long time. I hope that redisson can provide a unified solution to replace our work around

**Comment by mrniko** [comment] 2019-12-02 10:47
` it means that rmap.size() is 0, we can load all the data related to rediskey from the DB, I don't know if this is a redisson bug, `

it's not a bug since loader is not called `size()` method invocation.

**Comment by mrniko** [comment] 2019-12-02 10:51
I think your current solution with size checking is correct.

**Closed** 2020-01-15 08:08 UTC
