### ISSUE TITLE
Connection Leak

### ISSUE THREAD

**Issue by afuelcell** [redisson/redisson#3871] opened 2021-10-07 22:22 UTC
(Maybe related to https://github.com/redisson/redisson/issues/3840)

**Expected behavior**

Following fresh startup of service utilizing Redisson client, AWS ElastiCache nodes each maintain consistent ~1k active connections from our service without change (with exception of node failovers, re-sharding, etc)

**Actual behavior**

Slow connection leak after deployment of 3.16.3 client & constant spam of new connections being created. Previous client versions (tested all of 3.15.6, 3.16.0, 3.16.1, 3.16.2) have maintained constant ~1k connections per node without new connection spam.

Pattern of connection leak is unclear - connections increased continuously for ~11 hours, slowly decreased over another ~10 hours. Starting experiencing complete cache failure a bit before lowest peak of active connections during leak was hit.

AWS ElastiCache metrics:
(First drop is from trying re-deployment, where connection leak occurred again)
![image](https://user-images.githubusercontent.com/92111973/136460193-2d1756c5-7ff3-4d85-81d6-c34637f4342e.png)
![image](https://user-images.githubusercontent.com/92111973/136461370-c2dc00e3-3e6c-4d98-98b6-7a7e87145590.png)
![image](https://user-images.githubusercontent.com/92111973/136461422-a4db29fa-30e0-4997-bf2f-2305ca8eaad8.png)
![image](https://user-images.githubusercontent.com/92111973/136461475-f8f1aeaf-b981-46f6-b173-7db30d86f6c7.png)

Note that the read replicas of shard 0003 (0003-001, 0003-003) are the problematic ones in this case.

Nodes (as reported by ElastiCache `IsMaster` metric)
Shard 0001:

- Node 001: Master
- Node 002: Read-Replica

Shard 0002:
- Node 001: Master
- Node 002: Read-Replica

Shard 0003:
- Node 001: Read-Replica
- Node 002: Master
- Node 003: Read-Replica

Sample of debug-level logs (sanitized): https://pastebin.com/raw/RKJaYeX7

Reverting to previous client version resolves issue.

**Steps to reproduce or test case**
We have been able to repeat this issue across service deployments, but can't give general reproduction steps.

**Redis version**
5.0.6 (Engine: Clustered Redis)

**Redisson version**
3.16.3

**Redisson configuration**
Transit Encryption: Enabled
Timeout: 200 ms
Connect Timeout: 20 s
Check Slots Coverage: false
Retry Attempts: 1
Retry Interval: 500 ms

**Comment by mrniko** [comment] 2021-10-08 06:25
Can you try attached version?

[redisson-3.16.4-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/7308993/redisson-3.16.4-SNAPSHOT.jar.zip)

**Comment by afuelcell** [comment] 2021-10-08 15:47
Could you push the source code to a branch or provide some type of diff check from 3.16.3? For security & other reasons I cannot pull in that jar file into our environment for usage but I can manually patch source code changes between official Redisson client releases to test.

**Comment by mrniko** [comment] 2021-10-08 16:03
@afuelcell 

You can build master branch. I think it should be fixed by https://github.com/redisson/redisson/commit/33e5b5872b098c13cf1bbf70f8152f7f3d94dc7c

**Comment by mrniko** [comment] 2021-10-11 16:52
According to logs it's related to ClusterConnectionManager. 

```
11 Oct 2021 15:23:58,035 [32m[INFO][m  (redisson-netty-11-7) org.redisson.cluster.ClusterConnectionManager: slave: rediss://<priv-ip-5>:6379 added for slot ranges: [[12678-14002], [2570-5300], [7572-8936], [11272-11311]]
```

It detects ip changes for slave host name.

**Comment by afuelcell** [comment] 2021-10-11 22:25
Searching logs in past hour for "added for slot ranges":
https://pastebin.com/raw/SKfvYkzV

**Comment by mrniko** [comment] 2021-10-12 04:58
Seems that the problem is in hostname resolution. Can you switch to netty 4.1.67.Final ?

**Comment by afuelcell** [comment] 2021-10-12 18:38
Building in netty 4.1.67.Final seems to have *partially* worked. The leak appeared to be prevalent from the start of the deployment of our service and was ongoing up until our last host deployed, at which the connection counts returned to their expected value.

![image](https://user-images.githubusercontent.com/92111973/137010537-72fb45d7-0d36-4acc-9e7c-88bd9db3add1.png)
![image](https://user-images.githubusercontent.com/92111973/137010579-5d0b428b-61b2-49ac-bd97-8a58a0143648.png)

Start & end of the "leak" align with hosts for service coming up.

During the deployment, I had checked and noticed the same "added for slot ranges" logs were appearing that are now no longer appearing after all of the hosts have fully deployed.

**Comment by afuelcell** [comment] 2021-10-12 19:50
It must've been some stroke of luck, because after another try of service deployment we see the same patterns, logs as before (with the slot ranges logs) where the leak has not resolved after deployment.

![image](https://user-images.githubusercontent.com/92111973/137019927-3d0d9b55-ef9b-4599-b9df-748d7d31a282.png)

**Comment by mrniko** [comment] 2021-10-14 08:38
@afuelcell 

I need to sort out what is the problem. Can you set `TRACE` logging level for `io.netty.resolver` package and share output with this issue?

**Comment by afuelcell** [comment] 2021-10-14 22:50
> @afuelcell
> 
> I need to sort out what is the problem. Can you set `TRACE` logging level for `io.netty.resolver` package and share output with this issue?

Here is how the logs look for the most part from what I can see with the connection leak & netty trace logging enabled - 
https://pastebin.com/raw/V5QjqefH

Will test out the other rewrite you gave when I get the chance (likely tomorrow).

**Comment by mrniko** [comment] 2021-10-16 07:49
Can you try this version of resolveIP method (logs added) ?

```java
    private static final Map<RedisURI, RedisURI> MAPPING = new LRUCacheMap<>(100, 0, TimeUnit.DAYS.toMillis(30));

    protected RFuture<RedisURI> resolveIP(String scheme, RedisURI address) {
        if (address.isIP()) {
            RedisURI addr = applyNatMap(address);
            return RedissonPromise.newSucceededFuture(addr);
        }

        RPromise<RedisURI> result = new RedissonPromise<>();
        AddressResolver<InetSocketAddress> resolver = resolverGroup.getResolver(getGroup().next());
        InetSocketAddress addr = InetSocketAddress.createUnresolved(address.getHost(), address.getPort());
        Future<List<InetSocketAddress>> future = resolver.resolveAll(addr);
        future.addListener((FutureListener<List<InetSocketAddress>>) f -> {
            if (!f.isSuccess()) {
                log.error("Unable to resolve " + address, f.cause());
                result.tryFailure(f.cause());
                return;
            }

            List<InetSocketAddress> addrs = f.getNow();
            RedisURI currentURI = MAPPING.get(address);
            if (currentURI != null) {
                InetSocketAddress prevAddr = InetSocketAddress.createUnresolved(currentURI.getHost(), currentURI.getPort());
                log.info("resolved addrs: {}, currentAddr: {}, in list:{}", addrs, prevAddr, addrs.contains(prevAddr));
                if (addrs.contains(prevAddr)) {
                    result.trySuccess(currentURI);
                    return;
                }
            }
            
            InetSocketAddress s = addrs.get(0);
            RedisURI uri = new RedisURI(scheme + "://" + s.getAddress().getHostAddress() + ":" + address.getPort());
            uri = applyNatMap(uri);
            MAPPING.put(address, uri);
            log.info("added addrs: {}, currentAddr: {}, currentURI: {}", addrs, s, currentURI);
            result.trySuccess(uri);
        });
        return result;
    }

```

**Comment by mrniko** [comment] 2021-10-19 06:58
Updated version of the method.

```java
    private static final Map<RedisURI, RedisURI> MAPPING = new LRUCacheMap<>(100, 0, TimeUnit.DAYS.toMillis(30));

    protected RFuture<RedisURI> resolveIP(String scheme, RedisURI address) {
        if (address.isIP()) {
            return RedissonPromise.newSucceededFuture(address);
        }

        RPromise<RedisURI> result = new RedissonPromise<>();
        AddressResolver<InetSocketAddress> resolver = resolverGroup.getResolver(getGroup().next());
        InetSocketAddress addr = InetSocketAddress.createUnresolved(address.getHost(), address.getPort());
        Future<List<InetSocketAddress>> future = resolver.resolveAll(addr);
        future.addListener((FutureListener<List<InetSocketAddress>>) f -> {
            if (!f.isSuccess()) {
                log.error("Unable to resolve " + address, f.cause());
                result.tryFailure(f.cause());
                return;
            }

            List<InetSocketAddress> addrs = f.getNow();
            RedisURI currentURI = MAPPING.get(address);
            if (currentURI != null) {
                byte[] ipaddr = NetUtil.createByteArrayFromIpAddressString(currentURI.getHost());
                InetSocketAddress prevAddr = new InetSocketAddress(InetAddress.getByAddress(address.getHost(), ipaddr), currentURI.getPort());
                log.info("resolved addrs: {}, currentAddr: {}, in list:{}", addrs, prevAddr, addrs.contains(prevAddr));
                if (addrs.contains(prevAddr)) {
                    result.trySuccess(currentURI);
                    return;
                }
            }

            InetSocketAddress s = addrs.get(0);
            RedisURI uri = new RedisURI(scheme + "://" + s.getAddress().getHostAddress() + ":" + address.getPort());
            uri = applyNatMap(uri);
            MAPPING.put(address, uri);
            log.info("added addrs: {}, currentAddr: {}, currentURI: {}", addrs, s, currentURI);
            result.trySuccess(uri);
        });
        return result;
    }
```

**Comment by afuelcell** [comment] 2021-10-19 17:43
> @afuelcell
> 
> I modified three classes. Please add them and try to reproduce the issue.
> 
> [archive updated] [redisson.zip](https://github.com/redisson/redisson/files/7372646/redisson.zip)

This seems to have fixed the issue as far as I can tell. Cannot reproduce the issue on either of the two fleets that I was seeing the leak on before. The current connection counts are stable upon deployment and there are no constant new connection spikes as we had seen previously.

Here are some sample redis logs for verification purposes if needed: https://pastebin.com/raw/whFXGjDB

**Comment by mrniko** [comment] 2021-10-20 04:54
> I am seeing different patterns for the failover (no current connection increase to the new primary) compared to previous version

can you share logs with recorded failover?

> After the time of starting node failover, we have seen increased latency to our service that hasn't recovered. Here is logs briefly after failover, and before did the addition of read-replica: https://pastebin.com/raw/w0u95Efb

You may turn off logs for `io.netty` package. Cluster node state doesn't report any failed node.

**Closed as completed** 2021-10-20 06:03 UTC
Labels: bug
