### ISSUE TITLE
RScheduledExecutorService futures don't complete when they actually complete

### ISSUE THREAD

**Issue by vtkstef** [redisson/redisson#6176] opened 2024-09-17 18:52 UTC
### Redis version

7.4.0

### Redisson version

3.36.0

### Redisson configuration

---
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 10
  sslEnableEndpointIdentification: true
  sslProvider: "JDK"
  pingConnectionInterval: 0
  keepAlive: false
  tcpNoDelay: true
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 8
  connectionMinimumIdleSize: 1
  connectionPoolSize: 16
  database: 0
  dnsMonitoringInterval: 5000
threads: 4
nettyThreads: 12
referenceEnabled: true
transportMode: "NIO"
keepPubSubOrder: true
useScriptCache: true
minCleanUpDelay: 5
maxCleanUpDelay: 1800
cleanUpKeysAmount: 100
lockWatchdogTimeout: 60000

### What is the Expected behavior?

future should complete when the submitted task completes

### What is the Actual behavior?

spuriously it does not.

### Additional information

I submit 8 parallel tasks to a scheduler configured as such
```kotlin
    @Provides
    @Singleton
    @Named("redisson-node-executor")
    fun provideRedissonNodeExecutor(): ExecutorService {
        val threadFactory = ThreadFactoryBuilder()
            .setNameFormat("redisson-node-%d")
            .setDaemon(true)
            .build()
        val queue: BlockingQueue<Runnable> = object : LinkedTransferQueue<Runnable>() {
            override fun offer(runnable: Runnable): Boolean {
                return tryTransfer(runnable)
            }
        }
        return ThreadPoolExecutor(
            2,
            8,
            600L,
            SECONDS,
            queue,
            threadFactory
        ).apply {
            rejectedExecutionHandler = RejectedExecutionHandler { r, exc ->
                try {
                    exc.queue.put(r)
                } catch (e: InterruptedException) {
                    Thread.currentThread().interrupt()
                }
            }
        }
    }

    @Inject
    @Provides
    @Singleton
    fun provideRedissonExecutorNodeConfiguration(
        appCtx: AnnotationConfigApplicationContext,
        @Named("redisson-node-executor") executor: ExecutorService
    ): WorkerOptions = WorkerOptions.defaults()
        .executorService(executor)
        .workers(2)
        .beanFactory(DefaultListableBeanFactory(appCtx))
        .taskTimeout(20, SECONDS)
        .addListener(SuccessListener)
        .addListener(FailureListener)
        .addListener(StartedListener)
```
the started and success listeners log the following
```
INFO  2024-09-17T18:13:12.533Z viable-accounts<unknown> "redisson-node-0" [] c.t.s.v.t.StartedListener - started task_id=14aef696de93e413cc0e286cf9ace47c
INFO  2024-09-17T18:13:12.538Z viable-accounts<unknown> "redisson-node-1" [] c.t.s.v.t.StartedListener - started task_id=47f3ba5a4f852ecec4ff1924014d053b
INFO  2024-09-17T18:13:12.550Z viable-accounts<unknown> "redisson-node-0" [] c.t.s.v.t.SuccessListener - successful task offload for task_id=14aef696de93e413cc0e286cf9ace47c
INFO  2024-09-17T18:13:12.554Z viable-accounts<unknown> "redisson-node-1" [] c.t.s.v.t.SuccessListener - successful task offload for task_id=47f3ba5a4f852ecec4ff1924014d053b
INFO  2024-09-17T18:13:12.581Z viable-accounts<unknown> "redisson-node-0" [] c.t.s.v.t.StartedListener - started task_id=737907aeea4f664693c5c01204bec91b
INFO  2024-09-17T18:13:12.592Z viable-accounts<unknown> "redisson-node-1" [] c.t.s.v.t.StartedListener - started task_id=0df19e4c0f03fe266acad57684e9c703
INFO  2024-09-17T18:13:12.598Z viable-accounts<unknown> "redisson-node-0" [] c.t.s.v.t.SuccessListener - successful task offload for task_id=737907aeea4f664693c5c01204bec91b
INFO  2024-09-17T18:13:12.609Z viable-accounts<unknown> "redisson-node-1" [] c.t.s.v.t.SuccessListener - successful task offload for task_id=0df19e4c0f03fe266acad57684e9c703
INFO  2024-09-17T18:13:12.629Z viable-accounts<unknown> "redisson-node-0" [] c.t.s.v.t.StartedListener - started task_id=7aa95ce6b81f78b5793b9642b79eaaad
INFO  2024-09-17T18:13:12.639Z viable-accounts<unknown> "redisson-node-1" [] c.t.s.v.t.StartedListener - started task_id=b44bd05b24d77cd1649d2843c8350c05
INFO  2024-09-17T18:13:12.651Z viable-accounts<unknown> "redisson-node-0" [] c.t.s.v.t.SuccessListener - successful task offload for task_id=7aa95ce6b81f78b5793b9642b79eaaad
INFO  2024-09-17T18:13:12.668Z viable-accounts<unknown> "redisson-node-1" [] c.t.s.v.t.SuccessListener - successful task offload for task_id=b44bd05b24d77cd1649d2843c8350c05
INFO  2024-09-17T18:13:12.689Z viable-accounts<unknown> "redisson-node-0" [] c.t.s.v.t.StartedListener - started task_id=1079496c052bb27f56e158bc15262b93
INFO  2024-09-17T18:13:12.695Z viable-accounts<unknown> "redisson-node-1" [] c.t.s.v.t.StartedListener - started task_id=8bd97ddfbd3096c69a1e823f9a99b912
INFO  2024-09-17T18:13:12.710Z viable-accounts<unknown> "redisson-node-0" [] c.t.s.v.t.SuccessListener - successful task offload for task_id=1079496c052bb27f56e158bc15262b93
INFO  2024-09-17T18:13:12.713Z viable-accounts<unknown> "redisson-node-1" [] c.t.s.v.t.SuccessListener - successful task offload for task_id=8bd97ddfbd3096c69a1e823f9a99b912
```
all the tasks were started, and all the tasks completed. The task itself is extremely short lived as I don't want to impinge too much on the node executors.

yet while I wait for the future to complete on some sporadic  occasions futures wont complete. I was able to work around this with the following tidbit
```kotlin
    private suspend fun submitLoads(commands: List<PrimeLoadPartition>) = coroutineScope {
        val jobId = commands.first().command.jid.job
        withContext(CoroutineName("submitting jobId $jobId") + Dispatchers.IO + SupervisorJob()) {
            val defers = commands.map { executor.submit(it).toCompletableFuture().asDeferred() }
            val execIds = withTimeoutOrNull(Duration.ofSeconds(30)) {
                defers.awaitAll().mapNotNull { PrimeLoadPartition.resolve(it) }.associate { it }
            }.ifNull {
                defers.filter { it.isCompleted }.map { it.await() }.mapNotNull {
                    PrimeLoadPartition.resolve(it)
                }.associate { it }
            }
            if (execIds.size < commands.size) {
                val observed = execIds.values.map { it.partition }.toSet()
                commands.map { it.command.jid }.forEach { jid ->
                    if (jid.partition !in observed) {
                        logger.warn { "was not able to observe handoff for task ${jid.taskId} within 30 seconds" }
                    }
                }
            }
        }
    }
```
occasionally i may see one or two not complete in this case though none of them did
```
WARN  2024-09-17T18:13:42.603Z viable-accounts<unknown> "DefaultDispatcher-worker-26 @submitting jobId 08MFLylZGHD2KqTC8HTLMe#518" [] c.t.s.v.j.JobManager - was not able to observe handoff for task 08MFLylZGHD2KqTC8HTLMe/00 within 30 seconds
WARN  2024-09-17T18:13:42.603Z viable-accounts<unknown> "DefaultDispatcher-worker-26 @submitting jobId 08MFLylZGHD2KqTC8HTLMe#518" [] c.t.s.v.j.JobManager - was not able to observe handoff for task 08MFLylZGHD2KqTC8HTLMe/01 within 30 seconds
WARN  2024-09-17T18:13:42.603Z viable-accounts<unknown> "DefaultDispatcher-worker-26 @submitting jobId 08MFLylZGHD2KqTC8HTLMe#518" [] c.t.s.v.j.JobManager - was not able to observe handoff for task 08MFLylZGHD2KqTC8HTLMe/02 within 30 seconds
WARN  2024-09-17T18:13:42.603Z viable-accounts<unknown> "DefaultDispatcher-worker-26 @submitting jobId 08MFLylZGHD2KqTC8HTLMe#518" [] c.t.s.v.j.JobManager - was not able to observe handoff for task 08MFLylZGHD2KqTC8HTLMe/03 within 30 seconds
WARN  2024-09-17T18:13:42.603Z viable-accounts<unknown> "DefaultDispatcher-worker-26 @submitting jobId 08MFLylZGHD2KqTC8HTLMe#518" [] c.t.s.v.j.JobManager - was not able to observe handoff for task 08MFLylZGHD2KqTC8HTLMe/04 within 30 seconds
WARN  2024-09-17T18:13:42.603Z viable-accounts<unknown> "DefaultDispatcher-worker-26 @submitting jobId 08MFLylZGHD2KqTC8HTLMe#518" [] c.t.s.v.j.JobManager - was not able to observe handoff for task 08MFLylZGHD2KqTC8HTLMe/05 within 30 seconds
WARN  2024-09-17T18:13:42.603Z viable-accounts<unknown> "DefaultDispatcher-worker-26 @submitting jobId 08MFLylZGHD2KqTC8HTLMe#518" [] c.t.s.v.j.JobManager - was not able to observe handoff for task 08MFLylZGHD2KqTC8HTLMe/06 within 30 seconds
WARN  2024-09-17T18:13:42.603Z viable-accounts<unknown> "DefaultDispatcher-worker-26 @submitting jobId 08MFLylZGHD2KqTC8HTLMe#518" [] c.t.s.v.j.JobManager - was not able to observe handoff for task 08MFLylZGHD2KqTC8HTLMe/07 within 30 seconds
```
NB the last successful handoff was at `2024-09-17T18:13:12.713Z`

**Comment by mrniko** [comment] 2024-09-18 06:53
Do you mean feature object returned by `RExecutorService#submit(Runnable)` method?

**Comment by vtkstef** [comment] 2024-09-24 16:27
I use the variant that submits callables in my case `Callable<String>`

**Comment by seakider** [comment] 2024-12-24 14:40
@vtkstef Sorry, I can't reproduce your problem. Can you provide more information? Also, would mapNotNull { PrimeLoadPartition.resolve(it) } filter out some completed futures?

**Comment by mrniko** [comment] 2024-12-25 07:03
It can be connected to https://github.com/redisson/redisson/issues/6271

**Comment by mrniko** [comment] 2024-12-25 07:06
I'm closing it. Let us know if issue appears with 3.41.1 version.

**Closed by mrniko** 2024-12-25 07:06 UTC

**Comment by mrniko** [comment] 2025-01-07 15:03
Sorry, it's a 3.42.0 version
