### ISSUE TITLE
Redisson Using AWS Elasticache / Problems Connecting

### ISSUE THREAD

**Issue by tendryll** [redisson/redisson#4131] opened 2022-02-10 15:32 UTC
An application, that I am trying to troubleshoot, is unable to establish connections to a Redis replica, using AWS Elasticache, using the Redisson Java client. An example of an exception that occurs is this:

``` 
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: '<redis-replica-2-domain>' failed to resolve '<redis-replica-2-domain>'
    at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:901)
    at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:860)
    at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:328)
    at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:63)
    at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:377)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
    at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
    at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
    at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:220)
    at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:43)
    at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:170)
    at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748) io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.162.24.2:53] query timed out after 5000 milliseconds (no stack trace available)
 ```
 
The settings, and the values that they are being set to, are as follows:
 
nodeAddresses: <node address 1>,<node address 2>,<node address 3>
password: <password>
port: 6379
masterConnectionMinimumIdleSize: 5
slaveConnectionMinimumIdleSize: 5
masterConnectionPoolSize: 15
slaveConnectionPoolSize: 15
nettyThreads: 20
retryAttempts: 3
retryInterval: 1500 (in milliseconds)
connectTimeout: 30000 (in milliseconds)
subscriptionConnectionMinimumIdleSize: 10
subscriptionConnectionPoolSize: 15
scanInterval: 2000
 
Any thoughts on how I can resolve this issue?
 
We have used versions 3.16.8 and 3.10.1 of the Redisson library.

**Comment by mrniko** [comment] 2022-02-11 05:55
> io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.162.24.2:53] query timed out after 5000 milliseconds

This is the cause of the issue. Did you check your link to dns server? also you can try to update netty lib to the latest version.

**Comment by jonathannaguin** [comment] 2022-03-01 14:47
Hey @mrniko, we have also experienced this issue, the exception we see in the logs:
```
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'xxx.xxx.xx.xx.yyy.cache.amazonaws.com' failed to resolve 'xxx.xxx.xx.xx.yyy.cache.amazonaws.com'
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1046)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:999)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:417)
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:65)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:466)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:224)
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:176)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.X.X.2:53] query via UDP timed out after 5000 milliseconds (no stack trace available)
```

Raised from org.redisson.connection.DNSMonitor.

We are using Route53, no issues with the service when the exception happened.

**Comment by mrniko** [comment] 2022-03-01 15:42
@jonathannaguin 

From release to release netty project fixes issues related to dns-layer. Can you try netty latest version?

**Comment by jonathannaguin** [comment] 2022-03-01 15:49
@mrniko  I am using io.netty:netty-resolver-dns:4.1.68.Final and will take some time to get to the latest version... 
Just wondering though, is this actually an `error` on the DNSMonitor if in one iteration fails to resolve a dns record?

**Comment by EXPEbdodla** [comment] 2022-03-07 18:26
@mrniko We also have same issue with 3.16.8 and 3.10.3 versions. Any fix for this issue?

**Comment by mrniko** [comment] 2022-03-18 05:59
@EXPEbdodla 

> No issue with 2.8.2 version

This released doesn't use netty dns resolver.

**Comment by jonathannaguin** [comment] 2022-03-23 15:13
This keeps happening, once a week now -- there are other issues related to the same problem so wondering if we should have an option to turn this off?

**Comment by mrniko** [comment] 2022-03-24 11:20
@jonathannaguin 
Did you update netty to the latest? as option you can set dnsMonitoringInterval = -1 to disable host monitoring.

**Comment by ant76050391** [comment] 2022-04-11 04:40
I am going through the same thing. netty is using the latest version (4.1.75.Final). Wouldn't changing dnsMonitoringInterval to -1 as suggested by @mrniko  would lead to failover detection and other issues?

**Comment by ant76050391** [comment] 2022-04-14 01:32
I adjusted the setDnsMonitoringInterval to -1, but I didn't see any noticeable outliers in the failover tests, so I decided to keep it. However, since this is the first application today, we will report after watching to see if the same error occurs in the future.

**Comment by ant76050391** [comment] 2022-04-20 00:39
setDnsMonitoringInterval이 -1로 설정된 경우에도 여전히 발생합니다.

**Comment by kangwen** [comment] 2022-07-04 02:37
i' got this problem also. 
redis  use AWS cloud.  my pc use VPN connect AWS vpc. 
When i start my springboot ,this occurs " io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname:..."

my redisson version is 3.17.0 ,through redisson-spring-boot-starter:3.17.0, with netty version is 4.1.70

**Comment by jonathannaguin** [comment] 2022-08-29 08:56
I upgraded to io.netty:netty-resolver-dns 4.1.77.Final in our live environment and we still see some of these issues occasionally. Is "dnsMonitoringInterval" an option we can turn off from the Spring properties?

**Comment by mrniko** [comment] 2022-10-06 12:12
Can you try this implementation of AddressResolverGroupFactory
https://github.com/redisson/redisson/pull/4577#issuecomment-1269509090 ? It allows to adjust rate of dns queries per defined time interval.

**Comment by mrniko** [comment] 2022-10-12 10:12
Fixed in https://github.com/redisson/redisson/issues/1625

**Closed by mrniko** 2022-10-12 10:12 UTC
Labels: dns
