### ISSUE TITLE
调用rScoredSortedSet.getScore(100);方法时需要处理空指针

### ISSUE THREAD

**Issue by HorizonHero** [redisson/redisson#1014] opened 2017-08-24 08:58 UTC
我用RScoredSortedSet<Integer> rScoredSortedSet=redissonClient.getScoredSortedSet("ConsumingTime");获取到RScoredSortedSet，然后调用rScoredSortedSet.getScore(100);方法。
当我的redis中没有100对应的值时会报NullPointerException。
这个似乎不太合理，如果没有值可以返回0。但是直接报NullPointerException，我需要自己处理rScoredSortedSet.getScore(100);一层一层抛出来的异常。

**Comment by mrniko** [comment] 2017-09-04 13:44
Hi!

Can you provide how to reproduce it? Because I'm getting `null` instead of `NullPointerException`

```java
        RScoredSortedSet<String> set1 = redisson.getScoredSortedSet("simple1");
        Double s = set1.getScore("123");
        // s = null
```

**Comment by johnou** [comment] 2017-09-04 18:59
@mrniko they are probably assigning to a primitive which will result in an NPE..

```java
double s = set1.getScore("123");
```

**Comment by HorizonHero** [comment] 2017-09-05 00:48
@mrniko  I run a test method, I will be implemented after the information screenshots posted
![rediserror](https://user-images.githubusercontent.com/25317804/30040773-2d59b3b6-9216-11e7-86d4-838834593aa0.png)
Also, my rScoredSortedSet is not null, I'm sure.

**Comment by johnou** [comment] 2017-09-05 07:15
@horizonhero getScore can return null, you should use object double, not primitive otherwise when unboxing my result in an NPE.

**Comment by mrniko** [comment] 2017-09-05 08:20
@HorizonHero It's not a bug, method returns `null` if there is no record in Redis. Please `Double` type for result type.

**Comment by HorizonHero** [comment] 2017-09-06 00:24
@mrniko @johnou Oh I see.Thank you.

**Closed** 2017-09-06 07:35 UTC
