### ISSUE TITLE
connectionListener methods won't get triggered

### ISSUE THREAD

**Issue by okanck** [redisson/redisson#986] opened 2017-07-24 10:33 UTC
I wanted to sure the connection still alive while putting objects to Redis and so tried to add connection listener. But the methods won't get triggered.

The redis version I'm working on:
> ➜  ~ redis-server --version
Redis server v=3.2.9 sha=00000000:0 malloc=libc bits=64 build=d97708fd9e007be7
```java
	private static boolean connected = false;
	private static boolean running = true;

	public static void main(String[] args) {
		Config config = new Config();
		config.useSingleServer().setAddress("127.0.0.1:6379");

		RedissonClient redissonClient = Redisson.create(config);
		redissonClient.getNodesGroup().addConnectionListener(new ConnectionListener() {
			@Override
			public void onConnect(InetSocketAddress inetSocketAddress) {
				connected = true;
				System.out.println("Redis server connected");
			}

			@Override
			public void onDisconnect(InetSocketAddress inetSocketAddress) {
				connected = false;
				System.out.println("Redis server disconnected");
			}
		});

		while (running) {

			System.out.println("Redis status: " + connected);

			try {
				Thread.sleep(1000);
			}
			catch (InterruptedException e) {
				running = false;
			}
		}
	}
```
The output:
> [main] INFO org.redisson.Version - Redisson 3.3.2
[redisson-netty-1-4] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for /127.0.0.1:6379
[redisson-netty-1-3] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /127.0.0.1:6379
Redis status: false
Redis status: false
Redis status: false
Redis status: false
Redis status: false
Redis status: false

**Comment by mrniko** [comment] 2017-07-26 13:59
This issue was fixed in https://github.com/redisson/redisson/commit/a6fbdf5cb45dbe744902729c3f5f7ad671248df9 - version 3.4.4

**Comment by santoshJD** [comment] 2019-10-10 09:58
facing this same issue in 3.11.4 release.

**Comment by mrniko** [comment] 2019-10-10 10:08
@santoshJD 

Could you provide some test code to reproduce it?

**Comment by santoshJD** [comment] 2019-10-10 10:15
`redisConfig.useClusterServers().addNodeAddress(connectString.toArray(new String[connectString.size()]));
				redisClient = Redisson.create(redisConfig);
				redisClient.getNodesGroup().addConnectionListener(new ConnectionListener() {

					//@Override
					public void onConnect(InetSocketAddress inetSocketAddress) {
						logger.info("Redis server connected");
					}

					//@Override
					public void onDisconnect(InetSocketAddress inetSocketAddress) {
						logger.info(inetSocketAddress.toString());
						logger.error("Redis connection failed");
					}
				});
` 
connection is active , can do operation on it. but the onConnect connection is never invoked.

**Comment by mrniko** [comment] 2019-10-30 08:25
@santoshJD

onConnect method is not invoked since Redisson is already up.

**Closed** 2019-10-30 08:26 UTC

**Comment by santoshJD** [comment] 2019-11-05 04:00
connectionListener methods (onDisconnect,onConnect) getting called after certain time continuously.

**Comment by mrniko** [comment] 2019-11-05 08:41
@santoshJD 

please set debug for org.redisson and check for logs from ConnectionWatchdog class

**Comment by mrniko** [comment] 2021-03-26 07:07
listener registered via `Config.setConnectionListener()` now invokes `onConnect()` method.
