### ISSUE TITLE
Live Object with Map<> field

### ISSUE THREAD

**Issue by autochartfish** [redisson/redisson#929] opened 2017-06-20 15:31 UTC
I am trying to use a Live Object with a Map<DateTime, T> field. I use the rLiveObjectService.merge() to persist to Redis.

I can retrieve the Live Object OK using get(), but the Map field is always empty. I have stepped through the code and the Map field is populated OK - something appears to be going wrong when persisting the Map to Redis.

If I use a List<T> field, this returns correctly i.e. is populated.

From the Live Object example code, the Map should work.

I'm using Redisson 3.4.3.

Are there any known issues with using a Map<> field on Live Object?

**Comment by jackygurui** [comment] 2017-06-20 16:42
Can you show me the code if it is possible?

**Comment by autochartfish** [comment] 2017-06-21 06:12
Here is the method to persist to Redis:

public void cacheCandles(List<DataFeedInsertItem> candles) {
        DataFeedSymbol dataFeedSymbol = new DataFeedSymbol(candles.get(0).getDataFeed(), candles.get(0).getSymbol(), candles.get(0).getInterval());
        rLiveObjectService.merge(dataFeedSymbol);

        Map<DateTime, DataFeedInsertItem> candleMap = new HashMap<>();

        for (DataFeedInsertItem candle : candles) {
            LOGGER.debug("Cacheing the candles: DataFeed: {}; Symbol: {}; Interval: {}", candle.getDataFeed(), candle.getSymbol(), candle.getInterval());
           
			candleMap.put(candle.getPriceDatetime(), candle);
        }
        dataFeedSymbol.setDataFeedInsertItemMap(candleMap);
    }

And the Live Object:

import org.joda.time.DateTime;
import org.redisson.api.annotation.REntity;
import org.redisson.api.annotation.RId;

import java.util.HashMap;
import java.util.Map;

@REntity
public class DataFeedSymbol {

    @RId
    private DataFeedSymbolKey dataFeedSymbolKey;

    private String symbolName;
    private String dataFeedName;
    private Integer interval;
    private Map<DateTime, DataFeedInsertItem> dataFeedInsertItemMap;

    protected DataFeedSymbol() {
        super();
    }

    public DataFeedSymbol(String dataFeedName, String symbolName, Integer interval) {
        super();
        this.dataFeedName = dataFeedName;
        this.symbolName = symbolName;
        this.interval = interval;
        this.dataFeedSymbolKey = new DataFeedSymbolKey(dataFeedName, symbolName, interval);
        this.dataFeedInsertItemMap = new HashMap<>();
    }
    public String getSymbolName() {
        return symbolName;
    }

    public void setSymbolName(String symbolName) {
        this.symbolName = symbolName;
    }

    public String getDataFeedName() {
        return dataFeedName;
    }

    public void setDataFeedName(String dataFeedName) {
        this.dataFeedName = dataFeedName;
    }

    public Integer getInterval() {
        return interval;
    }

    public void setInterval(Integer interval) {
        this.interval = interval;
    }

    public void setDataFeedInsertItemMap(Map<DateTime, DataFeedInsertItem> dataFeedInsertItemMap) {
        this.dataFeedInsertItemMap = dataFeedInsertItemMap;
    }

    public Map<DateTime, DataFeedInsertItem> getDataFeedInsertItemMap() {
        return dataFeedInsertItemMap;
    }

    public void addDataFeedInsertItemToMap(DataFeedInsertItem dataFeedInsertItem) {
       getDataFeedInsertItemMap().put(dataFeedInsertItem.getPriceDatetime(), dataFeedInsertItem);
    }
}

**Comment by autochartfish** [comment] 2017-06-21 09:14
I have now also checked the LiveObjectServiceExamples and it also looks like the Product class with Map<> field also does not return the Map<> field, using:
`Map<String, Integer> prodItems = attachedProduct.getItemName2Amount();`

Can you confirm that on your side?

**Comment by jackygurui** [comment] 2017-06-21 14:04
@autochartfish Thank you for sharing the code snippet. I think the problem is the limitation of invoking proxied method internally:
```java
public void addDataFeedInsertItemToMap(DataFeedInsertItem dataFeedInsertItem) {
   getDataFeedInsertItemMap().put(dataFeedInsertItem.getPriceDatetime(), dataFeedInsertItem);
}
```
Please let me explain why:
As you probably already know, Live Objects are proxied classes. The getter and setter of the declared fields are proxied and remapped to hash operations. In another word, the content of those methods were never executed. 

And when you calling a proxied method `addDataFeedInsertItemToMap` inside itself, you are not invoking the `getDataFeedInsertItemMap` method on the proxy reference but rather your own reference. So in reality you are "putting" the items inside your local JVM instead of in to Redis.

You can read about this [at here](http://docs.spring.io/spring/docs/3.1.x/spring-framework-reference/html/aop.html#aop-understanding-aop-proxies). Although this is a spring document but the concept is the same here.

I understand you took code from the example, I apologise an outstanding PR has not yet been merged in to fix this issue.

**Closed** 2018-12-30 05:42 UTC
