### ISSUE TITLE
redisson print slots added and slots removed when application run a period of time

### ISSUE THREAD

**Issue by allmelgr** [redisson/redisson#3904] opened 2021-10-21 03:09 UTC
**redisson version: 3.16.2
and use redisson-spring-data-21 to adapter spring boot 2.1.6.RELEASE
os: red hat 7.6**

here is the log of org.redisson.cluster when it start print the infos

2021-10-21 06:39:40.317 [redisson-netty-2-2] DEBUG org.redisson.cluster.ClusterConnectionManager - cluster nodes state got from 192.168.101.30/192.168.101.30:6379:
229cba3ccc4ef32257638e506a4f0734d3572741 192.168.101.32:6380@16380 slave 3345f93588019048d901f0aa405d5cad4a8b71c2 0 1634769602577 3 connected
3bb628f2a70fd72b7682375260c202ff57fe9ced 192.168.101.32:6379@16379 master - 0 1634769603982 5 connected 10923-16383
2dd60672e8ffac23935da781e7002ba54d08a374 192.168.101.31:6380@16380 slave c4171c39d5f799748b355c9b57e427ce004408a8 0 1634769603000 1 connected
bd73b7da0bbb5ae7295adae3e7e6a9fe22f5439f 192.168.101.30:6380@16380 slave 3bb628f2a70fd72b7682375260c202ff57fe9ced 0 1634769602978 5 connected
3345f93588019048d901f0aa405d5cad4a8b71c2 192.168.101.31:6379@16379 master - 0 1634769603578 3 connected 5461-10922
c4171c39d5f799748b355c9b57e427ce004408a8 192.168.101.30:6379@16379 myself,master - 0 1634769603000 1 connected 0-5460

2021-10-21 06:39:45.323 [redisson-netty-2-2] DEBUG org.redisson.cluster.ClusterConnectionManager - cluster nodes state got from 192.168.101.30/192.168.101.30:6379:
229cba3ccc4ef32257638e506a4f0734d3572741 192.168.101.32:6380@16380 slave 3345f93588019048d901f0aa405d5cad4a8b71c2 0 1634769609598 3 connected
3bb628f2a70fd72b7682375260c202ff57fe9ced 192.168.101.32:6379@16379 master - 0 1634769608000 5 connected 10923-16383
2dd60672e8ffac23935da781e7002ba54d08a374 192.168.101.31:6380@16380 slave c4171c39d5f799748b355c9b57e427ce004408a8 0 1634769608997 1 connected
bd73b7da0bbb5ae7295adae3e7e6a9fe22f5439f 192.168.101.30:6380@16380 slave 3bb628f2a70fd72b7682375260c202ff57fe9ced 0 1634769608595 5 connected
3345f93588019048d901f0aa405d5cad4a8b71c2 192.168.101.31:6379@16379 master - 0 1634769608595 3 connected 5461-10922
c4171c39d5f799748b355c9b57e427ce004408a8 192.168.101.30:6379@16379 myself,master - 0 1634769607000 1 connected 0-5460

2021-10-21 06:39:45.326 [redisson-netty-2-2] INFO  org.redisson.cluster.ClusterConnectionManager - 2560 slots added to redis://192.168.101.30:6379
2021-10-21 06:39:45.327 [redisson-netty-2-2] INFO  org.redisson.cluster.ClusterConnectionManager - 2560 slots removed from redis://192.168.101.30:6379
2021-10-21 06:39:45.328 [redisson-netty-2-2] INFO  org.redisson.cluster.ClusterConnectionManager - 2709 slots added to redis://192.168.101.32:6379
2021-10-21 06:39:45.335 [redisson-netty-2-2] INFO  org.redisson.cluster.ClusterConnectionManager - 2645 slots removed from redis://192.168.101.32:6379
2021-10-21 06:39:45.336 [redisson-netty-2-2] INFO  org.redisson.cluster.ClusterConnectionManager - 2688 slots added to redis://192.168.101.31:6379
2021-10-21 06:39:45.336 [redisson-netty-2-2] INFO  org.redisson.cluster.ClusterConnectionManager - 2688 slots removed from redis://192.168.101.31:6379
2021-10-21 06:39:45.351 [redisson-netty-2-2] INFO  org.redisson.cluster.ClusterConnectionManager - 7893 slots found to add
2021-10-21 06:39:50.357 [redisson-netty-2-2] DEBUG org.redisson.cluster.ClusterConnectionManager - cluster nodes state got from 192.168.101.30/192.168.101.30:6379:
229cba3ccc4ef32257638e506a4f0734d3572741 192.168.101.32:6380@16380 slave 3345f93588019048d901f0aa405d5cad4a8b71c2 0 1634769614515 3 connected
3bb628f2a70fd72b7682375260c202ff57fe9ced 192.168.101.32:6379@16379 master - 0 1634769614014 5 connected 10923-16383
2dd60672e8ffac23935da781e7002ba54d08a374 192.168.101.31:6380@16380 slave c4171c39d5f799748b355c9b57e427ce004408a8 0 1634769613511 1 connected
bd73b7da0bbb5ae7295adae3e7e6a9fe22f5439f 192.168.101.30:6380@16380 slave 3bb628f2a70fd72b7682375260c202ff57fe9ced 0 1634769613010 5 connected
3345f93588019048d901f0aa405d5cad4a8b71c2 192.168.101.31:6379@16379 master - 0 1634769613611 3 connected 5461-10922
c4171c39d5f799748b355c9b57e427ce004408a8 192.168.101.30:6379@16379 myself,master - 0 1634769613000 1 connected 0-5460

2021-10-21 06:39:50.360 [redisson-netty-2-2] INFO  org.redisson.cluster.ClusterConnectionManager - 2560 slots added to redis://192.168.101.30:6379
2021-10-21 06:39:50.361 [redisson-netty-2-2] INFO  org.redisson.cluster.ClusterConnectionManager - 2560 slots removed from redis://192.168.101.30:6379
2021-10-21 06:39:50.361 [redisson-netty-2-2] INFO  org.redisson.cluster.ClusterConnectionManager - 2709 slots added to redis://192.168.101.32:6379
2021-10-21 06:39:50.363 [redisson-netty-2-2] INFO  org.redisson.cluster.ClusterConnectionManager - 2688 slots removed from redis://192.168.101.32:6379
2021-10-21 06:39:50.363 [redisson-netty-2-2] INFO  org.redisson.cluster.ClusterConnectionManager - 2624 slots added to redis://192.168.101.31:6379
2021-10-21 06:39:50.364 [redisson-netty-2-2] INFO  org.redisson.cluster.ClusterConnectionManager - 1344 slots removed from redis://192.168.101.31:6379
2021-10-21 06:39:50.389 [redisson-netty-2-2] INFO  org.redisson.cluster.ClusterConnectionManager - 6592 slots found to add
2021-10-21 06:39:55.393 [redisson-netty-2-5] DEBUG org.redisson.cluster.ClusterConnectionManager - cluster nodes state got from 192.168.101.31/192.168.101.31:6379:
3bb628f2a70fd72b7682375260c202ff57fe9ced 192.168.101.32:6379@16379 master - 0 1634769619875 5 connected 10923-16383
2dd60672e8ffac23935da781e7002ba54d08a374 192.168.101.31:6380@16380 slave c4171c39d5f799748b355c9b57e427ce004408a8 0 1634769619000 1 connected
bd73b7da0bbb5ae7295adae3e7e6a9fe22f5439f 192.168.101.30:6380@16380 slave 3bb628f2a70fd72b7682375260c202ff57fe9ced 0 1634769619574 5 connected
229cba3ccc4ef32257638e506a4f0734d3572741 192.168.101.32:6380@16380 slave 3345f93588019048d901f0aa405d5cad4a8b71c2 0 1634769618000 3 connected
3345f93588019048d901f0aa405d5cad4a8b71c2 192.168.101.31:6379@16379 myself,master - 0 1634769619000 3 connected 5461-10922
c4171c39d5f799748b355c9b57e427ce004408a8 192.168.101.30:6379@16379 master - 0 1634769618871 1 connected 0-5460

**why it happend?**

**Comment by mrniko** [comment] 2021-10-21 06:49
After which moment does it start to happen?

**Comment by allmelgr** [comment] 2021-10-22 02:59
> After which moment does it start to happen?

2021-10-21 06:39:45.326

**Comment by yongjie1992** [comment] 2021-12-21 05:16
I have the same question! Did you fix it?

**Comment by mrniko** [comment] 2021-12-21 06:44
Not yet, unable to reproduce it so far.

**Comment by mrniko** [comment] 2022-02-18 14:02
Fixed in https://github.com/redisson/redisson/issues/4146

**Closed by mrniko** 2022-02-18 14:02 UTC
Labels: question

**Comment by mrniko** [comment] 2024-04-18 12:13
Another fix made in https://github.com/redisson/redisson/issues/5752
