### ISSUE TITLE
Search domain query failed.

### ISSUE THREAD

**Issue by mrtinkz** [redisson/redisson#1944] opened 2019-02-28 15:14 UTC
### Expected behavior
The DNS resolver should find valid DNS records, I am trying to connect to the redis hosted on azure. I looked at the existing similar issues but looks like this issue still exists.

### Actual behavior

```
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'redis-c.redis.c.windows.net' failed to resolve 'redis-c.redis.c.windows.net.some.com' after 12 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:877) ~[netty-resolver-dns-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:838) ~[netty-resolver-dns-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333) ~[netty-resolver-dns-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:520) ~[netty-resolver-dns-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:63) ~[netty-resolver-dns-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:377) ~[netty-resolver-dns-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:196) ~[netty-resolver-dns-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:188) ~[netty-resolver-dns-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1149) ~[netty-resolver-dns-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[netty-codec-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```
### Redisson version
3.10.3 and netty 4.1.33
### Redisson configuration
Spring Boot Redisson example

**Comment by mrniko** [comment] 2019-02-28 15:21
Could you try to set follow implementation as value of `Config.addressResolverGroupFactory` setting:

```java
import io.netty.channel.socket.DatagramChannel;
import io.netty.channel.socket.nio.NioDatagramChannel;
import io.netty.resolver.ResolvedAddressTypes;
import io.netty.resolver.dns.DnsAddressResolverGroup;
import io.netty.resolver.dns.DnsNameResolverBuilder;
import io.netty.resolver.dns.DnsServerAddressStreamProvider;
import io.netty.resolver.dns.DnsServerAddressStreamProviders;

public class DnsAddressResolverGroupFactory implements AddressResolverGroupFactory {
    
    @Override
    public DnsAddressResolverGroup create(Class<? extends DatagramChannel> channelType,
            DnsServerAddressStreamProvider nameServerProvider) {
        DnsAddressResolverGroup group = new DnsAddressResolverGroup(new DnsNameResolverBuilder()
                .channelType(NioDatagramChannel.class)
                .nameServerProvider(DnsServerAddressStreamProviders.platformDefault())
                .resolvedAddressTypes(ResolvedAddressTypes.IPV4_ONLY));
        return group;
    }

}
```

**Comment by mrtinkz** [comment] 2019-02-28 18:13
my apologies, I should add this in my spring boot application?

**Comment by mrniko** [comment] 2019-03-01 06:29
Yes

**Comment by julialiu15** [comment] 2019-03-01 18:30
Also seeing this issue, it happens sparsely without (once a month) a reliable way to reproduce. I've seen related issues are closed and fix was already in place at version 3.8.2, but still happens with on 3.10.1.

```stack_trace: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'cache-production-b.stq2en.0001.use1.cache.amazonaws.com' failed to resolve 'cache-production-b.stq2en.0001.use1.cache.amazonaws.com' after 2 queries 
    at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:845)
    at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:806)
    at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333)
    at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:322)
    at io.netty.resolver.dns.DnsResolveContext.access$500(DnsResolveContext.java:62)
    at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:379)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
    at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:216)
    at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:43)
    at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:166)
    at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.88.0.2:53] query timed out after 5000 milliseconds (no stack trace available)

thread_name: redisson-netty-1-12
type: service
```

Redisson version (netty default version):
3.10.1

**Comment by julialiu15** [comment] 2019-03-01 18:35
> Could you try to set follow implementation as value of `Config.addressResolverGroupFactory` setting:


After adding the implementation, Is this the right way to set the value for `
Config.addressResolverGroupFactory`? Thank you.

```
Config config = new Config();
config.setAddressResolverGroupFactory(new DnsAddressResolverGroupFactory());
RedissonClient client = Redisson.create(config);
```

**Comment by mrniko** [comment] 2019-03-02 06:30
@julialiu15 

Yes, make sure `DnsAddressResolverGroupFactory` import points to your package and not redisson.

**Comment by mrtinkz** [comment] 2019-03-06 19:20
Made the above change an now I see a different issue, just so I am trying to connect to the redis hosted on azure.

`redis.cache.windows.net:6380,password=xxxxxxxxxxxxxxxxxxVjM=,ssl=True,abortConnect=False`

`
Caused by: java.lang.IllegalArgumentException: server(s) address(es) not defined!
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:242) ~[redisson-3.10.3.jar:na]
	at org.redisson.Redisson.<init>(Redisson.java:120) ~[redisson-3.10.3.jar:na]
	at org.redisson.Redisson.create(Redisson.java:163) ~[redisson-3.10.3.jar:na]
	at com.ford.au.feed.consumer.config.RedissonConfig.redisson(RedissonConfig.java:16) ~[classes/:na]
	at com.ford.au.feed.consumer.config.RedissonConfig$$EnhancerBySpringCGLIB$$4c1fc051.CGLIB$redisson$0(<generated>) ~[classes/:na]
	at com.ford.au.feed.consumer.config.RedissonConfig$$EnhancerBySpringCGLIB$$4c1fc051$$FastClassBySpringCGLIB$$fa15ea3d.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at com.ford.au.feed.consumer.config.RedissonConfig$$EnhancerBySpringCGLIB$$4c1fc051.redisson(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 160 common frames omitted
`

**Comment by mrniko** [comment] 2019-03-07 06:03
Could you share your Redisson configuration?

**Comment by mrtinkz** [comment] 2019-03-07 18:35
It's unable to resolve the domain because I am behind the proxy, everything working fine if I am outside the proxy network. Any workarounds to run behind the proxy?

**Comment by mrniko** [comment] 2019-03-08 05:17
@mrtinkz 

I think this could be solved by network setting.

**Comment by cnsnaveen** [comment] 2020-07-21 10:42
> Could you try to set follow implementation as value of `Config.addressResolverGroupFactory` setting:
> 
> ```java
> import io.netty.channel.socket.DatagramChannel;
> import io.netty.channel.socket.nio.NioDatagramChannel;
> import io.netty.resolver.ResolvedAddressTypes;
> import io.netty.resolver.dns.DnsAddressResolverGroup;
> import io.netty.resolver.dns.DnsNameResolverBuilder;
> import io.netty.resolver.dns.DnsServerAddressStreamProvider;
> import io.netty.resolver.dns.DnsServerAddressStreamProviders;
> 
> public class DnsAddressResolverGroupFactory implements AddressResolverGroupFactory {
>     
>     @Override
>     public DnsAddressResolverGroup create(Class<? extends DatagramChannel> channelType,
>             DnsServerAddressStreamProvider nameServerProvider) {
>         DnsAddressResolverGroup group = new DnsAddressResolverGroup(new DnsNameResolverBuilder()
>                 .channelType(NioDatagramChannel.class)
>                 .nameServerProvider(DnsServerAddressStreamProviders.platformDefault())
>                 .resolvedAddressTypes(ResolvedAddressTypes.IPV4_ONLY));
>         return group;
>     }
> 
> }
> ```

@mrniko 
after adding this it worked.

can you please explain how by setting above config it solved the issue?

**Comment by mrniko** [comment] 2020-07-21 11:13
@cnsnaveen

This issue was resolved in netty project. Use latest netty

**Comment by avcad** [comment] 2021-01-08 02:35
I am running Redisson 3.14.0 in Kubernetes (Redis also in same Kubernetes cluster) and I am seeing the issue,
so I changed to a fully qualified domain and seems to have helped. 
address: "redis://redis-master.redis.svc.cluster.local.:6379"

**Comment by Hollerweger** [comment] 2021-01-18 09:59
We also still see the issues that cname domain can't be resolved at random intervals (~once in some days):
```
Unable to resolve redis.test.internal

Stacktrace: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'redis.test.internal' failed to resolve 'redis.test.internal'
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1013) [netty-resolver-dns-4.1.55.Final.jar!/:4.1.55.Final]
```
@mrniko Can you tell the Netty version that should fix the issue?

**Comment by mrniko** [comment] 2021-01-18 10:20
@Hollerweger 

Did you try this solution https://github.com/redisson/redisson/issues/1944#issuecomment-468312630 ?

**Comment by 13872095752** [comment] 2021-01-20 09:11
I understand what you mean is that the latest version of redisson relies on netty, have solved this problem. If the previous version of redisson needs to change the configuration of **AddressResolverGroupFactory**, right?@mrniko

**Comment by mrniko** [comment] 2021-01-20 11:59
@13872095752

yes, the problem solve in netty. But if it doesn't work anyway, you could try solution suggested in https://github.com/redisson/redisson/issues/1944#issuecomment-468312630

**Comment by 13872095752** [comment] 2021-01-20 12:07
@mrniko Thanks，my redisson version is 3.12.0，but the problem still appear，now I'm trying this configuration to see if it will happen occasionally

**Comment by avcad** [comment] 2021-01-20 16:14
@13872095752 are you using a fully qualified domain (that ends with ".") ?  That seems to be working for me but I am still monitoring. This probably a better workaround and it should perform better.

I thought implementing a new AddressResolverGroupFactory, was a workaround., not a fix. I understand it just disables ipv6?
I was reading the report in the Jetty website a while ago and I am not clear why disabling ipv6 is needed. 
Also, is the change to AddressResolverGroupFactory equivalent to setting java.net.preferIPv4Stack=true?  I remember reading somebody used preferIPv4Stack but it wasn't helping. I'd need to find that post again

From DnsNameResolver, I see NetUtil.isIpV4StackPreferred()  that reads java.net.preferIPv6Addresses can also be used to 
set IPV4_ONLY
        if (NetUtil.isIpV4StackPreferred() || !anyInterfaceSupportsIpV6()) {
            DEFAULT_RESOLVE_ADDRESS_TYPES = ResolvedAddressTypes.IPV4_ONLY;
            LOCALHOST_ADDRESS = NetUtil.LOCALHOST4;
        } else ...

**Comment by 13872095752** [comment] 2021-01-21 02:26
@avcad I understand that this problem should be a bug in the operating system level or netty. The settings you mentioned may be the same thing as this, but there may be differences in implementation, leading to different results. Now I am trying the author's method, and I think it can solve this problem

**Comment by syncAsync863** [comment] 2021-04-20 06:43
I am using latest netty version which is 4.1.60.Final and also used this custom DnsAddressResolverGroupFactory but I am still facing thsi issue. I have implemented redisson on a saprk job.

**Comment by code-and-such** [comment] 2021-08-19 12:32
@avcad I wonder what the result of your monitoring was? Did the trailing dot solve the problem (completely)?

**Comment by freshgeek** [comment] 2021-09-29 06:13
> > Could you try to set follow implementation as value of `Config.addressResolverGroupFactory` setting:
> 
> After adding the implementation, Is this the right way to set the value for ` Config.addressResolverGroupFactory`? Thank you.
> 
> ```
> Config config = new Config();
> config.setAddressResolverGroupFactory(new DnsAddressResolverGroupFactory());
> RedissonClient client = Redisson.create(config);
> ```



> @mrtinkz
> 
> I think this could be solved by network setting.
Excuse me, How to solve it if you use redisson-spring-boot-starter ？

**Comment by mrniko** [comment] 2022-10-12 10:10
Fixed in https://github.com/redisson/redisson/issues/1625

**Closed by mrniko** 2022-10-12 10:10 UTC
Labels: dns
