### ISSUE TITLE
org.redisson.client.WriteRedisConnectionException 

### ISSUE THREAD

**Issue by kamalbctg** [redisson/redisson#3545] opened 2021-04-11 14:44 UTC
Some time getting following exception in unit tests but not always 
```
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! 
Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null],
 connection: RedisConnection@1405217801 [redisClient=[addr=redis://localhost:6333], 
channel=[id: 0xec022dc7, L:0.0.0.0/0.0.0.0:38200], currentCommand=null], command: (EVAL), 
params: [local v = redis.call('hget', KEYS[1], ARGV[1]); 
redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1,  
RequestCache, PooledUnsafeDirectByteBuf(ridx: 0, widx: 42, cap: 256), 
PooledUnsafeDirectByteBuf(ridx: 0, widx: 103, cap: 256)] after 3 retry attempts
Caused by: io.netty.channel.StacklessClosedChannelException
```

**Comment by mrniko** [comment] 2021-04-12 12:54
you need to check your instance since it closes channels.

**Comment by kamalbctg** [comment] 2021-04-12 13:53
@mrniko  thank for reply. I have 14 tests some time(1 out of 100 run) one of them failed. i am starting embedded-redis with @BeforeClass also check with external redis never seen instance is down as i can perform redis operation using redis-client. By the way my implementation have Rlock.

**Comment by packley1** [comment] 2021-07-26 22:09
> you need to check your instance since it closes channels.

What do you mean by this?  Are you saying that the Redis Server is closing the connection?

**Comment by mrniko** [comment] 2021-07-27 04:28
@packley1 

I mean to check network

**Comment by packley1** [comment] 2021-07-27 13:20
> @packley1
> 
> I mean to check network

So we are seeing this same error, but only under very specific conditions.  Generally everything works well, we load tested and did not see this error.  However, when we attempt to retrieve a large object from the cache, it is fine.  However, if multiple threads retrieve the same large object from the cache at about the same time, we start seeing this error.  When we fetch the item from the cache, we do update the expiry time from each thread - could this be an issue (updating the same cached object from multiple threads)?

**Comment by mrniko** [comment] 2021-07-27 13:26
can you suggest test case to reproduce it?

**Comment by mrniko** [comment] 2021-07-27 13:54
@packley1 

You need to increase nettyThreads amount. Decoding 18Mb of data may make netty thread busy and block queued connection operations.

**Comment by packley1** [comment] 2021-07-28 04:48
> @packley1
> 
> You need to increase nettyThreads amount. Decoding 18Mb of data may make netty thread busy and block queued connection operations.

I did try this, set it to 128.... No changes.

My solution/work around is to make sure the same key is not requested simultaneously.  So far this is promising.

I will put together the sequence which causes this issue, in the next day or so.

**Closed** 2021-09-06 10:49 UTC
Labels: question

**Comment by XQDD** [comment] 2021-09-07 08:46
> > @packley1
> > You need to increase nettyThreads amount. Decoding 18Mb of data may make netty thread busy and block queued connection operations.
> 
> I did try this, set it to 128.... No changes.
> 
> My solution/work around is to make sure the same key is not requested simultaneously. So far this is promising.
> 
> I will put together the sequence which causes this issue, in the next day or so.

@packley1  any update?

**Comment by packley1** [comment] 2021-09-07 12:51
In a nut shell this problem occurs when we make simultaneous requests to REDIS for cached data which is large (in our case the cached data was 18Mb).

**Comment by mrniko** [comment] 2021-09-14 06:20
@packley1 

Did you try to increase connections amount?

**Comment by mrniko** [comment] 2021-09-17 08:23
I have checked. Increased size of connection pool solves the issue.
