### ISSUE TITLE
RScoredSortedSet.valueRangeReversed()  -inf +inf or +inf -inf bounds

### ISSUE THREAD

**Issue by AntonShiryaev** [redisson/redisson#5777] opened 2024-04-13 14:35 UTC
Redisson methods: RScoredSortedSet.valueRange() and RScoredSortedSet.valueRangeReversed().

I have noticed that the official Redis command syntax requires setting -/+inf bounds.
> ZRANGEBYSCORE key min max [WITHSCORES] [LIMIT offset count] 
> // redis> ZRANGEBYSCORE myzset -inf +inf

> ZREVRANGEBYSCORE key max min [WITHSCORES] [LIMIT offset count] 
> // redis> ZREVRANGEBYSCORE myzset +inf -inf

However, in method (valueRangeReversed), realization with -/+inf does not comply. And valueRangeReversed will work only with -inf +inf, but should work only with +inf -inf.

With valueRangeReversed(Double.POSITIVE_INFINITY, true, Double.NEGATIVE_INFINITY, true,0,1) throw an exception:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:687)
	...

valueRange(Double.NEGATIVE_INFINITY, true, Double.POSITIVE_INFINITY, true, 0, 1)  // work
valueRangeReversed(Double.POSITIVE_INFINITY, true, Double.NEGATIVE_INFINITY, true,0,1) // not work
valueRangeReversed(Double.NEGATIVE_INFINITY, true, Double.POSITIVE_INFINITY, true, 0, 1) // work

In terminal:
```
127.0.0.1:6379> ZRANGEBYSCORE test +inf -inf WITHSCORES LIMIT 0 1
(empty array)
127.0.0.1:6379> ZRANGEBYSCORE test -inf +inf WITHSCORES LIMIT 0 1
 1) "5"
 2) "1713014496"
```

```
127.0.0.1:6379> ZREVRANGEBYSCORE test -inf +inf WITHSCORES LIMIT 0 1
(empty array)
127.0.0.1:6379> ZREVRANGEBYSCORE test +inf -inf WITHSCORES LIMIT 0 1
 1) "4"
 2) "1713014515"
```

Is that a bug?
[RedisCommands](https://redis.io/docs/latest/commands/zrevrangebyscore/)

**Comment by mrniko** [comment] 2024-04-16 05:41
Unable to reproduce with the code below.

```java
        RScoredSortedSet<Integer> set = redisson.getScoredSortedSet("simple");
        set.add(1, 1);
        set.add(2, 2);
        set.valueRangeReversed(Double.POSITIVE_INFINITY, true, Double.NEGATIVE_INFINITY, true, 0, 1);
```

**Comment by AntonShiryaev** [comment] 2024-04-16 14:43
I'm sorry. Let me provide my code example based on yours:

```
package abcd;
import org.redisson.Redisson;
import org.redisson.api.RScoredSortedSet;
import org.redisson.api.RedissonClient;
import org.redisson.client.RedisConnectionException;
import org.redisson.config.Config;
import static java.lang.System.out;
public class Test2 {
    public static void main(String[] args) {
        RedissonClient redisson;
        RScoredSortedSet<Integer> users;
        Config config = new Config();
        config.useSingleServer().setAddress("redis://127.0.0.1:6379");

        try {
            redisson = Redisson.create(config);
            users = redisson.getScoredSortedSet("simple");
            users.delete();

            users.add(1,1);
            users.add(2,2);

            Integer maxUserId = users.valueRangeReversed(Double.NEGATIVE_INFINITY, true, Double.POSITIVE_INFINITY, true, 0, 1).stream().toList().get(0);
            out.println("maxUserId = " + maxUserId);
            out.println("*******");
            Integer maxUserIdError = users.valueRangeReversed(Double.POSITIVE_INFINITY, true, Double.NEGATIVE_INFINITY, true, 0, 1).stream().toList().get(0);
            out.println("maxUserIdError = " + maxUserIdError);

        } catch (
                RedisConnectionException Exc) {
            out.println("No connection to Redis");
            out.println(Exc.getMessage());
        }
    }
}
```


Console output is:

> maxUserId = 2
> uuuuuuuuuuuuuuuuuu
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
> 	at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:687)
> 	at abcd.Test2.main(Test2.java:29)

And my pom.xml file is:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>testcase</groupId>
    <artifactId>testcase</artifactId>
    <version>1.0-SNAPSHOT</version>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.28.0</version>
        </dependency>
    </dependencies>

</project>

```

In the code above: 
Integer maxUserId should not work, 
Integer maxUserIdError should work, but it's not. 
I needed to fetch the member with the maximum score. If I used something wrong, let me know, please.

**Comment by mrniko** [comment] 2024-04-17 06:25
Thanks for the example. ZREVRANGEBYSCORE command has a different order of min max parameters. This is why you get empty result for `valueRangeReversed(Double.POSITIVE_INFINITY, true, Double.NEGATIVE_INFINITY, true, 0, 1)` method

**Comment by AntonShiryaev** [comment] 2024-04-17 15:09
Ok. I thought syntax valueRangeReversed() is equal to redis command syntax, where max is startScore, min is endScore:

> ZREVRANGEBYSCORE key max min [WITHSCORES] [LIMIT offset count]

[ZREVRANGEBYSCORE](https://redis.io/docs/latest/commands/zrevrangebyscore/)

> `valueRangeReversed(Double.NEGATIVE_INFINITY, true, Double.POSITIVE_INFINITY, true, 0, 1)` result is correct. startScore = Min = Double.NEGATIVE_INFINITY and endScore = Max = Double.POSITIVE_INFINITY

But as you say for valueRangeReversed() Min is startScore, Max is endScore is correct - Ok. Needs to remember it. Thank you.

**Comment by mrniko** [comment] 2024-04-17 15:19
> But as you say for valueRangeReversed() Min is startScore, Max is endScore is correct - Ok. Needs to remember it. Thank you.

Yeah, as it stated in javadocs of the method. I'm closing the issue

**Closed by mrniko** 2024-04-17 15:19 UTC
