### ISSUE TITLE
Connection storm on Azure RedisCluster

### ISSUE THREAD

**Issue by go0t** [redisson/redisson#4494] opened 2022-08-18 05:34 UTC
**Expected behavior**
Stable connection between redisson client and RedisCluster

**Actual behavior**
The client reacted by sending 40k+ connection requests per second, causing more CPU load and pushing the shard into cascade failure. 
![image](https://user-images.githubusercontent.com/111473273/185285145-5ffa6256-3144-4643-a67e-bdbd0497f851.png)
![image](https://user-images.githubusercontent.com/111473273/185285358-3b38987b-d51f-4f97-95fb-521840c5edc5.png)
![image](https://user-images.githubusercontent.com/111473273/185297528-e5190737-a83e-4b28-9624-3c2af1a48d3f.png)
![image](https://user-images.githubusercontent.com/111473273/185297566-9d7d6573-835b-42ef-95a7-2218de6fbeee.png)

**Steps to reproduce or test case**
We have 40+ services running on 800+ pods, connect to a Azure RedisCluster within 3 shards by Redisson-3.17.0 at the first time. After a server maintained event (shard2 primary and slave node status changed), the connections to shard2 quickly increased and shard2 CPU overload 100%, services failed to get response from server.

After the incident, we reproduced it by force restart primary node in a shard. it's a connection bug in Redisson-3.17.0 triggered by server maintained event and fixed in Redisson-3.17.2.

The latest version we integrated in services in Redisson-3.17.3, and we updated client configuration suggested by Azure Redis team as below. However similar issue occurred in production environment. This time we cannot reproduce it in testing environment by restart primary or slave node in a shard.

Here's some analysis comment from Azure Redis team:
Aside from being pushed into overload, the cache is healthy and operating as expected. Server logs show no unusual errors. Logs do show that replication of data from the Primary to Replica node in shard 2 did deteriorate, which is normal in situations with CPU exhaustion or network saturation. 
The fact that we’ve seen similar issues with two different caches in different months indicates an issue with the client rather than the server. Specifically, the low-level problems with connections that only occur on clustered caches points to an issue with the Redisson client library rather than the application itself. This could be a problem with Redisson configuration (unlikely, after rigorous review by the application team), or a bug with Redisson itself. Several other Azure customers have reported issues with Redisson in similar scenarios involving clustered caches and connection instability. At least one customer was able to resolve the issue by upgrading to a newer version, but the frequency of issues with the library does not inspire confidence.  

**Redis version**
4.0.14

**Redisson version**
3.17.3

**Redisson configuration**
clusterServersConfig:
  masterConnectionPoolSize: 24
  masterConnectionMinimumIdleSize: 8
  slaveConnectionPoolSize: 24
  slaveConnectionMinimumIdleSize: 8
  subscriptionConnectionPoolSize: 8
  subscriptionConnectionMinimumIdleSize: 1
  connectTimeout: 5000
  scanInterval: 30000
  timeout: 5000
  readMode: MASTER_SLAVE

**Comment by mrniko** [comment] 2022-08-18 08:45
Can you share Redisson logs with `debug` tracing logging level? It's similar to a network issue

**Comment by mrniko** [comment] 2022-08-18 08:47
Can it be related to this https://github.com/redisson/redisson/issues/3934 ?

**Comment by JasonHelloWorld** [comment] 2022-08-18 09:39
> Can it be related to #3934 ?

#3934 related to ServiceExecutor, I've checked code there's no ServiceExecutor related coding.

**Comment by JasonHelloWorld** [comment] 2022-08-18 12:33
> Can you share Redisson logs with `debug` tracing logging level? It's similar to a network issue
Sorry we dont have debug log in production environment, here's error log before the incident.

Unable to send PING command over channel: [id: 0xacd92b94,L:/10.244.46.232:49494 - R:52.131.44.164/52.131.44.164:15004]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=rediss://52.131.44.164:15004]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:245)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

Unable to unfreeze entry: [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:83:queue:0, freeConnectionsAmount=26, freeConnectionsCounter=value:374:queue:0, freezeReason=MANAGER, client=[addr=rediss://52.131.44.164:15004], nodeType=SLAVE, firstFail=1658883897932]
java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 52.131.44.164/52.131.44.164:15004
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1423)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:154)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:310)
	at org.redisson.connection.pool.ConnectionPool.lambda$createConnection$3(ConnectionPool.java:276)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.redisson.client.RedisClient$1$1.run(RedisClient.java:226)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 52.131.44.164/52.131.44.164:15004
	at org.redisson.connection.pool.ConnectionPool$1.lambda$run$0(ConnectionPool.java:153)
	... 18 common frames omitted
Caused by: java.util.concurrent.CompletionException: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=rediss://52.131.44.164:15004]
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
	... 10 common frames omitted
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=rediss://52.131.44.164:15004]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:245)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)

There're 87k same error logs as the above in the first 15 mins.
![image](https://user-images.githubusercontent.com/111473273/185394393-b5519c04-5b02-47a9-af97-1649659b81eb.png)

Below is RedisCluster server side log:
PreciseTimeStamp	RoleInstance	Message
1:05:22	5	[01:05:22.4289155] [2588] 27 Jul 01:05:22.432 * Unable to partial resync with slave 172.16.0.8:10226 for lack of backlog (Slave request was: 1360508225, repl_backlog: Not Null, repl_backlog_off: 3602368854, repl_backlog_histlen: 200000000).
1:05:22	4	[01:05:22.4200047] [6064] 27 Jul 01:05:22.429 * Trying a partial resynchronization (request 6e9894133db71f45fce1dde9e399a90433b9d6b4:1360508225).
1:05:23	5	[01:05:23.9758454] [2588] 27 Jul 01:05:23.976 # Sent FULLRESYNC to slave
1:06:14	4	[01:06:14.3425220] [2252] 27 Jul 01:06:14.344 * Trying a partial resynchronization (request ebf51d68f0231616843f2512b77e03ff7e52b347:1).
1:06:14	5	[01:06:14.3327278] [2588] 27 Jul 01:06:14.345 * Partial resynchronization not accepted: Replication ID mismatch (Slave asked for 'ebf51d68f0231616843f2512b77e03ff7e52b347', my replication IDs are '6e9894133db71f45fce1dde9e399a90433b9d6b4' and '0000000000000000000000000000000000000000')
1:06:15	5	[01:06:15.3483411] [2588] 27 Jul 01:06:15.350 # Sent FULLRESYNC to slave
1:06:24	4	[01:06:24.1238947] [2252] 27 Jul 01:06:24.136 * Full resync from master: 6e9894133db71f45fce1dde9e399a90433b9d6b4:4334748338
1:11:03	4	[01:11:03.9400804] [2252] 27 Jul 01:11:03.941 * Trying a partial resynchronization (request 6e9894133db71f45fce1dde9e399a90433b9d6b4:4378350823).
1:11:03	5	[01:11:03.9378576] [2588] 27 Jul 01:11:03.941 * Unable to partial resync with slave 172.16.0.8:10226 for lack of backlog (Slave request was: 4378350823, repl_backlog: Not Null, repl_backlog_off: 6576868770, repl_backlog_histlen: 200000000).
1:11:04	5	[01:11:04.4534579] [2588] 27 Jul 01:11:04.464 # Sent FULLRESYNC to slave
1:11:23	5	[01:11:23.6062499] [2588] 27 Jul 01:11:23.609 * Partial resynchronization not accepted: Replication ID mismatch (Slave asked for 'c991c52a7d51f36003ea83916d31803e66fdab21', my replication IDs are '6e9894133db71f45fce1dde9e399a90433b9d6b4' and '0000000000000000000000000000000000000000')
1:11:23	4	[01:11:23.5965229] [5648] 27 Jul 01:11:23.609 * Trying a partial resynchronization (request c991c52a7d51f36003ea83916d31803e66fdab21:1).
1:11:24	5	[01:11:24.1218121] [2588] 27 Jul 01:11:24.131 # Sent FULLRESYNC to slave
1:11:26	4	[01:11:26.0340454] [5648] 27 Jul 01:11:26.043 * Full resync from master: 6e9894133db71f45fce1dde9e399a90433b9d6b4:7000028381
1:16:16	5	[01:16:16.9531879] [2588] 27 Jul 01:16:16.959 * Unable to partial resync with slave 172.16.0.8:10226 for lack of backlog (Slave request was: 7031779983, repl_backlog: Not Null, repl_backlog_off: 9293701129, repl_backlog_histlen: 200000000).
1:16:16	4	[01:16:16.9448000] [5648] 27 Jul 01:16:16.959 * Trying a partial resynchronization (request 6e9894133db71f45fce1dde9e399a90433b9d6b4:7031779983).
1:16:17	5	[01:16:17.1407042] [2588] 27 Jul 01:16:17.156 # Sent FULLRESYNC to slave
1:19:23	4	[01:19:23.5401599] [6020] 27 Jul 01:19:23.541 * Trying a partial resynchronization (request dd72d3b3ba8a8eba425a624c96b9848ac9ad7604:1).
1:19:23	5	[01:19:23.5449290] [2588] 27 Jul 01:19:23.542 * Partial resynchronization not accepted: Replication ID mismatch (Slave asked for 'dd72d3b3ba8a8eba425a624c96b9848ac9ad7604', my replication IDs are '6e9894133db71f45fce1dde9e399a90433b9d6b4' and '0000000000000000000000000000000000000000')
1:19:24	5	[01:19:24.4199978] [2588] 27 Jul 01:19:24.417 # Sent FULLRESYNC to slave
1:19:24	4	[01:19:24.4151733] [6020] 27 Jul 01:19:24.429 * Full resync from master: 6e9894133db71f45fce1dde9e399a90433b9d6b4:10978235594

**Comment by mrniko** [comment] 2022-08-18 13:49
Did you try to increase nettyThreads setting?

**Comment by JasonHelloWorld** [comment] 2022-08-18 15:14
> Did you try to increase nettyThreads setting?
No, we didn't. Is this related to the issue?

**Comment by mrniko** [comment] 2022-08-18 15:58
busy netty threads may cause these errors.

**Comment by JasonHelloWorld** [comment] 2022-08-19 00:33
Thanks for your quick reply. Is it possible to reproduce the issue by set netty threads in testing environment?

**Comment by JasonHelloWorld** [comment] 2022-08-19 00:43
> busy netty threads may cause these errors.

As the above connection screenshot, I dont understand why busy netty threads quick increased connection size which obviously much more than max pool size limit. 
Pool size in configuration is master 24 + slave 24, even all 800+ pods cannot generated max 80k/s connection storm.

**Comment by mrniko** [comment] 2022-08-23 06:57
Unable to reproduce this issue. It might be environment specific. Can you share full log from application start?

**Comment by go0t** [comment] 2022-08-24 15:18
[log.csv](https://github.com/redisson/redisson/files/9417186/log.csv)
Please find log  of one service with Redisson 3.17.3 in production environment.
We also found a big key issue which might related to the incident. The key value size is about 200k, the service frequently read/write the key before the incident, however it works well in single redis server.

**Comment by mrniko** [comment] 2022-09-30 07:14
Try to set masterConnectionMinimumIdleSize = masterConnectionPoolSize, slaveConnectionPoolSize = slaveConnectionMinimumIdleSize

**Comment by mrniko** [comment] 2022-11-17 08:32
Connection leaks after failover in cluster fixed in https://github.com/redisson/redisson/issues/4637

**Closed by mrniko** 2022-11-17 08:32 UTC
