### ISSUE TITLE
JsonJacksonCodec constructor in 3.6.1 breaks with Jackson 2.9.x

### ISSUE THREAD

**Issue by tkruse** [redisson/redisson#1314] opened 2018-02-21 00:24 UTC
Using Jackson 2.9.2 and 2.9.4 (tried both), trying to upgrade from Redisson 3.3.2 to 3.6.1 I get this:

```
Caused by: java.lang.IllegalStateException: Failed copy(): org.msgpack.jackson.dataformat.MessagePackFactory (version: 2.9.2) does not override copy(); it has to
        at com.fasterxml.jackson.core.JsonFactory._checkInvalidCopy(JsonFactory.java:333)
        at com.fasterxml.jackson.core.JsonFactory.copy(JsonFactory.java:320)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:499)
        at com.fasterxml.jackson.databind.ObjectMapper.copy(ObjectMapper.java:617)
        at org.redisson.codec.JsonJacksonCodec.<init>(JsonJacksonCodec.java:107)
```

Redisson 3.5.7 does not have this issue.

**Comment by mrniko** [comment] 2018-02-21 05:06
Hi!
ObjectMapper wasn't copied during JsonJacksonCodec creation. This issue was fixed in 3.6.0 version.
But it discovered another issue with msgpack. It didn't override copy method - project https://github.com/msgpack/msgpack-java/pull/454

We should wait a next version of msgpack.

**Comment by Marek00Malik** [comment] 2018-03-16 09:25
any news on this ?
I can see this fix is now closed, but there hasn't been any version released since Nov 2017.

**Comment by mrniko** [comment] 2018-03-16 09:27
@Marek00Malik 

I guess you better ask @komamitsu regarding release date.

**Comment by Marek00Malik** [comment] 2018-03-16 09:57
Quick question, is this bug also the cause of throwing:
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of org.hibernate.cache.spi.entry.StandardCacheEntryImpl: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)

**Comment by mrniko** [comment] 2018-03-16 10:17
@Marek00Malik 
It's not a bug, StandardCacheEntryImpl doesn't have default constructor which is requirement for jackson json codec. Try fst codec

**Comment by kringol** [comment] 2018-04-12 06:28
Now failing due a different reason.
Tested with msgpack 0.8.15 and redisson 3.6.5

Fails instantly when trying to instantiate a MsgPackJacksonCodec
`java.lang.NullPointerException
	at org.msgpack.jackson.dataformat.ExtensionTypeCustomDeserializers.<init>(ExtensionTypeCustomDeserializers.java:38)
	at org.msgpack.jackson.dataformat.MessagePackFactory.<init>(MessagePackFactory.java:61)
	at org.msgpack.jackson.dataformat.MessagePackFactory.copy(MessagePackFactory.java:147)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:499)
	at com.fasterxml.jackson.databind.ObjectMapper.copy(ObjectMapper.java:617)
	at org.redisson.codec.JsonJacksonCodec.<init>(JsonJacksonCodec.java:108)
	at org.redisson.codec.MsgPackJacksonCodec.<init>(MsgPackJacksonCodec.java:31)
`

**Comment by kringol** [comment] 2018-04-16 01:58
msgpack-java 0.8.16 is out now to fix the new issue
Confirmed it works fine :)
https://github.com/msgpack/msgpack-java/issues/470

**Closed** 2018-04-16 07:05 UTC
