### ISSUE TITLE
Azure Redis For Cache. Scheduler stops fire timeouts after redis restart

### ISSUE THREAD

**Issue by lasfromhell** [redisson/redisson#3705] opened 2021-07-01 09:50 UTC
We're scheduling multiple tasks and using Redisson as a library for distributed scheduling backed by Azure Redis For Cache (cluster mode)
Everything works fine during few weeks but at some moment it stops call tasks handlers after timeout. We found that it happens in failover cases (when master is terminated and slave promoted to master or when redis fully rebooted) but not each time. It can be reproduced manually when we randomly restart master/slave redis instances or both of them through Azure Portal. After a few restarts (it happens not each time) our application stops execute tasks handlers when it's time to call it. Newly created tasks for the same instance of RScheduledExecutorService are also not working.
If we restart our application when detect this issue, then it handles all scheduled tasks that were not handled after failover and starts working normally.

I tried to debug this issue and see that HashedWheelTimer still executing and pushes request Ids through lua script into list (request queue):
{job-scheduler-executor:org.redisson.executor.RemoteExecutorService}  (backed by redisson blocking queue)
But entries are never extracted from this list after restart (previously it was done by BLPOP command, but after restart I don't see any BLPOP commands related to this queue and from response queue also: {remote_response}:<uuid>). Most probably it just doesn't resend BLPOP command after reconnect to Redis and because of this it doesn't call associated handler. Size of queue just increasing when new tasks scheduled:
![image](https://user-images.githubusercontent.com/31354373/124103031-8f910800-da69-11eb-9d9f-663d68ce1729.png)

And after restart of an application it immediately handle all of them:
![image](https://user-images.githubusercontent.com/31354373/124103154-aafc1300-da69-11eb-97d4-7f6b233c012d.png)

Here is a log file that I've captured (with enabled Redisson debug logs) and there you can see that there are no BLPOP commands anymore after restart. I can reproduce the issue but not sure what exactly I should check. 
Log: 
[js2.log](https://github.com/redisson/redisson/files/6747202/js2.log)

Since request queue is a local variable passed to "subscribe" method of RedsissonRemoteService, I cannot check the state of this queue (may be there is a way to do that but didn't found where it can be stored)
![image](https://user-images.githubusercontent.com/31354373/124103723-3d9cb200-da6a-11eb-8f41-a0c3d33134a3.png)
While debugging after failover, I've tried to call "getBlockingQueue" manually, it returns new instance of blocking queue. Poll/take methods from this newly created queue working fine for this queue after failover. It's possible that re-subcribe didn't happen in some rare situation.

**Expected behavior**
After failover redisson continues fire timouts (calls handlers)

**Actual behavior**
Redisson stops call scheduler tasks handlers. Even newly scheduled tasks are not working

**Redis version**
Azure Redis for Cache (Redis 4.0.14)

**Redisson version**
3.15.4

**Redisson configuration**

clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 15000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: ${REDIS_AZURE_PASSWORD}
  subscriptionsPerConnection: 5
  clientName: null
  pingConnectionInterval: 3000
  tcpNoDelay: true
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "MASTER"
  subscriptionMode: "MASTER"
  nodeAddresses:
    - "rediss://${REDIS_AZURE_HOSTNAME}:6380"
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"

[](url)

**Comment by mrniko** [comment] 2021-07-15 12:43
Thanks for provided logs.

I don't see any failover according to cluster state:

```
DEBUG [2021-06-30T13:25:47.911Z:redisson-netty-2-17][org.redisson.cluster.ClusterConnectionManager][] cluster nodes state got from /10.216.20.4:6380:
2b3fbbb6e55c8e328226cf1c74a1810f0e7fada3 10.216.20.4:15000 myself,master - 0 0 2 connected 0-16383
```
```
DEBUG [2021-06-30T13:30:27.486Z:redisson-netty-2-10][org.redisson.cluster.ClusterConnectionManager][] cluster nodes state got from /10.216.20.4:6380:
921f5ad5daf031835511c9a0863c140ae8ed1fc9 10.216.20.4:15001 slave 9acb8fbd60dc0ddab28e20704936a462284ed2e3 0 1625059826885 1 connected
9acb8fbd60dc0ddab28e20704936a462284ed2e3 10.216.20.4:15000 myself,master - 0 0 0 connected 0-16383
```

Only new slave node was added.

**Comment by lasfromhell** [comment] 2021-07-15 13:07
Not sure exactly what happens on Azure Redis after restart of whole cluster. May be it assigns other slave nodes

**Comment by mrniko** [comment] 2021-07-20 13:29
how do you restart azure redis? by selecting primary and replica nodes and clicking reboot button?

**Comment by lasfromhell** [comment] 2021-07-20 13:58
To reproduce it, yes. It's usually not enough just to do this once. Just randomly restarting master 1/2 or slave 1/2 or reboot all of them. 
Actually, we have this issue in production (without any manual restarts) since in Azure switch between master and slave happens pretty often (may be once a day or even more often. As I understand it's normal, sometimes Azure ops are applying updates this way, sometimes it's kind of preventive work). Once I saw that there was a restart of one pair master+slave (since we have 2 masters and a slave per master). Last time we had an issue with connections for exactly this situation. But I wasn't able to find a pattern. It happens in different situations. But more often with scheduling (may be because there more long running operations like blpop, not sure)

**Comment by mrniko** [comment] 2021-07-20 15:54
Which Cache Type do you use? Basic C0, Standard C1 ...

**Comment by lasfromhell** [comment] 2021-07-20 17:53
It's a premium with 2 shards

**Comment by mrniko** [comment] 2021-07-22 10:14
Unable to reproduce with Azue Premium Redis cache.

Here is the code:
```java
        Config config = new Config();
        config.setCodec(new FstCodec());
        config.setThreads(16);
        config.setNettyThreads(32);
        config.useClusterServers()
                .setIdleConnectionTimeout(10000)
                .setConnectTimeout(15000)
                .setTimeout(3000)
                .setRetryAttempts(3)
                .setRetryInterval(1500)
                .setFailedSlaveCheckInterval(60000)
                .setFailedSlaveReconnectionInterval(3000)
                .setTcpNoDelay(true)
                .setSlaveConnectionMinimumIdleSize(24)
                .setSlaveConnectionPoolSize(64)
                .setMasterConnectionMinimumIdleSize(24)
                .setMasterConnectionPoolSize(64)
                .setSubscriptionMode(SubscriptionMode.MASTER)
                .setReadMode(ReadMode.MASTER)
                .addNodeAddress("redis://.......");
        RedissonClient redisson = Redisson.create(config);
        redisson.getKeys().flushall();

        RScheduledExecutorService ee = redisson.getExecutorService("test");
        ee.registerWorkers(WorkerOptions.defaults().workers(1));

        Thread t = new Thread(() -> {
            RScheduledExecutorService e = redisson.getExecutorService("test");
            for (int i = 0; i < 1000; i++) {
                try {
                    e.submit(new TestTask("" + i));
                    Thread.sleep(1000);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
        t.start();
        t.join();


        redisson.shutdown();
```

Can you try this snippet with latest Redisson version?

**Comment by mrniko** [comment] 2021-07-23 09:16
Can try to reproduce the issue using attached version?

[redisson-all-3.16.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/6867683/redisson-all-3.16.1-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment] 2021-08-03 06:42
I'm closing this. Let me know if you reproduce it with 3.16.1+ version.

**Closed by mrniko** 2021-08-03 06:42 UTC
Labels: failover

**Comment by lasfromhell** [comment] 2021-08-03 06:56
Tried to reproduce on 3.16.1 but wasn't able anymore. Looks like that it's working
