### ISSUE TITLE
RedissonBaseLock can't be unlocked if exception got thrown from the same thread

### ISSUE THREAD

**Issue by up-to-you** [redisson/redisson#3420] opened 2021-02-17 15:21 UTC
RedissonBaseLock.java:312

opStatus is always null:
RedissonPromise.java:183  (status of netty's Future is canceled due to Exception thrown from the same thread)

I'm experience it permanently.
At a first glance (if i'm not mistaken) this is a Blocker  level issue.

RedissonPromise.java:187:
Same behavior if Exception got thrown too early, such that f.getNow() results null

**Comment by up-to-you** [comment] 2021-02-17 15:22
Are there some workarounds like disabling spin-loop feature ?

**Comment by mrniko** [comment] 2021-02-17 16:17
Unable to reproduce it. Please provide test code.

**Comment by up-to-you** [comment] 2021-02-17 16:36
Yep, sry, i was wrong. Got confused because of some proxy / aop debugging issues. The exception RedissonBaseLock:312 is thrown if lock object already evicted by TTL (leaseTime). Still a bit confusing message about Thread owning, albeit the lock actually evicted.

**Comment by mrniko** [comment] 2021-02-18 06:09
OK, I'm closing this.

**Closed by mrniko** 2021-02-18 06:09 UTC
