### ISSUE TITLE
PING Command execution timeout for command

### ISSUE THREAD

**Issue by Venkat-C-J** [redisson/redisson#5624] opened 2024-02-12 10:31 UTC
We are facing below exception 
`org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=xxxx://xxxx]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:261)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750) `

We came across this GitHub link https://github.com/redisson/redisson/issues/4451 where a similar exception was reported. This issue was addressed in Redisson version 3.17.6.

Issue: https://github.com/redisson/redisson/issues/4441 
PR: https://github.com/redisson/redisson/commit/b320f191c6a03c3d19c3c648a85d83d7280747ac

We are currently in 3.20.1 but still facing the same issue.

**Comment by mrniko** [comment] 2024-02-12 10:57
Fixed in https://github.com/redisson/redisson/issues/5493
Try 3.26.1 version

**Comment by Venkat-C-J** [comment] 2024-02-12 11:25
> Fixed in #5493 Try 3.26.1 version

@mrniko your swift response is greatly appreciated. We will be testing with the latest version, 3.26.1. Thank you!

**Comment by Venkat-C-J** [comment] 2024-02-12 14:48
@mrniko While this issue has been reported across various Redisson versions, it specifically emerges in a particular environment despite multiple deployments using the same Redisson version (3.20.1). Our aim is to comprehend the specific scenarios leading to this problem. By doing so, we can proactively prevent or take necessary actions to mitigate the occurrence of this issue in other environments.

Issue reported in 3.17.6 version : https://github.com/redisson/redisson/issues/4441
PR : https://github.com/redisson/redisson/commit/b320f191c6a03c3d19c3c648a85d83d7280747ac

Issue reported in 3.23.4 version : https://github.com/redisson/redisson/issues/5371
PR : https://github.com/redisson/redisson/commit/605665665e0a6e85d76b844b7ea316554661969a

Issue reported in 3.25.0 version : https://github.com/redisson/redisson/issues/5493
PR : https://github.com/redisson/redisson/commit/e7bdea6cd476f3adb2f75db07136690c72fb93a3

Thanks

**Comment by mrniko** [comment] 2024-02-13 05:42
@Venkat-C-J 

I suggest you to check the network of this environment.

**Comment by ShriramDeshkar** [comment] 2024-02-27 05:02
Same error in latest 3.27.0 version 

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=rediss://<redishostname>:6380]
	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:253)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by mrniko** [comment] 2024-02-27 11:07
@ShriramDeshkar 

Did you try to increase ping timeout interval?

**Comment by ShriramDeshkar** [comment] 2024-02-27 11:20
I have not set any timeout interval explicitly ...I m using org.redisson.config.Config to set configuration of RedissonClient object .....what is your recommendation ? What value shall we use while setting timeout interval ? and which method to use setTimeout() or setConnectTimeout() ?

**Comment by ShriramDeshkar** [comment] 2024-03-05 07:08
@mrniko any update on this issue ?

**Comment by pious68** [comment] 2024-03-07 15:08
> @mrniko any update on this issue ?

my redis version is 7.2.4，redissson version is 3.27.1，without any questions，i think it is redisson version and redis version don‘t match

**Comment by mrniko** [comment] 2024-03-08 11:19
@ShriramDeshkar 

Sorry, unable to reproduce it.

@pious68 

What do you mean PING command is compatible with any version of Redisson and Redis

**Comment by mrniko** [comment] 2024-03-11 06:18
@Venkat-C-J 

Can you share the Redisson config?

**Closed** 2024-04-13 08:10 UTC
Labels: question

**Comment by Ftrybe** [comment] 2024-04-26 05:05
I encountered the same error and initially had Redis version 6. Upgrading to the latest version resolved the issue for me. It seems that compatibility or specific fixes in the newer Redis versions may address this error. It might be worth checking if there’s a particular version or configuration change that specifically targets this issue.
﻿

**Comment by mrniko** [comment] 2024-04-26 05:11
@Ftrybe 
There are no fixes in Redisson related to specific Redis versions. I guess Redis redeployment in cloud may also helped to resolve the issue.
