### ISSUE TITLE
RLocalCachedMap with SentinelConnectionManager sometimes fail to reattach topic after Failover

### ISSUE THREAD

**Issue by lehuuthanh5** [redisson/redisson#5194] opened 2023-07-25 03:09 UTC
Hi,
I'm using Redisson 3.20.0 with SentinelConnectionManager (1 master, 2 slaves)
I run an application with 1500 RLocalCachedMaps(UPDATE strategy). I run on sentinel this command: `SENTINEL FAILOVER mymaster`. Sometimes, after Failover time, Redisson cannot reattach 1500 topics for the maps.
Any advice on this? or this is a bug?
Redisson Config:
```
config.useSentinelServers()
                .setMasterName("")
                .setPassword("")
                .setReadMode(ReadMode.SLAVE)
                .setSubscriptionMode(SubscriptionMode.SLAVE)
                .setKeepAlive(true)
                .setTcpNoDelay(true)
                .addSentinelAddress("")
                .setSubscriptionsPerConnection(200)
                .setSlaveConnectionPoolSize(1000)
                .setMasterConnectionPoolSize(1000);
config.setNettyThreads(256);
config.setCheckLockSyncedSlaves(false);
```
Thanks

**Comment by lehuuthanh5** [comment] 2023-07-26 11:49
Hi @mrniko
When the case occurred, I can see that the entry inside `freePubSubConnections` has RedisPubSubConnection.closed = true. Redisson always gets this PubSubConnectionEntry to re-subscribe and StacklessClosedChannelException is thrown and the Topic cannot re-subscribe.
![image](https://github.com/redisson/redisson/assets/9514682/3092a714-c08e-48c7-aa54-2cb8304d2e02)
I don't know the root cause yet. 
Potential cause: When failover occurred with the command `SENTINEL FAILOVER mymaster`, It has a race condition between creating PubSubConnectionEntry and closing PubSubConnectionEntry connection 
Anyway, The PubSubConnectionEntry should not be in freePubSubConnections. Do you have any advice on this? 
Thanks

**Comment by lehuuthanh5** [comment] 2023-07-27 04:37
Hi @mrniko, I found PublishSubscribeService.java version
https://github.com/redisson/redisson/blob/b172cd81182142f00cf5f4760df0ed0b52841647/redisson/src/main/java/org/redisson/pubsub/PublishSubscribeService.java
This will fix the problem, and it should exit from 3.19.0 with this fix
https://github.com/redisson/redisson/commit/b172cd81182142f00cf5f4760df0ed0b52841647#diff-ee43636685559b77a9e923d342764381a8cd8e3b3272463dd47b5eb6baccb197
Any problem here that makes this commit not released?
Thanks

**Comment by mrniko** [comment] 2023-07-27 05:17
it was released but there other issues which lead to further changes of these part

**Comment by mrniko** [comment] 2023-07-27 05:35
> The PubSubConnectionEntry should not be in freePubSubConnections. Do you have any advice on this?

It can be in freePubSubConnections if subscribedChannelsAmount allows to acquire more connections for it.

Unable to reproduce the issue with the latest version. Can you try it?

**Comment by lehuuthanh5** [comment] 2023-07-27 05:37
> It can be in freePubSubConnections if subscribedChannelsAmount allows to acquire more connections for it.

But the connection status is closed. 
Let me try the newest

**Comment by mrniko** [comment] 2023-07-27 05:59
If it can be reproduced with the latest version. Try version below

[redisson-3.23.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/12179779/redisson-3.23.2-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment] 2023-07-27 06:08
Please skip suggested build for testing in this comment https://github.com/redisson/redisson/issues/5194#issuecomment-1652958851

**Comment by mrniko** [comment] 2023-07-27 06:13
It was fixed in https://github.com/redisson/redisson/issues/5039

**Comment by lehuuthanh5** [comment] 2023-07-27 07:06
Cannot reproduce with Redisson 3.23.1.
Thank you for your support

**Closed** 2023-07-27 07:35 UTC
Labels: question

**Comment by mrniko** [comment] 2023-07-27 07:43
Here is another issue I found https://github.com/redisson/redisson/issues/5199

**Comment by lehuuthanh5** [comment] 2023-07-27 08:15
Ah, I see.
I debugged with the newest version and see all the topics are reattached to Master Node.

Thank you for your fixing
