### ISSUE TITLE
Subscription timeout after 3000ms. Check network and/or increase 'timeout' parameter. 

### ISSUE THREAD

**Issue by ydziadovich** [redisson/redisson#4610] opened 2022-10-18 13:18 UTC
Hi. We use redis for distributed lock, storing some cache data and listen some key notification events. For this purposes we have a redis cluster with 3 masters and 3 slaves. Our team is experiencing the issue with _Subscription timeout_ in production after some couple of time (a few days) after start/restart our services. We can't understand the reason of this issue from stack trace:
`Subscription timeout after 3000ms. Check network and/or increase 'timeout' parameter. 
org.redisson.client.RedisTimeoutException: Subscription timeout after 3000ms. Check network and/or increase 'timeout' parameter.
	at org.redisson.pubsub.PubSubConnectionEntry.lambda$subscribe$0(PubSubConnectionEntry.java:177)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)`

It's not clear what method/service... can't subscribe and how we can debug it.
We don't have any issues with network. Also, we monitor redis and don't see any issues there. 

We have already increased:
subscriptionsPerConnection: 20
subscriptionConnectionPoolSize: 120
nettyThreads: 64
threads: 64

But it didn't help. Could you advice what config we can change to fix this issue or how we can debug this issue to understand a root cause of this issue?

**Redisson version**
3.17.6

**Comment by cnudroid** [comment] 2023-02-02 01:44
I saw this happening with 3.19.1 version too. I am trying to rule out that there is no network glitch.

`Caused by: org.redisson.client.RedisTimeoutException: Subscription timeout after 5000ms. Check network and/or increase 'timeout' parameter.
	at org.redisson.pubsub.PubSubConnectionEntry.lambda$subscribe$0(PubSubConnectionEntry.java:181)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)`

**Comment by mrniko** [comment] 2023-02-02 06:36
Is there any way to reproduce it?

**Comment by khuynhthanhchiluyen** [comment] 2023-06-26 06:23
still produce the same error with nettyThreads = 64 or 128

**Comment by mrniko** [comment] 2023-06-26 08:18
@khuynhthanhchiluyen 

Is there any code to reproduce the issue?

**Comment by mrniko** [comment] 2023-06-26 11:02
Incorrect handling of "unknown command" response may cause to this issue. Fixed in https://github.com/redisson/redisson/issues/5128

**Closed by mrniko** 2023-06-26 11:02 UTC
Labels: question
