### ISSUE TITLE
Redisson connections release while command execution attempt failed

### ISSUE THREAD

**Issue by lasfromhell** [redisson/redisson#3733] opened 2021-07-16 13:58 UTC
We faced an issue in following Azure Redis Cluster configuration:
  * master1 <-> slave1
  * master2 <-> slave2

Version of Redisson 3.15.4, Redis 4.0.14

Configuration:
    clusterServersConfig:
      idleConnectionTimeout: 10000
      connectTimeout: 15000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500
      failedSlaveReconnectionInterval: 3000
      failedSlaveCheckInterval: 60000
      subscriptionsPerConnection: 5
      clientName: null
      subscriptionConnectionMinimumIdleSize: 1
      subscriptionConnectionPoolSize: 50
      slaveConnectionMinimumIdleSize: 24
      slaveConnectionPoolSize: 64
      masterConnectionMinimumIdleSize: 24
      masterConnectionPoolSize: 64
      readMode: "MASTER"
      subscriptionMode: "MASTER"
      nodeAddresses:
        - "rediss://...."
    threads: 16
    nettyThreads: 32
    codec: !<org.redisson.codec.FstCodec> {}
    transportMode: "NIO"

After few restarts of Redis we see following errors all the time:

org.redisson.client.RedisTimeoutException: Unable to acquire connection! RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@5123a990(failure: java.util.concurrent.CancellationException)]Increase connection pool size. Node source: NodeSource [slot=8616, addr=null, redisClient=null, redirect=null, entry=null], command: (BLPOP), params: [{job-scheduler-executor:org.redisson.executor.RemoteExecutorService}, 0] after 0 retry attempts","2":"at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:187)","3":"at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)","4":"at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)","5":"at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)","6":"at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)","7":"at java.base/java.lang.Thread.run(Unknown Source)\n"}}

And we have a question:
1. When RedisExecutor executes its command and retryTimeout happened then:
1.1. Error message is assigning to exception variable
1.2. Then attemptPromise is cancelling
1.3. Then attemptPromise.onComplete happens which calls releaseConnection
1.4. There is a code
![image](https://user-images.githubusercontent.com/31354373/125958543-eab9da72-fece-4028-be37-21b5fe4e0162.png)
which do not release connection if connectionFuture.isSuccess() == false (and this condition always met in case of timeout or I am wrong?).
And looks like that its never releases this connection and free connection counter semaphore is not releasing at all here.
Is it expected behavior? Should we always have connectTimeout less than retryInterval?
And in case when 2nd attempt fails too, we still see in the logs "after 0 retry attempts" because we already have "exception" variable set on previous step.

**Comment by mrniko** [comment] 2021-07-16 17:53
> which do not release connection if connectionFuture.isSuccess() == false (and this condition always met in case of timeout or I am wrong?).

Connection isn't released if it wasn't acquired.

> And looks like that its never releases this connection and free connection counter semaphore is not releasing at all here.
Is it expected behavior?

If connectionFuture was canceled then it's released at ConnectionPool line 245.

> Should we always have connectTimeout less than retryInterval?

Redisson doesn't connect each time since connections are pooled.

**Comment by lasfromhell** [comment] 2021-07-17 08:32
> Connection isn't released if it wasn't acquired.
> If connectionFuture was canceled then it's released at ConnectionPool line 245.

ConnectionPool:245 calls .remove method which adds listener to removedListeners in Semaphore but who will increment counter in Semaphore in this case? What if we already acquired all connections and counter is 0?

Here is the link to the logs where we always have failure while commands sent to 2nd master node of redis (10.40.20.4:15002 myself,master - 0 1626408459000 19 connected 8192-16383):
[logfile](https://github.com/redisson/redisson/files/6834415/job-scheduler-ff6474494-kpc85.txt)
It's not from the beginning but we were not able to collect it from beginning due to rolling logs. And it's reproducing pretty rare after restarts of some nodes (we saw that 2nd master and it's slave was restarted few times before this starting happen)

Additionally, there we always see "RedisTimeoutException:CancellationException Unable to acquire connection .... after 0 retry attempts" and at the same time for the same command we see lines like "attempt 2 for command (BLPOP) and params", "attempt 3 for command (BLPOP) and params" (we have configuration with max 3 attempts).

Restart of an application resolves the problem
Could you please take a look?

**Comment by mrniko** [comment] 2021-07-24 07:32
I fixed AsyncSemaphore race condition which may cause this issue. https://github.com/redisson/redisson/commit/34d2e4de3a8b6cc9170fe7b5d82d40498fe60f1e

**Comment by mrniko** [comment] 2021-08-03 06:41
I'm closing this. Let me know if you reproduce it with 3.16.1+ version.

**Closed by mrniko** 2021-08-03 06:41 UTC
Labels: failover, question

**Comment by lasfromhell** [comment] 2021-08-03 06:56
Tried to reproduce on 3.16.1 but wasn't able anymore. Looks like that it's working
