### ISSUE TITLE
Problem to deserialize object with jackson

### ISSUE THREAD

**Issue by LucasES** [redisson/redisson#1865] opened 2019-01-16 18:40 UTC
Hi guys,

I have two applications, one read and another write on redis:

My entity

    @Data
    @JsonTypeInfo(use = JsonTypeInfo.Id.NONE)
    public class Job implements Serializable {
        private static final long serialVersionUID = 1L;
        private String a;
        private String b;
    }

For save i use this code:

`RList<Job> list = redissonClient.getList(key);
        list.addAll(jobList);`

The value is saved in redis just like that:

> {"a":"test","b":"test"}

My problem is when I try to read the redis list at another java application.

I have a method that use this code to read the list:
`List<Job> allJobs = redissonClient.getList(key);`

But when i execute the project i receive this error:
> io.netty.handler.codec.DecoderException: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class java.lang.Object]: missing type id property '@class'
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 322]

My redisson.json file has the same configuration in both projects:

`{
  "singleServerConfig": {
    "idleConnectionTimeout": 10000,
    "pingTimeout": 1000,
    "connectTimeout": 10000,
    "timeout": 3000,
    "retryAttempts": 3,
    "retryInterval": 1500,
    "reconnectionTimeout": 3000,
    "failedAttempts": 3,
    "password": null,
    "subscriptionsPerConnection": 5,
    "clientName": null,
    "address": "redis://127.0.0.1:6379",
    "subscriptionConnectionMinimumIdleSize": 1,
    "subscriptionConnectionPoolSize": 50,
    "connectionMinimumIdleSize": 10,
    "connectionPoolSize": 64,
    "database": 0,
    "dnsMonitoringInterval": 5000
  },
  "threads": 0,
  "nettyThreads": 0,
  "codec": null,
  "useLinuxNativeEpoll": false
}`

Version of redisson:

> <dependency>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.9.1</version>
        </dependency>

**Comment by LucasES** [comment] 2019-01-16 18:42
Hi guys,

I have two application for read and write the redis values:

My entity

    `@Data
    @JsonTypeInfo(use = JsonTypeInfo.Id.NONE)
    public class Job implements Serializable {
    private static final long serialVersionUID = 1L;
    private String a;
    private String b;
    }`

For save i use this code:

  `RList<Job> list = redissonClient.getList(key);
   list.addAll(jobList);`

My problem is when i tried read the List of Jobs at another java application.

I have a method that use this code to read the list:

`List<Job> allJobs = redissonClient.getList(key);`

But when i execute the project i receive this error:

> io.netty.handler.codec.DecoderException: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class java.lang.Object]: missing type id property '@class'
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 322]

My redisson.json file is setted codec with null value.

**Comment by jackygurui** [comment] 2019-01-16 21:43
if you remove `@JsonTypeInfo(use = JsonTypeInfo.Id.NONE)` it would work then.

**Comment by maxhomann** [comment] 2019-01-17 14:30
Hi there,
I'm having the same issue but without the `@JsonTypeInfo` annotation. Like @LucasES, I have two applications and both reside in two different code bases and therefore have different package names. Now when trying to deserialize in ProjB just like Lucas does, the following trace states to me that the type information is stored with the fully-qualified name.

> Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'com.projA.Job' as a subtype of [simple type, class java.lang.Object]: no such class found

Makes sense, because even though the classes are the same, their package is different, i.e. 
`com.projA.Job` and `com.projB.Job`. Using 

> @JsonTypeInfo(use = JsonTypeInfo.Id.NONE)
public class Job {}

or `JsonTypeInfo.Id.NAME` in the hope that the type information is stored without the package name or not at all has no effect.

**Comment by LucasES** [comment] 2019-01-18 16:17
@jackygurui unfornatelly if i remove this annotation the redisson will save the Object just like that:

> {"@class":"br.com.projectname.dto.Job","a":"test","b":"test"}

As you can se, the value that saved in redis with the full package of my Object.

When i try deserialize the object that is mapped in another package in my Second Project.
Example: br.com.projectb.entity.Job

I receive this exception:

> io.netty.handler.codec.DecoderException: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class java.lang.Object]: missing type id property '@Class'
at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 322]

**Comment by LucasES** [comment] 2019-01-18 16:19
@maxhomann Were you successful in doing so?

**Comment by jackygurui** [comment] 2019-01-21 22:43
@LucasES I think the problem is when supposedly a same class gets bundled into different packages, in the laws of Java, they should be treated as different classes, the `@Class` is used specifically to instruct Jackson which class the JSON string should represent as there is no way to tell at the runtime. 

So the solution is actually on your side, you can either abay the laws of Java by moving the class in question to a shared library so they carries the same package names. Or you need to have a `TypedJsonJacksonCodec` and tell Redisson/Jackson exactly how you would like to deserialise the JSON string.

**Comment by maxhomann** [comment] 2019-01-22 08:21
@jackygurui But Jackson offers the capability to serialize a type to JSON as simple name or minimal class name ([like so](https://github.com/FasterXML/jackson-docs/wiki/JacksonPolymorphicDeserialization#12-per-class-annotations)), i.e. 
> @JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
public class Job {}

Looking at the code at 
https://github.com/redisson/redisson/blob/12e4968c474d0315637471f79f6cc7fd4a5810cf/redisson/src/main/java/org/redisson/codec/JsonJacksonCodec.java#L152
redisson seems to always use the `@Class` property for type resolving when using the JsonJacksonCodec. In my case it even ignores any Jackson class annotations.

**Comment by jackygurui** [comment] 2019-01-22 16:54
@maxhomann You're correct that Jackson does offer the ability to serialise a type to JSON with simple of minimal class name, but what it can't do is deserialise them with out extra information. The problem you're experiencing is on deserialisation side.

**Comment by maxhomann** [comment] 2019-01-23 15:36
@jackygurui Yes, you are right but I am not sure if you understood me corretly. I experimented a little more with the Jackson class annotations. Consider we have this pojo and basic redis operations across two packages

```java
package projA & projB;
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
@JsonTypeName("ABC-Type")
public class ABC {
    public String aString;
}

package projA;
public static void main(String[] args) {    
    ABC data = new ABC();
    data.aString = "coming from projA";
    RSet<ABC> testSet = redis.getSet("testset");
    testMap.clear();
    testMap.add(data);
}

package projB;
public static void main(String[] args) {
    ...
    RSet<ABC> testSet = redis.getSet("testset");
    testSet.forEach(System.out::println);
}
```
After executing projA redis has `"{\"@type\":\"ABC-Type\",\"aString\":\"coming from projA\"}"` confirming to me that the jackson annotations did indeed change the serialization behavior. Now when trying to run projB, I get 
```
org.redisson.client.RedisException: Unexpected exception while processing command

	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:322)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:165)
	at org.redisson.RedissonObject.get(RedissonObject.java:69)
	at org.redisson.RedissonSet.scanIterator(RedissonSet.java:88)
	at org.redisson.RedissonSet$1.iterator(RedissonSet.java:97)
	at org.redisson.RedissonBaseIterator.hasNext(RedissonBaseIterator.java:64)
	at java.lang.Iterable.forEach(Iterable.java:74)
	...
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class java.lang.Object]: missing type id property '@class'
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 59]
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:1638)
```
which leads me to my previous post about that one line where the `JsonTypeInfo.Id.CLASS` is forced
https://github.com/redisson/redisson/blob/12e4968c474d0315637471f79f6cc7fd4a5810cf/redisson/src/main/java/org/redisson/codec/JsonJacksonCodec.java#L152

How can I configure redisson to use the `JsonTypeInfo.Id.NAME` or any other Jackson annotation-induced behavior to resolve the type? I clearly always looks for the `@class` in the json string. This would also solve @LucasES problem.

**Comment by jackygurui** [comment] 2019-01-24 01:10
@maxhomann I think I understood your requirement correctly: you would like to have minimal class path information to deserialise your `ABC` class. 

Before I go on to explain why Redisson has took the path that leads to where we are now, just imagine in a bazzar senario where someone has asked you to find a file called `ABC.txt` in a random computer but didn't tell you in which directory. It would be impossible to find it without scanning/indexing the entire filesystem. 

Bear in mind the generic type info is not passed to the JVM runtime, it is easy to see Redisson is facing the same problem when it received a piece of string from Redis and it just says its a type of `ABC` but god knows which package it is from. So the dilemma of making this to work is whether to ask users to preregister all the class, or should it scan the entire classpath every single time and make a guess when we saw duplicated class names from different packages (you will be surprised to see how many duplicated names), or we just ask the user to write down the names along with their classpath so we know exactly where to look for them.

Redisson took the liberty and choose the latter as the default option. Simply because it requires nothing extra to setup and works for most of the senarios. In particular when the class path is different but shares the same name, as per Java specification dictates, it has be treated as different class. 

To recognise the fact that default option cannot cover every single use case, Redisson allows user to customise the codec to suite each ones own needs. This can be done on the global level and/or per key level, it is up to the user to decide. 

So there are two solutions:
1. the fact that `projA.ABC` and `projB.ABC` are required to be treated as the same class offends JLS, it is the best to move `ABC` to a package which are accessible by both projects. Then Jackson/Redisson should work just as normal.
2. If it is not possible to do above, you need to implement your own convention with or without Jackson and tell Redisson to use this particular way for a given key. Redisson has provided `TypedJsonJacksonCodec` to simplify the process if you prefer to use Jackson. You can find the usage here: https://github.com/redisson/redisson/blob/365731758f175fbd33cbc3091eadf7d7459179ca/redisson/src/test/java/org/redisson/codec/TypedJsonJacksonCodecTest.java

Hope I have explained everything clearly.

**Comment by maxhomann** [comment] 2019-01-24 07:14
Wow, it finally works! Please excuse me, at the end I was the one that wasn't clear, because all I wanted to know is your second solution 😌 I'm feeling stupid now, didn't see that redis.getSet/getMap etc. had overloaded methods where I could provide a codec.
To adress your explanation of what happens: I was fully aware of that and agree with you that this should be the default way. Have a nice day!

**Closed** 2019-03-07 06:08 UTC

**Comment by testower** [comment] 2020-12-02 20:11
Hope you don't mind me asking a follow-up question on this thread. I'm trying to use JsonJacksonCodec together with geojson-jackson to define certain geojson structures *nested inside my json* (see https://github.com/NABSA/gbfs/blob/v2.1-RC2/gbfs.md#geofencing_zonesjson-added-in-v21-rc), and facing some issues that their serialisers don't implement type id handling:

```
java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Type id handling not implemented for type org.geojson.LngLatAlt (by serializer of type org.geojson.jackson.LngLatAltSerializer) (through reference chain: org.entur.lamassu.model.gbfs.v2_1.GeofencingZones["data"]->org.entur.lamassu.model.gbfs.v2_1.GeofencingZones$Data["geofencing_zones"]->org.entur.lamassu.model.gbfs.v2_1.GeofencingZones$FeatureCollection["features"]->java.util.ArrayList[0]->org.entur.lamassu.model.gbfs.v2_1.GeofencingZones$Feature["geometry"]->org.geojson.MultiPolygon["coordinates"]->java.util.ArrayList[0]->java.util.ArrayList[0]->java.util.ArrayList[0])
```

I'm giving the codec to the redisson top level redisson configuration, and I don't understand how I can provide a specific typed codec for a specific key, way deep in the json tree. Do I need to write my own pojos here?

**Comment by mrniko** [comment] 2020-12-03 06:54
You can define mixin for org.geojson.LngLatAlt to define id https://www.tutorialspoint.com/jackson_annotations/jackson_annotations_mixin.htm

**Comment by testower** [comment] 2020-12-03 07:40
Thanks, I was hoping that was a solution, but how to access the object mapper? It doesn't seem to be accessible via the JsonJacksonCodec instance?

**Comment by testower** [comment] 2020-12-03 08:11
@mrniko I feel like I'm pretty close to a solution here, but I'm still unsure how to use the mixin "to define id". Is there an annotation that I can use to achieve this? I'm have a hunch that I need to write my own serializer and use the mixin to provide it, but would be nice to know if there is a shorter way. 🤔

**Comment by mrniko** [comment] 2020-12-03 08:26
you can use own ObjectMapper without ids.

**Comment by testower** [comment] 2020-12-03 08:32
Sorry, maybe it's obvious, but I don't understand what that means. I added a mixin for LngLatAlt, but I don't know what annotations to add to it. As is, I'm still just getting the same error as before.

```
        config = new Config();

        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.addMixIn(org.geojson.LngLatAlt.class, MixinForLngLatAlt.class);
        var codec = new JsonJacksonCodec(objectMapper);
        config.setCodec(codec);
```

```
public abstract class MixinForLngLatAlt extends LngLatAlt {}
```

**Comment by mrniko** [comment] 2020-12-03 09:30
try to override `JsonJacksonCodec.initTypeInclusion` method as empty.

**Comment by testower** [comment] 2020-12-03 09:31
But won't that break the rest of my polymorphic serialisation setup?

**Comment by testower** [comment] 2020-12-03 10:06
Since all I needed was serialization/deserialization of multipolygons, I went with my own naïve implementation instead of using geojson-jackson - so problem solved. Thanks for your time though @mrniko 🥇

**Comment by jarodrevisionist3** [comment] 2025-01-30 12:48
> Thanks, I was hoping that was a solution, but how to access the object mapper? It doesn't seem to be accessible via the JsonJacksonCodec instance?
> 
> EDIT: The obvious solution when I used my brain: Use the constructor of JsonJacksonCodec to provide my own object mapper instance 👍





https://stackdev.space/questions/delete-the-element-from-the-json-data
