### ISSUE TITLE
Connection leak issue while using Redis-Redisson

### ISSUE THREAD

**Issue by ammar-ahmad** [redisson/redisson#2771] opened 2020-05-14 17:16 UTC
We have a Redis cluster(running in Sentinel mode) with 3 nodes and we are using Redisson (version 3.10.7) to interact with Redis. While checking for some other issue, we noticed a high number of client being connected to server.
On further investigation, we noticed the below scenarios. 

    +-------------+-----------------------+
    |Client         | Connections         |
    +-------------------------------------+
    |Client A at T0 |   33                |
    |               |(default by Reddison)|
    |Client A at T1 |99                   |
    |               |(post network glitch |
    |               |or server crash)     |
    |Client A at T2 | 33                  |
    |               |  (post restart app) |
    |               |                     |
    +-------------------------------------+
	
In case app restart is not done as well, connection remains open even though we have a "timeout" set at server level. Is Redisson leaving the older connection open  and creates a new one in case of redis server crash or network glitch?
Also, I noticed that with each client connection to Redis server,Redis is opening 4 file descriptor. Is this normal?

**Comment by mrniko** [comment] 2020-05-15 07:16
Fixed in https://github.com/redisson/redisson/issues/2672

**Comment by ammar-ahmad** [comment] 2020-05-15 18:27
I tried taking the master branch code and I am still able to replicate the issue. 
Just to let you know, we are using Redis with Sentinel. 
Can we reopen this issue?

**Comment by mrniko** [comment] 2020-05-16 06:55
> Is Redisson leaving the older connection open and creates a new one in case of redis server crash or network glitch?

Broken connections are reconnected by ConnectionWatchdog. What are TCP status of all these connections?

**Comment by akhandel** [comment] 2020-05-18 13:16
For all connection, TCP status is ESTABLISHED.

**Comment by mrniko** [comment] 2020-05-18 14:55
Does this happen after Redis failover?

**Comment by akhandel** [comment] 2020-05-20 06:51
we are using below command to see,

lsof -n | grep redis | grep 'my ip'


Connection are keep on increasing while reconnect to redis.

Connection are getting broken very frequency and we are seeing connection pool is getting created again and again.

**Comment by mrniko** [comment] 2020-05-21 09:42
Could you provide steps to reproduce the problem?

Did you try to set `pingConnectionInterval` setting https://github.com/redisson/redisson/wiki/2.-Configuration#pingconnectioninterval ?

**Comment by akhandel** [comment] 2020-05-27 11:52
I did try setting pingConnectionInterval to 1000 but didn't help. 
This is happening in longevity run and connections are not getting closed and have in established.

This could due to sentinal down and in that case, connection pool gets recreated and few of the connection become as leak which get slowly increased.

**Comment by mrniko** [comment] 2020-05-27 12:10
Could you describe steps to reproduce the problem?

**Comment by akhandel** [comment] 2020-06-01 07:18
Test the application for a longer time around 24 hours continuously
Break in network intermittently between redis and application and reconnect within few milliseconds
The previous connections still have tcp established and redisson creates new pool of connection
In 24 hours it increased to 10 times without releasing connection.

**Comment by mrniko** [comment] 2020-06-01 07:25
> Break in network intermittently between redis and application and reconnect within few milliseconds

You mean to break connection between all Redis nodes and application?

**Comment by mrniko** [comment] 2020-06-01 07:36
Do you see any errors in logs? like NullPointerException ?

**Comment by mrniko** [comment] 2020-06-15 13:21
Do you use ssl connection to Redis?

**Comment by kazetsukaimiko** [comment] 2020-06-16 15:02
We're experiencing this with SSL connections to Redis.

**Comment by mrniko** [comment] 2020-06-16 17:11
@kazetsukaimiko 

Which Redisson version do you use?
Could you attach heap dump?

**Comment by kazetsukaimiko** [comment] 2020-06-16 17:47
3.12.2. 
Cannot attach heap dump, too much red tape there as this is in our production environment.

How it manifests: We use Azure Redis, which is a Tiered service. There are limits to the number of connections based on tier. Redission eventually bombs out saying that it is unable to fill the connection pool with the minimum number of connections because the Azure service stops accepting additional connections (1000 is our limit). 

When we go to check connections we see around 800 ESTABLISHED TCP connections on the offending node, and upwards of 5000 SYN_SENT typically. Between the "bad node" and all of its replicas, we have close to if not 1000 connections total.

I believe we are experiencing the same kind of "millisecond outages" described above.

**Comment by mrniko** [comment] 2020-06-17 05:02
Could you try to reproduce it with version attached?

[redisson-3.13.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4790444/redisson-3.13.2-SNAPSHOT.jar.zip)

**Comment by kazetsukaimiko** [comment] 2020-06-17 13:34
@mrniko I really appreciate the quick turnaround. This issue takes time (a few days) to manifest, let me see if I can put together a testing plan.

Do you have a diff for this build somewhere I can peek through as well?

**Comment by mrniko** [comment] 2020-06-17 15:30
Here is the fix https://github.com/redisson/redisson/commit/b707fe8e297bcc9dbf36e83684e667ecc387769b

**Comment by kazetsukaimiko** [comment] 2020-06-18 14:17
!conectionPromise.isDone() check looks like a potential NPE? There are constructors where that field is not set. Seems like you should do the same null check as you do with command just above.

We are setting up our test case today.

**Comment by kazetsukaimiko** [comment] 2020-06-18 15:49
We're going to have to wait for this fix to trickle down to a release and roll it out then.

**Comment by mrniko** [comment] 2020-06-18 16:38
conectionPromise can't be null

**Comment by mrniko** [comment] 2020-07-03 05:36
Fixed in https://github.com/redisson/redisson/issues/2845

**Closed** 2020-07-03 05:36 UTC
