### ISSUE TITLE
Use RMap<String, Map<Integer, Integer>> show exception: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by lovecto** [redisson/redisson#2025] opened 2019-04-04 05:31 UTC
when user RMap
`@Autowired
	private RedissonClient redisson;

	@Test
	public void testRedissonMap(){
		try {
			String mapGroup = "TEST_MAP_GROUP_2";
			String key = "TEST_KEY_2";
		
			RMap<String, Map<Integer, Integer>> rMap = redisson.getMap(mapGroup);
			Map<Integer, Integer> map = new HashMap<Integer, Integer>();
			for(int i = 0; i < 10; i++){
				map.put(i, i);
			}
			rMap.put(key, map);
			map = rMap.get(key);
			map.forEach(new BiConsumer<Integer, Integer>() {
				@Override
				public void accept(Integer t, Integer u) {
					System.out.println("数据集:" + t + "," + u);
				}
			});
		} catch (Exception e) {
			e.printStackTrace();
		}
	}`
throw java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer

**Comment by mrniko** [comment] 2019-04-04 05:40
Unable to reproduce with 3.10.5 version

**Comment by lovecto** [comment] 2019-04-04 06:27
Appeared in version 3.8.0，but 3.10.5 is ok ! thanks !

**Comment by lovecto** [comment] 2019-04-04 06:28
> Unable to reproduce with 3.10.5 version

Appeared in version 3.8.0，but 3.10.5 is ok ! thanks !

**Comment by mrniko** [comment] 2019-04-04 06:28
Great! I'm closing it

**Closed by mrniko** 2019-04-04 06:28 UTC
