### ISSUE TITLE
use RBloomFilter contains throw org.redisson.client.RedisMovedException

### ISSUE THREAD

**Issue by qq31715879** [redisson/redisson#3031] opened 2020-09-04 04:11 UTC
RBloomFilter<String> bloomFilter = DrpRedissonClusterPool.get().getBloomFilter("getBloomFilter", new FstCodec());
        bloomFilter.delete();
        bloomFilter.tryInit(40000, 0.01);
        System.out.println(bloomFilter.getSize() / 8 / 1024 / 1024);
        System.out.println(bloomFilter.count());
        bloomFilter.add("111");
        bloomFilter.add("111");
        bloomFilter.add("111");
        System.out.println(bloomFilter.getSize());
        System.out.println(bloomFilter.count());
        System.out.println(bloomFilter);
        System.out.println(bloomFilter.contains("111"));

----------------------------------------------------------------
run bloomFilter.contains("111")

Exception in thread "main" org.redisson.client.RedisMovedException
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:339)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:266)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:207)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mrniko** [comment] 2020-09-07 11:33
Please share Redisson config

**Comment by qq31715879** [comment] 2020-09-07 12:06
> Please share Redisson config

Config config = new Config();
        String epoll = get("epoll");
        if (!DrpPropertySystem.isWindows()) {
            config.setTransportMode(TransportMode.EPOLL);
        } else {
            config.setTransportMode(TransportMode.NIO);
        }


        String lockWatchdogTimeout = get("lockWatchdogTimeout");
        if (DrpStringUtil.isNotEmpty(lockWatchdogTimeout)) {
            config.setLockWatchdogTimeout(Long.parseLong(lockWatchdogTimeout));
        }
        config.setExecutor(DrpThreadPool.getExecutor());
        config.setKeepPubSubOrder(false);

        String cluster = DrpProperty.get("redis.cluster");
        DrpAdapter.validation(cluster, "nacos get redis cluster is null");
        assert cluster != null;
        String[] clusterArray = cluster.split(",");
        for (int i = 0; i < clusterArray.length; i++) {
            clusterArray[i] = "redis://" + clusterArray[i];
        }
        String scanInterval = get("scanInterval");
        String subscriptionConnectionMinimumIdleSize = get("subscriptionConnectionMinimumIdleSize");
        String subscriptionConnectionPoolSize = get("subscriptionConnectionPoolSize");
        String lockWatchdogTimeout = get("lockWatchdogTimeout");
        if (DrpStringUtil.isNotEmpty(lockWatchdogTimeout)) {
            config.setLockWatchdogTimeout(Long.parseLong(lockWatchdogTimeout));
        }
        config.setExecutor(DrpThreadPool.getExecutor());
        config.setKeepPubSubOrder(false);

        String cluster = DrpProperty.get("redis.cluster");
        DrpAdapter.validation(cluster, "nacos get redis cluster is null");
        assert cluster != null;
        String[] clusterArray = cluster.split(",");
        for (int i = 0; i < clusterArray.length; i++) {
            clusterArray[i] = "redis://" + clusterArray[i];
        }
        String scanInterval = get("scanInterval");
        String subscriptionConnectionMinimumIdleSize = get("subscriptionConnectionMinimumIdleSize");
        String subscriptionConnectionPoolSize = get("subscriptionConnectionPoolSize");
        String subscriptionsPerConnection = get("subscriptionsPerConnection");
        String slaveConnectionMinimumIdleSize = get("slaveConnectionMinimumIdleSize");
        String slaveConnectionPoolSize = get("slaveConnectionPoolSize");
        String masterConnectionMinimumIdleSize = get("masterConnectionMinimumIdleSize");
        String masterConnectionPoolSize = get("masterConnectionPoolSize");
        String idleConnectionTimeout = get("idleConnectionTimeout");
        String connectTimeout = get("connectTimeout");
        String timeout = get("timeout");
        String retryAttempts = get("retryAttempts");
        String retryInterval = get("retryInterval");
        String reconnectionTimeout = get("reconnectionTimeout");
        String failedAttempts = get("failedAttempts");
        config.setCodec(JsonJacksonCodec.INSTANCE);
        config.useClusterServers()
                .setScanInterval(DrpStringUtil.isEmpty(scanInterval) ? 1000 * 60 * 30 : Integer.parseInt(scanInterval))
                .setSubscriptionConnectionMinimumIdleSize(DrpStringUtil.isEmpty(subscriptionConnectionMinimumIdleSize) ? 1 : Integer.parseInt(subscriptionConnectionMinimumIdleSize))
                .setSubscriptionConnectionPoolSize(DrpStringUtil.isEmpty(subscriptionConnectionPoolSize) ? 20 : Integer.parseInt(subscriptionConnectionPoolSize))
                .setSubscriptionsPerConnection(DrpStringUtil.isEmpty(subscriptionsPerConnection) ? 5 : Integer.parseInt(subscriptionsPerConnection))
                .setSlaveConnectionMinimumIdleSize(DrpStringUtil.isEmpty(slaveConnectionMinimumIdleSize) ? 12 : Integer.parseInt(slaveConnectionMinimumIdleSize))
                .setSlaveConnectionPoolSize(DrpStringUtil.isEmpty(slaveConnectionPoolSize) ? 64 : Integer.parseInt(slaveConnectionPoolSize))
                .setMasterConnectionMinimumIdleSize(DrpStringUtil.isEmpty(masterConnectionMinimumIdleSize) ? 12 : Integer.parseInt(masterConnectionMinimumIdleSize))
                .setMasterConnectionPoolSize(DrpStringUtil.isEmpty(masterConnectionPoolSize) ? 64 : Integer.parseInt(masterConnectionPoolSize))
                .setIdleConnectionTimeout(DrpStringUtil.isEmpty(idleConnectionTimeout) ? 10000 : Integer.parseInt(idleConnectionTimeout))
                .setConnectTimeout(DrpStringUtil.isEmpty(connectTimeout) ? 4000 : Integer.parseInt(connectTimeout))
                .setTimeout(DrpStringUtil.isEmpty(timeout) ? 2000 : Integer.parseInt(timeout))
                .setRetryAttempts(DrpStringUtil.isEmpty(retryAttempts) ? 0 : Integer.parseInt(retryAttempts))
                .setRetryInterval(DrpStringUtil.isEmpty(retryInterval) ? 1000 : Integer.parseInt(retryInterval))
//                .setreconnectionTimeout(DrpStringUtil.isEmpty(retryInterval) ? 1 : Integer.parseInt(retryInterval))
//                .failedAttemp(DrpStringUtil.isEmpty(retryInterval) ? 1 : Integer.parseInt(retryInterval))
                .addNodeAddress(clusterArray);
        return config;
        String subscriptionsPerConnection = get("subscriptionsPerConnection");
        String slaveConnectionMinimumIdleSize = get("slaveConnectionMinimumIdleSize");
        String slaveConnectionPoolSize = get("slaveConnectionPoolSize");
        String masterConnectionMinimumIdleSize = get("masterConnectionMinimumIdleSize");
        String masterConnectionPoolSize = get("masterConnectionPoolSize");
        String idleConnectionTimeout = get("idleConnectionTimeout");
        String connectTimeout = get("connectTimeout");
        String timeout = get("timeout");
        String retryAttempts = get("retryAttempts");
        String retryInterval = get("retryInterval");
        String reconnectionTimeout = get("reconnectionTimeout");
除，直到 reconnectionTimeout（重新连接时间间隔） 超时以后再次尝试
        String failedAttempts = get("failedAttempts");
        config.setCodec(JsonJacksonCodec.INSTANCE);
        config.useClusterServers()
                .setScanInterval(DrpStringUtil.isEmpty(scanInterval) ? 1000 * 60 * 30 : Integer.parseInt(scanInterval))
                .setSubscriptionConnectionMinimumIdleSize(DrpStringUtil.isEmpty(subscriptionConnectionMinimumIdleSize) ? 1 : Integer.parseInt(subscriptionConnectionMinimumIdleSize))
                .setSubscriptionConnectionPoolSize(DrpStringUtil.isEmpty(subscriptionConnectionPoolSize) ? 20 : Integer.parseInt(subscriptionConnectionPoolSize))
                .setSubscriptionsPerConnection(DrpStringUtil.isEmpty(subscriptionsPerConnection) ? 5 : Integer.parseInt(subscriptionsPerConnection))
                .setSlaveConnectionMinimumIdleSize(DrpStringUtil.isEmpty(slaveConnectionMinimumIdleSize) ? 12 : Integer.parseInt(slaveConnectionMinimumIdleSize))
                .setSlaveConnectionPoolSize(DrpStringUtil.isEmpty(slaveConnectionPoolSize) ? 64 : Integer.parseInt(slaveConnectionPoolSize))
                .setMasterConnectionMinimumIdleSize(DrpStringUtil.isEmpty(masterConnectionMinimumIdleSize) ? 12 : Integer.parseInt(masterConnectionMinimumIdleSize))
                .setMasterConnectionPoolSize(DrpStringUtil.isEmpty(masterConnectionPoolSize) ? 64 : Integer.parseInt(masterConnectionPoolSize))
                .setIdleConnectionTimeout(DrpStringUtil.isEmpty(idleConnectionTimeout) ? 10000 : Integer.parseInt(idleConnectionTimeout))
                .setConnectTimeout(DrpStringUtil.isEmpty(connectTimeout) ? 4000 : Integer.parseInt(connectTimeout))
                .setTimeout(DrpStringUtil.isEmpty(timeout) ? 2000 : Integer.parseInt(timeout))
                .setRetryAttempts(DrpStringUtil.isEmpty(retryAttempts) ? 0 : Integer.parseInt(retryAttempts))
                .setRetryInterval(DrpStringUtil.isEmpty(retryInterval) ? 1000 : Integer.parseInt(retryInterval))
//                .setreconnectionTimeout(DrpStringUtil.isEmpty(retryInterval) ? 1 : Integer.parseInt(retryInterval))
//                .failedAttemp(DrpStringUtil.isEmpty(retryInterval) ? 1 : Integer.parseInt(retryInterval))
                .addNodeAddress(clusterArray);
        return config;

**Comment by qq31715879** [comment] 2020-09-08 01:34
> Please share Redisson config

there is no problem using the add method
use contains method throw org.redisson.client.RedisMovedException

**Comment by xianfengsong** [comment] 2020-09-09 12:29
same problem:
redis_version:3.2.9
redission:3.13.4

**the error string is "MOVED 9520 10.38.163.58:7110"**
**but when i connect to my local redis cluster(version 4.0)，bloomFilter.contains works fine**

my config:
@Bean
    public RedissonClient redissonClient() {
        List<String> nodeSet = redisClusterNodeSet.stream().map(e -> "redis://" + e).collect(Collectors.toList());
        Config config = new Config();
        config.useClusterServers().addNodeAddress(nodeSet.toArray(new String[]{}));
        return Redisson.create(config);
    }
@mrniko 
stack trace:

org.redisson.client.RedisMovedException: null
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:339)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:266)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:207)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)

**Comment by mrniko** [comment] 2020-09-11 09:44
@xianfengsong 

Unable to reproduce.
Could you share output log with logging leve `TRACE` for `org.redisson` package?

**Comment by xianfengsong** [comment] 2020-09-21 02:49
> @xianfengsong
> 
> Unable to reproduce.
> Could you share output log with logging leve `TRACE` for `org.redisson` package?

here is the Trace log:
2020-09-21 10:42:58 [redisson-netty-2-23] TRACE org.redisson.client.handler.CommandEncoder [CommandEncoder.java:112] channel: [id: 0x85628c0a, L:/10.221.128.67:40902 - R:/10.38.163.58:7111] message: *6
$4
EVAL
$211
local size = redis.call('hget', KEYS[1], 'size');local hashIterations = redis.call('hget', KEYS[1], 'hashIterations');assert(size == ARGV[1] and hashIterations == ARGV[2], 'Bloom filter config has been changed')
$1
1
$13
{test}:config
$3
958
$1
7
*3
$6
GETBIT
$4
test
$2
59
*3
$6
GETBIT
$4
test
$3
472
*3
$6
GETBIT
$4
test
$3
531
*3
$6
GETBIT
$4
test
$2
24
*3
$6
GETBIT
$4
test
$2
83
*3
$6
GETBIT
$4
test
$3
496
*3
$6
GETBIT
$4
test
$3
593

**2020-09-21 10:42:58 [redisson-netty-2-23] TRACE org.redisson.client.handler.CommandDecoder [CommandDecoder.java:116] reply: -MOVED 6918 10.38.163.58:7110**
:1
:1
:1
:1
:1
:1
:1
, channel: [id: 0x85628c0a, L:/10.221.128.67:40902 - R:/10.38.163.58:7111], command: CommandsData [commands=[CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@78340cac(incomplete)], command=(EVAL), params=[local size = redis.call('hget', KEYS[1], 'size');local hashIterations = redis.call('hget', KEYS[1], ..., 1, {test}:config, 958, 7], codec=org.redisson.client.codec.StringCodec], CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@68d55886(incomplete)], command=(GETBIT), params=[test, 59], codec=org.redisson.client.codec.LongCodec], CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@38f661b2(incomplete)], command=(GETBIT), params=[test, 472], codec=org.redisson.client.codec.LongCodec], CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@494dcc8d(incomplete)], command=(GETBIT), params=[test, 531], codec=org.redisson.client.codec.LongCodec], CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@11c4f864(incomplete)], command=(GETBIT), params=[test, 24], codec=org.redisson.client.codec.LongCodec], CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@531793b2(incomplete)], command=(GETBIT), params=[test, 83], codec=org.redisson.client.codec.LongCodec], CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@58679393(incomplete)], command=(GETBIT), params=[test, 496], codec=org.redisson.client.codec.LongCodec], CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@7f6905b6(incomplete)], command=(GETBIT), params=[test, 593], codec=org.redisson.client.codec.LongCodec]]]
2020-09-21 10:42:58 [redisson-netty-2-23] DEBUG org.redisson.command.RedisExecutor [RedisExecutor.java:632] connection released for command null and params null from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:64:queue:0, freezeReason=null, client=[addr=redis://10.38.163.58:7110], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@1134737243 [redisClient=[addr=redis://10.38.163.58:7111], channel=[id: 0x85628c0a, L:/10.221.128.67:40902 - R:/10.38.163.58:7111], currentCommand=null]

org.redisson.client.RedisMovedException
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:339)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:266)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:207)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)

**Comment by xianfengsong** [comment] 2020-09-21 02:50
test code:
        List<String> nodeSet = redisClusterNodeSet.stream().map(e -> "redis://" + e).collect(Collectors.toList());
        Config config = new Config();
        config.useClusterServers().setTimeout(10_000).addNodeAddress(nodeSet.toArray(new String[]{}));
        RedissonClient redissonClient = Redisson.create(config);
        RBloomFilter<String> bf = redissonClient.getBloomFilter("test", new StringCodec());
        boolean init = bf.tryInit(100, 0.01);
        bf.expire(24, TimeUnit.HOURS);
        bf.add("test1");
        Assert.assertTrue(bf.contains("test1"));

**Comment by xianfengsong** [comment] 2020-09-21 02:51
redis cluster nodes:
ddca63980f3c393aded90dcc78280bc5fb53d121 10.38.163.58:7100 slave b4879da1e4d1cfcbcbc01403c2d88d9b91fc8fcb 0 1600656333086 13 connected
8e99a414aee29d292a858a2cded1c7ddea150957 10.38.163.58:7120 slave f6bce91b4c81cc1b79fb6ef91e5312eb1590909c 0 1600656333786 19 connected
e9ee474e9d6c982ce9353edb9b51978c3b9f2661 10.38.163.58:7110 master - 0 1600656332786 15 connected 5461-10922
f6bce91b4c81cc1b79fb6ef91e5312eb1590909c 10.38.163.58:7121 master - 0 1600656333386 19 connected 10923-16383
4e8a03d29321d852778ce55a23d136b10e27a69b 10.38.163.58:7111 myself,slave e9ee474e9d6c982ce9353edb9b51978c3b9f2661 0 0 15 connected
b4879da1e4d1cfcbcbc01403c2d88d9b91fc8fcb 10.38.163.58:7101 master - 0 1600656331786 13 connected 0-5460

**Comment by mrniko** [comment] 2021-02-11 05:51
Fixed in https://github.com/redisson/redisson/issues/3102. Update to the latest version

**Closed by mrniko** 2021-02-11 05:51 UTC
Labels: question
