### ISSUE TITLE
Redisson 3.15.1 and 3.15.2 never release connection on redis server (replicated server configuration)

### ISSUE THREAD

**Issue by CyrilDevOps** [redisson/redisson#3518] opened 2021-03-24 18:39 UTC
**Expected behavior**
we have switched from redisson 3.15.0 to 3.15.1, and we were hit by a crazy increase of connection on our redis nodes.
our application idle at 77 connection to our redis nodes (basic replicatedserverconfig with three rediss node in aws elasticache).
our fleet of container generate total number of connexion between 200 to 500 depending on autoscaling.

**Actual behavior**
Today behavior with 3.15.1 and 3.15.2 is a crazy number of connexion, redisson never releasing the connexions,
eating all the connexions in our container (creating mess with tomcat), and generating 20k to 60k connexions on
our redis nodes.

**Steps to reproduce or test case**
Switching redisson version
3.15.0 -> 77 connexion
3.15.1 and 3.15.2 -> always increasing the number of connexion to redis
(connexion where checked with netstat -na | grep 6379 | grep EST | wc

**Redis version**
redis elasticache 6.x 6.0.5

**Redisson version**
3.15.0 ok
3.15.1 and 3.15.2 bad

**Redisson configuration**
replicatedServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: ${REDIS_PASSWORD}
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
    - "rediss://xxx.cache.amazonaws.com:6379"
    - "rediss://yyy.cache.amazonaws.com:6379"
    - "rediss://zzz.cache.amazonaws.com:6379"
  scanInterval: 1000
threads: 16
nettyThreads: 64
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"

redisson is used for spring boot cache mostly, a very simple lua script is also used for leader election.

**Comment by CyrilDevOps** [comment] 2021-03-24 18:49
Redis connexion in AWS after rollingback to 3.15.0
![Screen Shot 2021-03-24 at 2 49 15 PM](https://user-images.githubusercontent.com/36180571/112367319-23577900-8cb0-11eb-9c70-53995864f7b2.png)

**Comment by mrniko** [comment] 2021-03-25 05:15
can you share redisson logs in debug mode?

**Comment by pioneer2k** [comment] 2021-03-25 12:43
We are experiencing the same with the same versions. With 3.15.0 everything was OK.
With 3.15.1 and 3.15.2 we are experiencing that no more file descriptors are available on our server after the application is running some time. And the number of connections to the Elasticache cluster is rising.
![image](https://user-images.githubusercontent.com/32297829/112474475-f66a9b00-8d6f-11eb-89c2-1862986ae972.png)
 
 `[#|[2021-03-23 10:33:47,202] [redisson-netty-2-13] [WARN ] [] - [Failed to initialize a channel. Closing: [id: 0x32565a6a] java.io.FileNotFoundException: /tmp/rootdir/config/cacerts.jks (No file descriptors available)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
	at java.base/java.net.URL.openStream(URL.java:1140)
	at org.redisson.client.handler.RedisChannelInitializer.initSsl(RedisChannelInitializer.java:123)
	at org.redisson.client.handler.RedisChannelInitializer.initChannel(RedisChannelInitializer.java:79)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:502)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)`

**Comment by mrniko** [comment] 2021-03-25 12:58
do you see any other exceptions in logs?

**Comment by pioneer2k** [comment] 2021-03-25 13:11
Unfortunately not. The above one is the first one I see.

**Comment by mrniko** [comment] 2021-03-25 13:17
@pioneer2k can you share Redisson config?

**Comment by pioneer2k** [comment] 2021-03-25 13:23
Do you need something else? We have the same issue without SSL.

![image](https://user-images.githubusercontent.com/32297829/112479734-9e369780-8d75-11eb-9116-97b65a768d5b.png)

**Comment by mrniko** [comment] 2021-03-25 14:04
Can you try to downgrade netty to 4.1.58.Final?

**Comment by pioneer2k** [comment] 2021-03-25 14:16
How can I achieve that? We do not have netty directly integrated in our project, just as dependency by redisson.

**Comment by CyrilDevOps** [comment] 2021-03-25 14:29
We are using netty 4.1.60.Final in our project, also try to debug the DNSResolver problem with redisson/netty and AWS Elasticache hostname.

**Comment by mrniko** [comment] 2021-03-25 15:23
@pioneer2k 

Define these libs explicitly in your project:

```xml
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-common</artifactId>
            <version>4.1.58.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec</artifactId>
            <version>4.1.58.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-buffer</artifactId>
            <version>4.1.58.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport</artifactId>
            <version>4.1.58.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-resolver-dns</artifactId>
            <version>4.1.58.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>4.1.58.Final</version>
        </dependency>
``` 

and check these versions in final build.

**Comment by pioneer2k** [comment] 2021-03-25 17:40
My WAR file has now included these lib's:
![image](https://user-images.githubusercontent.com/32297829/112518105-5e81a700-8d99-11eb-9b1c-f94f4810681d.png)

The server is running now for 15 Minutes with a normal amount of connections to Elasticache. I will come back to you after some hours with new results.

**Comment by pioneer2k** [comment] 2021-03-25 19:41
@mrniko everything is running fine now for over two hours. The amount of the connections to Elasticache is in a normal range.
It seems that netty causes this issue. Maybe you should go back to 4.1.58.Final in one of the next releases of Redisson.
![image](https://user-images.githubusercontent.com/32297829/112533518-51b97f00-8daa-11eb-99a1-10dd22dedbc7.png)

**Comment by mrniko** [comment] 2021-03-26 05:07
@pioneer2k 

Do you use SSL connection? Does this issue arise with non-SSL connection as well?

**Comment by pioneer2k** [comment] 2021-03-26 08:11
@mrniko we use both and the issue arises in both variants

**Comment by mrniko** [comment] 2021-03-26 08:34
Which Redisson version did you use with 4.1.58.Final ?

**Comment by pioneer2k** [comment] 2021-03-26 08:39
3.15.2

**Comment by mrniko** [comment] 2021-03-26 08:41
@CyrilDevOps 

> also trying to debug the DNSResolver problem with redisson/netty and AWS Elasticache hostname.

Can you provide more details?

**Comment by mrniko** [comment] 2021-03-26 08:42
@CyrilDevOps 

> everything is running fine now for over two hours. The amount of the connections to Elasticache is in a normal range.
It seems that netty causes this issue.

Can you check it as well?

**Comment by pioneer2k** [comment] 2021-03-26 13:24
@mrniko I am so sorry. I have to revert everything I said about my tests with netty 4.1.58.Final. I observed the wrong environment! Unfortunately the issue is still there, even with netty 4.1.58.Final.
See the rising amount of connections until we re-deploy our application.
![image](https://user-images.githubusercontent.com/32297829/112637847-de158180-8e3e-11eb-8bf4-ac98a31679c0.png)

Any other ideas we can try?

**Comment by mrniko** [comment] 2021-03-26 14:18
Can you record session with https://jdk.java.net/jmc/8 ?

**Comment by mrniko** [comment] 2021-03-26 14:29
try to set `pingConnectionInterval = 0`

**Comment by pioneer2k** [comment] 2021-03-26 17:17
pingConnectionInterval = 0 makes no difference
I will give JMC a try on monday

**Comment by CyrilDevOps** [comment] 2021-03-26 23:11
> @CyrilDevOps
> 
> > also trying to debug the DNSResolver problem with redisson/netty and AWS Elasticache hostname.
> 
> Can you provide more details?

We have a few times a day the error in our log :
"level":"ERROR","thread":"redisson-netty-2-7","logger":"org.redisson.connection.DNSMonitor","message":"Unable to resolve xxx.cache.amazonaws.com","context":"default","exception":"io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'xxx.cache.amazonaws.com' failed to resolve 'xxx.cache.amazonaws.com .... Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.198.56.2:53] query via UDP timed out after 2000 milliseconds (no stack trace available)

Our setup is very basic, a container running in ECS on a amazon linux EC2 with no specific settings for DNS, DNS config is coming automatically by AWS with DHCP.

Our redis in elasticache is a 3 nodes replicated, and DNSMonitor failed randomly on nodes names.

Don't think it is related to this problem (we had it since before 3.15.0)

**Comment by mrniko** [comment] 2021-03-27 05:43
@CyrilDevOps

> Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.198.56.2:53] query via UDP timed out after 2000 milliseconds (no stack trace available)

The problem is in dns server

**Comment by mrniko** [comment] 2021-03-27 05:55
First of all please try version attached.

[redisson-3.15.3-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/6215180/redisson-3.15.3-SNAPSHOT.jar.zip)

**Comment by pioneer2k** [comment] 2021-03-29 12:22
@mrniko I am running 3.15.3-SNAPSHOT for half an hour now and the amount of connections is keeping stable for now.

**Comment by mrniko** [comment] 2021-03-30 05:20
Fixed

**Closed by mrniko** 2021-03-30 05:20 UTC
Labels: bug
