### ISSUE TITLE
ClientConnectionsEntry中的成员变量allConnections（Queue）中存在非常多的RedisConnection对象，内存占用非常大，无法回收，导致年老代被占满，疯狂fullgc，cpu 300%

### ISSUE THREAD

**Issue by xujunhua555** [redisson/redisson#2362] opened 2019-10-15 06:19 UTC
### Expected behavior
不会存在非常多的RedisConnection，堆内存、cpu正常
### Actual behavior
存在非常多的RedisConnection，新生代，年老代都接近100%，cpu达到300%
### Redis version
4.0.8
### Redisson version
3.10.1
### Redisson configuration
Config config = new Config();
        config.setNettyThreads(0).setThreads(0).setCodec(new JsonJacksonCodec()).setReferenceEnabled(true);
        config.useSingleServer()
                .setAddress("redis://"+"ip".concat(":").concat(String.valueOf(port)))
                .setDatabase(1)
                .setPassword("password")
                .setIdleConnectionTimeout(10000)
                .setPingConnectionInterval(30000)
                .setPingTimeout(1000)
                .setConnectTimeout(10000)
                .setTimeout(3000)
                .setRetryAttempts(3)
                .setRetryInterval(1500)
                .setSubscriptionsPerConnection(5)
                .setClientName("none")
                .setSubscriptionConnectionMinimumIdleSize(1)
                .setSubscriptionConnectionPoolSize(50)
                .setConnectionPoolSize(64)
                .setConnectionMinimumIdleSize(10)
                .setDnsMonitoringInterval(5000);
        RedissonClient redissonClient = Redisson.create(config);

**Comment by xujunhua555** [comment] 2019-10-15 06:25
sorry，Redisson Configuration describe error！！！ correct the following

config.useSentinelServers()
                .setMasterName("mymaster")
                .addSentinelAddress("redis://"+redisConfig.getSentinelHostname1().concat(":").concat(String.valueOf(redisConfig.getSentinelPort1())))
                .addSentinelAddress("redis://"+redisConfig.getSentinelHostname2().concat(":").concat(String.valueOf(redisConfig.getSentinelPort2())))
                .addSentinelAddress("redis://"+redisConfig.getSentinelHostname3().concat(":").concat(String.valueOf(redisConfig.getSentinelPort3())))
                .setDatabase(redisConfig.getDatabase())
                .setPassword(redisConfig.getPassword())
                .setIdleConnectionTimeout(10000)
                .setPingConnectionInterval(30000)
                .setPingTimeout(1000)
                .setConnectTimeout(10000)
                .setTimeout(3000)
                .setRetryAttempts(3)
                .setRetryInterval(1500)
                .setFailedSlaveReconnectionInterval(3000)
                .setFailedSlaveCheckInterval(3)
                .setSubscriptionsPerConnection(5)
                .setClientName("none")
                .setSubscriptionConnectionMinimumIdleSize(1)
                .setSubscriptionConnectionPoolSize(50)
                .setSlaveConnectionMinimumIdleSize(10)
                .setSlaveConnectionPoolSize(64)
                .setMasterConnectionMinimumIdleSize(10)
                .setMasterConnectionPoolSize(64)
                .setReadMode(ReadMode.SLAVE)
                .setSubscriptionMode(SubscriptionMode.SLAVE);

**Comment by xujunhua555** [comment] 2019-10-15 06:29
<img width="1276" alt="屏幕快照 2019-10-15 下午1 15 12" src="https://user-images.githubusercontent.com/18409916/66805673-2812ec00-ef58-11e9-84b9-083a18202a84.png">

**Comment by mrniko** [comment] 2019-10-15 06:37
This might be related to https://github.com/redisson/redisson/issues/2309

Can you try to reproduce it with 3.11.4?

**Comment by xujunhua555** [comment] 2019-10-15 07:06
> This might be related to #2309
> 
> Can you try to reproduce it with 3.11.4?

Unlike him, I am the allConnections variable in ClientConnectionsEntry with a lot of redisconnections。How do you eliminate this phenomenon in version 3.11.4? How?

**Comment by xujunhua555** [comment] 2019-10-15 07:20
> This might be related to #2309
> 
> Can you try to reproduce it with 3.11.4?

Are you sure my problem is the same as his?

**Comment by mrniko** [comment] 2019-10-15 09:54
@xujunhua555 

Can you share the memory dump, so I could realize what is the cause of memory consumption?

**Comment by mrniko** [comment] 2019-10-15 09:55
@xujunhua555 

Also can you check memory consumption by FastThreadLocalThread object?

**Comment by xujunhua555** [comment] 2019-10-15 10:22
ok，The file is too big to upload. I will send it to you in the email. Please tell me your email address

**Comment by xujunhua555** [comment] 2019-10-15 10:22
> @xujunhua555
> 
> Also can you check memory consumption by FastThreadLocalThread object?

ok，The file is too big to upload. I will send it to you in the email. Please tell me your email address

**Comment by mrniko** [comment] 2019-10-15 10:23
@xujunhua555 

Here it is yefyufudre@enayu.com

**Comment by xujunhua555** [comment] 2019-10-15 10:35
It was sent to your email

**Comment by xujunhua555** [comment] 2019-10-15 10:35
> @xujunhua555
> 
> Here it is [yefyufudre@enayu.com](mailto:yefyufudre@enayu.com)

It was sent to your email

**Comment by mrniko** [comment] 2019-10-15 10:36
@xujunhua555 

I got it. Thanks

**Comment by mrniko** [comment] 2019-10-15 10:58
@xujunhua555 

Is there any conditions for this issue? Which Redisson objects do you use?

**Comment by xujunhua555** [comment] 2019-10-15 13:38
> @xujunhua555
> 
> Is there any conditions for this issue? Which Redisson objects do you use?

In my application, the following methods are mainly called from redisson

RedissonClient redissonClient = Redisson.create(config);
RBucket rBucket = redissonClient.getBucket("bucketName");
if (rBucket.isExists()) {
        rBucket.get();
 }

**Comment by xujunhua555** [comment] 2019-10-15 14:06
> @xujunhua555
> 
> Is there any conditions for this issue? Which Redisson objects do you use?

There were some errors in that app at the time, as shown below
![WechatIMG1327](https://user-images.githubusercontent.com/18409916/66838866-09344a00-ef98-11e9-8642-cc3a58c61842.jpeg)

**Comment by mrniko** [comment] 2019-10-16 09:53
Could you try to update to the latest version? since many changes have been made since then.

**Comment by xujunhua555** [comment] 2019-10-17 02:20
> Could you try to update to the latest version? since many changes have been made since then in CommandAsyncService class

Redisson in my application has been updated to the latest version. I will watch it for a while to see if there is any problem. However, I still want to know the cause of my problem and hope to have a technical exchange

**Comment by leiyong316** [comment] 2019-10-22 11:09
@mrniko @xujunhua555 I also encountered the same problem.  redisson version 3.11.4, redis version 5.0.0.  Server cpu 300% after running for a while.

**Comment by mrniko** [comment] 2019-10-22 15:36
@leiyong316 

did you try to use 3.10.0 version?

**Comment by mrniko** [comment] 2019-10-22 15:37
@leiyong316 

Could you make thread dump during this issue?

**Comment by leiyong316** [comment] 2019-10-22 16:36
@mrniko thanks reply, but 3.10.0 not fix RedisTimeoutException

**Comment by mrniko** [comment] 2019-10-22 16:37
@leiyong316 

Please refer to this section https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

**Comment by xujunhua555** [comment] 2019-10-23 16:37
java.lang.OutOfMemoryError: Java heap space
2019-10-23 23:58:11.967 [] DEBUG i.netty.buffer.PoolThreadCache - Freed 21 thread-local buffer(s) from thread: redisson-netty-1-7
2019-10-23 23:57:06.711 [] WARN  i.n.u.c.DefaultPromise - An exception was thrown by org.redisson.client.RedisConnection$4.operationComplete()
java.lang.OutOfMemoryError: Java heap space
2019-10-23 23:56:39.444 [] WARN  i.n.u.c.DefaultPromise - An exception was thrown by org.redisson.client.RedisConnection$5.operationComplete()
java.lang.OutOfMemoryError: Java heap space
2019-10-23 23:56:40.684 [] WARN  i.n.u.c.DefaultPromise - An exception was thrown by org.redisson.client.RedisConnection$5.operationComplete()
java.lang.OutOfMemoryError: Java heap space
2019-10-23 23:49:13.103 [] WARN  i.n.u.c.SingleThreadEventExecutor - Unexpected exception from an event executor: 
java.lang.OutOfMemoryError: Java heap space

**Comment by xujunhua555** [comment] 2019-10-23 16:37
> @leiyong316
> 
> Please refer to this section https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

java.lang.OutOfMemoryError: Java heap space
2019-10-23 23:58:11.967 [] DEBUG i.netty.buffer.PoolThreadCache - Freed 21 thread-local buffer(s) from thread: redisson-netty-1-7
2019-10-23 23:57:06.711 [] WARN  i.n.u.c.DefaultPromise - An exception was thrown by org.redisson.client.RedisConnection$4.operationComplete()
java.lang.OutOfMemoryError: Java heap space
2019-10-23 23:56:39.444 [] WARN  i.n.u.c.DefaultPromise - An exception was thrown by org.redisson.client.RedisConnection$5.operationComplete()
java.lang.OutOfMemoryError: Java heap space
2019-10-23 23:56:40.684 [] WARN  i.n.u.c.DefaultPromise - An exception was thrown by org.redisson.client.RedisConnection$5.operationComplete()
java.lang.OutOfMemoryError: Java heap space
2019-10-23 23:49:13.103 [] WARN  i.n.u.c.SingleThreadEventExecutor - Unexpected exception from an event executor: 
java.lang.OutOfMemoryError: Java heap space

**Comment by mrniko** [comment] 2019-10-23 17:12
@xujunhua555 

What is the cause of OOM ?

**Comment by xujunhua555** [comment] 2019-10-24 05:45
> @xujunhua555
> 
> What is the cause of OOM ?

I don't know at the moment, but my redisson is version 3.10.1

**Comment by xujunhua555** [comment] 2019-10-24 05:46
> @xujunhua555
> 
> What is the cause of OOM ?

It is estimated that the same problem is described in the title of the issue

**Comment by MyGodIT** [comment] 2019-10-25 09:03
@xujunhua555  After update redisson to 3.11.4, Has your problem been solved？ And now I have the same problem as you. It's seem no use updating to the latest.

**Comment by leiyong316** [comment] 2019-10-28 08:10
@xujunhua555 guys, cpu 100% problem, 3.11.5 published, Have you tested this version?

**Comment by walkersing** [comment] 2019-12-20 05:02
me too

**Comment by walkersing** [comment] 2020-01-03 02:59
我用的时候，redisson 拿到每次 redisson对象后，setConfig 会把内存撑爆。是不是这个原因

**Comment by mrniko** [comment] 2020-01-03 07:03
@walkersing 

RedissonClient config settings aren't applied once client instance was created.

**Comment by empty117** [comment] 2020-02-03 06:57
@mrniko : We got similar issue in Redisson 3.10.1 in Sentinel mode.

There are ~57k elements in "org.redisson.connection.ClientConnectionEntry.allConnections" will cause OoM.

Is there any updates on this issue?

**Comment by mrniko** [comment] 2020-02-03 07:01
@empty117 

Is there any way to reproduce this?

**Comment by mrniko** [comment] 2020-02-03 07:05
@empty117 

Could you provide memory dump?

**Comment by empty117** [comment] 2020-02-03 07:12
@mrniko : Sorry not yet got reproduced. dump file is big ~300MB in zip, how to send you?

**Comment by empty117** [comment] 2020-02-03 07:45
Please get snapshot, there are ~57k elements here,

<img width="487" alt="pic" src="https://user-images.githubusercontent.com/20530797/73634454-32d6c580-469c-11ea-994a-ab3d44f288d4.png">

**Comment by mrniko** [comment] 2020-02-03 07:46
@empty117 

Through https://anonfile.com/

**Comment by empty117** [comment] 2020-02-03 08:07
@mrniko : Sorry, i checked with my teammates, cannot send dump file due to company security policy, please understand...  I can share snapshot if it helps..

**Comment by mrniko** [comment] 2020-02-03 08:09
You mean a memory snapshot?

**Comment by empty117** [comment] 2020-02-03 08:18
@mrniko : snapshot picture.

**Comment by mrniko** [comment] 2020-02-03 08:19
Was there any failover?

**Comment by empty117** [comment] 2020-02-03 08:19
No, redis is working well, no failover happens.

**Comment by mrniko** [comment] 2020-02-03 08:20
Could you share logs of SentinelConnectionManager?

**Comment by empty117** [comment] 2020-02-03 08:27
All SentinelConnectionManager logs are the same, repeat many times:

2020-01-21-T04:32:06.941-0600 | s2ossv17 | | redisson-netty-1-3 | ERROR | org.redisson.connection.SentinelConnectionManager | Can't execute SENTINEL commands on 5.135.64.141/5.135.64.141:26379

**Comment by mrniko** [comment] 2020-02-03 08:29
Are there other errors in logs?

**Comment by empty117** [comment] 2020-02-03 08:36
I can find below ones:

2020-01-21-T02:58:12.271-0600 | s2ossv17 | | redisson-netty-1-3 | ERROR | org.redisson.client.handler.CommandDecoder | Unable to decode data. reply: $770
...

java.util.concurrent.CancellationException: null
        at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263) ~[?:1.8.0_222]
        at org.redisson.misc.RedissonPromise.cancel(RedissonPromise.java:239) ~[?:?]
        at org.redisson.command.CommandAsyncService$13.run(CommandAsyncService.java:941) ~[?:?]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682) ~[?:?]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757) ~[?:?]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
2020-01-21-T02:58:12.278-0600 | s2ossv17 | | redisson-netty-1-3 | WARN  | io.netty.channel.DefaultChannelPipeline | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.util.concurrent.CancellationException
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]

2020-01-21-T02:58:27.659-0600 | s2ossv17 | | redisson-netty-1-11 | WARN  | org.redisson.client.handler.CommandDecoder | response has been skipped due to timeout!

**Comment by mrniko** [comment] 2020-02-03 09:15
"Can't execute SENTINEL commands on" leads to this memory leak fixed in https://github.com/redisson/redisson/issues/2539

Can you update to the 3.12.1 and try it again.

**Comment by empty117** [comment] 2020-02-03 10:01
Thanks, but i don't see a visible leak in sentinelConnectionManager in my dump?

![image](https://user-images.githubusercontent.com/20530797/73643828-2871f700-46af-11ea-8daf-1ec533b49059.png)

**Comment by mrniko** [comment] 2020-02-03 10:35
check nodeConnections field

**Comment by empty117** [comment] 2020-02-03 10:53
Not found, it's 3.10.1, i don't see nodeConnections in SentinelConnectionManager.

**Comment by mrniko** [comment] 2020-02-03 10:54
don't see this field at all?

**Comment by empty117** [comment] 2020-02-03 10:57
Yes, also from sourceCode, there's no such field. You can check in 3.10.1

**Comment by mrniko** [comment] 2020-02-03 11:00
Sorry, it's located in parent class - MasterSlaveConnectionManager

**Comment by empty117** [comment] 2020-02-03 11:11
Mine is normal, actually, my dump is quite similar as xujunhua555, did you have any finding in his dump file?
![image](https://user-images.githubusercontent.com/20530797/73648552-c61df400-46b8-11ea-9558-8f3137cf847e.png)

**Comment by mrniko** [comment] 2020-02-04 09:43
Think I found the cause of `ClientConnectionsEntry.allConnections`. IdleConnectionWatcher doesn't remove connection from this list when idle connection is closed.

**Comment by empty117** [comment] 2020-02-04 09:53
@mrniko : Thanks so much, great finding, any idea how to trigger/produce this issue? How to make idle connections?

**Comment by mrniko** [comment] 2020-02-04 09:56
Stop to use Redisson for more than `idleConnectionTimeout` (default is 10 seconds).

**Comment by mrniko** [comment] 2020-02-04 09:58
Fixed

**Closed by mrniko** 2020-02-04 09:58 UTC
Labels: bug

**Comment by hezhengzhou** [comment] 2020-02-04 10:15
@mrniko Thanks for fixing this issue. it's quite urgent to include this fix in our project to catch the key milestone. could you help to have a new release now ? thanks a lot!

**Comment by mrniko** [comment] 2020-02-04 10:19
I plan to make another release in a few weeks. SNAPSHOT version is attached.

[redisson-3.12.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4152653/redisson-3.12.2-SNAPSHOT.jar.zip)

**Comment by hezhengzhou** [comment] 2020-02-05 01:57
Thanks @mrniko
