### ISSUE TITLE
Password support for sentinel.conf requirepass config option

### ISSUE THREAD

**Issue by gtg469x** [redisson/redisson#2038] opened 2019-04-11 14:03 UTC
### Expected behavior
Sentinel support for authentication with password was added in Redis 5. Redisson will authenticate to Redis Sentinel's started with requirepass <password.here> in sentinel.conf.  The work around for now is to simply have the sentinel's not run in protected mode even if Redis Master/Slave instances have password requirements.  This works, however when auth is required on the sentinel nodes (as set by sentinel.conf requirepass <foo.bared.blahblahblah>) themselves, RedissonClient cannot perform commands to the sentinel nodes (Sentinel Sentinels, Sentinel Master, yada yada)

Commit adding authentication support for sentinels:  https://github.com/antirez/redis/commit/fa675256c127963c74ea68f8bab22ef105bada02

Expected behavior is that RedissonClient sends the auth with a password value that's set in a config.

### Actual behavior
Redisson does not appear to authenticate with the redis password stored in BaseConfig, and there doesn't appear to be a place to add one in the SentinelConfig.  On Spring boot application with redis password set and requirepass in sentinel.conf, startup has the following error:
```
Caused by: org.redisson.client.RedisException: NOAUTH Authentication required.. channel: [id: 0x37c4957c, L:/172.19.0.1:34720 - R:172.19.0.3/172.19.0.3:26379] command: (SENTINEL GET-MASTER-ADDR-BY-NAME), params: [masternamehereblahblahblah]
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:314)
    at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:130)
    at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:110)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
    at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce or test case
Start a Redis Master, Replica, and Sentinels all with requirepass set to some value, then attempt to get RedissonClient with SentinelServersConfig set up, setting password to whatever your password is, master name to whatever your master name is, and your nodes as appropriate.

### Redis version
5.0.4

### Redisson version
3.10.X

### Redisson configuration
```
SentinelServersConfig sentinelServersConfig = config.useSentinelServers();
            sentinelServersConfig.setMasterName(sentinelProperties.getMasterName());
            List<String> nodes = sentinelProperties.getNodes();
            String[] nodeStr = nodes.toArray(new String[nodes.size()]);
            sentinelServersConfig.addSentinelAddress(nodeStr);
            sentinelServersConfig.setReadMode(ReadMode.MASTER);
            sentinelServersConfig.setPassword(sentinelProperties.getPassword());
```
Due to sensitive nature of passwords, names etc, these will remain abstracted in my configuration snippet here.  None of these values are null, they are all set via a configuration setting.

**Comment by mrniko** [comment] 2019-04-16 07:43
Unable to reproduce it with 3.10.6 version. Could you set logging level TRACE for `org.redisson` package and share log output? Also make sure in absence of old Redisson version in classpath.

**Comment by gtg469x** [comment] 2019-04-16 12:04
Looks like it was an older Redisson version further up in my dependencies.  Didn't realize there was a conflict.  Did a test with same password for master/slave/sentinels and a test with master/slave password1 and sentinels password2, doesn't look like the second case works.  It's a low priority edge case though so if you want to close as can't repro, all good.

**Comment by mrniko** [comment] 2019-08-11 07:48
Fixed in https://github.com/redisson/redisson/issues/1981

**Closed by mrniko** 2019-08-11 07:48 UTC
