### ISSUE TITLE
connection error when Redis Cluster deployed in kubernetes fail over

### ISSUE THREAD

**Issue by LT65** [redisson/redisson#2034] opened 2019-04-10 01:04 UTC
### Expected behavior
Redisson is not able to send request to redis cluster deployed in kubernetes when master/slave are down.

### Actual behavior
Below are the exceptions caught when requests were sent to Redisson; the exceptions are alternating (i.e. I got exception #1 in one request - then got exception #2 in an other request for the same test)

1) exeception #1:

org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=32, freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, client=[addr=redis://10.244.0.65:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@223124557 [redisClient=[addr=redis://10.244.6.102:6379], channel=[id: 0x43c6edb3, L:0.0.0.0/0.0.0.0:39840], command=null], command: (GET), params: [http:device:http-gw-lan-test-6666] after 3 retry attempts
        at org.redisson.command.CommandAsyncService.checkWriteFuture(CommandAsyncService.java:873)
        at org.redisson.command.CommandAsyncService.access$000(CommandAsyncService.java:97)
        at org.redisson.command.CommandAsyncService$7.operationComplete(CommandAsyncService.java:792)
        at org.redisson.command.CommandAsyncService$7.operationComplete(CommandAsyncService.java:789)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:991)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:873)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1365)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1127)
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1174)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1098)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)

2) exception #2:
2019-04-09 23:48:59.141 ERROR 1 --- [tor-tcp-epoll-2] o.r.connection.pool.SlaveConnectionPool  : slave 10.244.6.102/10.244.6.102:6379 has been disconnected after 60000 ms interval since moment of the first failed connection
23:48:59.141 [reactor-tcp-epoll-2] ERROR o.r.c.pool.SlaveConnectionPool - slave 10.244.6.102/10.244.6.102:6379 has been disconnected after 60000 ms interval since moment of the first failed connection
org.redisson.client.RedisTimeoutException: Unable to get connection! Try to increase 'nettyThreads' and 'connection pool' settings or set decodeInExecutor = true and increase 'threads' settingNode source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=32, freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, client=[addr=redis://10.244.0.65:6379], nodeType=MASTER, firstFail=0]]], command: (GET), params: [http:device:http-gw-lan-test-8888] after 3 retry attempts
        at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
        at java.lang.Thread.run(Thread.java:748)

### Steps to reproduce or test case
Deploy redis cluster in kubernetes (3 masters: redis-cluster-0, redis-cluster-1, redis-cluster-2; 3 slaves: redis-cluster-3, redis-cluster-4, redis-cluster5)

Kill redis-cluster-0 and redis-cluster-3.  

Wait for redis-cluster-0 and redis-cluster3 to have state RUNNING and READY

Kill redis-cluster-1, redis-cluster-2, redis-cluster-4, redis-cluster-5

Send requests to see exceptions

I am using redisson reactive clien
[redisDownError-Report.txt](https://github.com/redisson/redisson/files/3061543/redisDownError-Report.txt)
t.

### Redis version
5.0.3

### Redisson version
3.10.5

### Redisson configuration
 clusterServersConfig:
      idleConnectionTimeout: 10000
      connectTimeout: 10000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500
      failedSlaveReconnectionInterval: 3000
      failedSlaveCheckInterval: 60000
      password: Redis123456
      subscriptionsPerConnection: 5
      clientName: null
      loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
      subscriptionConnectionMinimumIdleSize: 1
      subscriptionConnectionPoolSize: 50
      slaveConnectionMinimumIdleSize: 32
      slaveConnectionPoolSize: 64
      masterConnectionMinimumIdleSize: 32
      masterConnectionPoolSize: 64
      readMode: "SLAVE"
      subscriptionMode: "SLAVE"
      nodeAddresses:
      - "redis://redis-cluster:6379"
      scanInterval: 1000
      pingConnectionInterval: 10000
      keepAlive: false
      tcpNoDelay: false
    threads: 8
    nettyThreads: 16
    codec: !<org.redisson.codec.FstCodec> {}
    transportMode: "NIO"

**Comment by mrniko** [comment] 2019-04-10 05:55
According to the follow text in stacktrace `Caused by: java.nio.channels.ClosedChannelException` first issue caused by closed channel.

`slave 10.244.6.102/10.244.6.102:6379 has been disconnected after 60000 ms interval since moment of the first failed connection` - appears when Redisson detects broken connection to slave. If slave ndoe hasn't been recovered in `failedSlaveCheckInterval` time interval then Redisson disconnects this slave to avoid overall performance degradation.

Could you check your network for issues?

**Comment by LT65** [comment] 2019-04-10 14:12
There is no network issue.  The redis cluster is deployed in kubernetes hence when the nodes die and brought back up by kubernetes, the nodes will have new ip addresses, and becasue of Redisson still looking at the old ip addresses we are getting this error. We need to know if there is a solution for this problem.

IP addresses in kubernetes before the test start:
lt65@CA-00000619:~$ kubectl -n lmc-dev get pods -o wide
NAME                                                              READY   STATUS    RESTARTS   AGE     IP             NODE                       NOMINATED NODE
redis-cluster-0                                                   0/1     Running   1          4m24s   10.244.4.127   aks-agentpool-22432579-4   <none>
redis-cluster-1                                                   1/1     Running   0          34m     10.244.6.102   aks-agentpool-22432579-6   <none>
redis-cluster-2                                                   1/1     Running   0          34m     10.244.2.101   aks-agentpool-22432579-1   <none>
redis-cluster-3                                                   1/1     Running   0          40m     10.244.5.254   aks-agentpool-22432579-3   <none>
redis-cluster-4                                                   1/1     Running   0          33m     10.244.0.65    aks-agentpool-22432579-0   <none>
redis-cluster-5                                                   1/1     Running   0          32m     10.244.7.121   aks-agentpool-22432579-7   <none>

IP addresses after redis-cluster-0 and redis-cluster-3 are killed and brought back by kubernetes:
lt65@CA-00000619:~$ kubectl -n lmc-dev get pods -o wide
NAME                                                              READY   STATUS    RESTARTS   AGE     IP             NODE                       NOMINATED NODE
redis-cluster-0                                                   1/1     Running   0          2m2s    10.244.5.2     aks-agentpool-22432579-3   <none>
redis-cluster-1                                                   1/1     Running   0          42m     10.244.6.102   aks-agentpool-22432579-6   <none>
redis-cluster-2                                                   1/1     Running   0          41m     10.244.2.101   aks-agentpool-22432579-1   <none>
redis-cluster-3                                                   0/1     Running   0          35s     10.244.4.128   aks-agentpool-22432579-4   <none>
redis-cluster-4                                                   1/1     Running   0          40m     10.244.0.65    aks-agentpool-22432579-0   <none>
redis-cluster-5                                                   1/1     Running   0          40m     10.244.7.121   aks-agentpool-22432579-7   <none>

**Comment by mrniko** [comment] 2019-04-10 17:16
In this case I would recommend to monitor cluster state log output. You can observe it if you set logging level `DEBUG` for `org.redisson.cluster` package

**Comment by ekhaduk** [comment] 2019-04-11 15:12
Our redis kubernetes setup consists of three masters and three slaves. The problem starts happening when at least two masters are killed.  However, it is fine when we kill two slaves. Please check the log attached for more details.
[redisson-killed-two-masters.txt](https://github.com/redisson/redisson/files/3069304/redisson-killed-two-masters.txt)

**Comment by mrniko** [comment] 2019-04-12 05:55
Interesting 10.0.230.94 reports cluster state but not in cluster. Let me clarify, did you set single host name resolving single IP as nodeAddresses ?

**Comment by ekhaduk** [comment] 2019-04-12 11:33
Becasue the Pods (redis instances) in a kubernetes Deployment come and go, and their IP addresses change. We used kubernetes Service in front of them, which give us a stable IP address that lasts for the life of the Service, even as the IP addresses of the member Pods change.
This Service provides load balancing. Clients call the service, and their requests are balanced across the redis instances that are members of the Service.
in the redisson configuration we had the service host name as nodeAddresses.
nodeAddresses:
      - "redis://redis-cluster:6379"
{"@timestamp":"2019-04-12T11:27:44.248+00:00","@version":"1","message":"Redis cluster nodes configuration got from redis-cluster/10.0.230.94:6379:\ncd5fee46618fcde3bfe83ec809e41fa082419933 10.244.2.125:6379@16379 slave 3e0b9c101fe9b4897d337b60b1f89da67cd97b5e 0 1555068462000 47 connected\n61e5fafc621f4209041487471446fd87349c5424 10.244.0.86:6379@16379 slave cd231a96283a98d77e29e0f1ae15dfc756254937 0 1555068463599 40 connected\n3e0b9c101fe9b4897d337b60b1f89da67cd97b5e 10.244.6.141:6379@16379 master - 0 1555068463700 47 connected 0-5460\n5744bd7d242e9def46c6a8008aa03a2466dee878 10.244.5.24:6379@16379 master - 0 1555068462697 48 connected 10923-16383\n23035b9f350003e4ebe11d4b03bbaefddc4501ff 10.244.7.134:6379@16379 myself,slave 5744bd7d242e9def46c6a8008aa03a2466dee878 0 1555068463000 45 connected\ncd231a96283a98d77e29e0f1ae15dfc756254937 10.244.4.141:6379@16379 master - 0 1555068463599 40 connected 5461-10922\n","logger_name":"org.redisson.cluster.ClusterConnectionManager","thread_name":"main","level":"INFO","level_value":20000,"caller_class_name":"org.redisson.cluster.ClusterConnectionManager","caller_method_name":"<init>","caller_file_name":"ClusterConnectionManager.java","caller_line_number":125}

**Comment by mrniko** [comment] 2019-04-15 09:26
ClusterConnectionManager doesn't report anything since `14:54:05` though it should log an error:

1. https://github.com/redisson/redisson/blob/bbe40d02ef24ce75fb364e10eaa304a3a6a4c0b3/redisson/src/main/java/org/redisson/cluster/ClusterConnectionManager.java#L290

2. https://github.com/redisson/redisson/blob/bbe40d02ef24ce75fb364e10eaa304a3a6a4c0b3/redisson/src/main/java/org/redisson/cluster/ClusterConnectionManager.java#L337

3.
https://github.com/redisson/redisson/blob/bbe40d02ef24ce75fb364e10eaa304a3a6a4c0b3/redisson/src/main/java/org/redisson/cluster/ClusterConnectionManager.java#L351

**Closed** 2019-08-15 08:54 UTC

**Comment by eladtamary** [comment] 2020-07-09 22:47
Seems to be related to: https://github.com/redisson/redisson/issues/2839
I also got this issue in Redisson version: 3.11.0.
Upgrading to 3.13.2 fixed it.
