### ISSUE TITLE
Thread hangs 6days in redisson await by get() until the thread interrupt

### ISSUE THREAD

**Issue by huangshaobb** [redisson/redisson#5773] opened 2024-04-11 13:17 UTC
org.springframework.dao.InvalidDataAccessApiUsageException: java.lang.InterruptedException; nested exception is org.redisson.client.RedisException: java.lang.InterruptedException
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:52)
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:228)
	at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:223)
	at org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:389)
	at com.lingzhi.retail.dubhe.redis.component.CountFailRedissonConnectionFactoryProxy$CountFailRedissonClusterConnectionProxy.lambda$sync$0(CountFailRedissonConnectionFactoryProxy.java:83)
	at com.lingzhi.retail.dubhe.redis.component.CountFailRedissonConnectionFactoryProxy.handleException(CountFailRedissonConnectionFactoryProxy.java:43)
	at com.lingzhi.retail.dubhe.redis.component.CountFailRedissonConnectionFactoryProxy.access$000(CountFailRedissonConnectionFactoryProxy.java:23)
	at com.lingzhi.retail.dubhe.redis.component.CountFailRedissonConnectionFactoryProxy$CountFailRedissonClusterConnectionProxy.sync(CountFailRedissonConnectionFactoryProxy.java:83)
	at org.redisson.spring.data.connection.RedissonConnection.read(RedissonConnection.java:770)
	at org.redisson.spring.data.connection.RedissonConnection.get(RedissonConnection.java:504)
	at org.springframework.data.redis.connection.DefaultStringRedisConnection.get(DefaultStringRedisConnection.java:377)
	at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:57)
	at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:59)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95)
	at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:53)
	at com.lingzhi.retail.app.service.decoration.RedisUtils.get(RedisUtils.java:54)
	at com.lingzhi.retail.app.service.decoration.RedisUtils.get(RedisUtils.java:75)
	at com.lingzhi.retail.app.service.decoration.impl.DecorationModuleProductServiceImpl.fetchModule(DecorationModuleProductServiceImpl.java:142)
	at com.lingzhi.retail.app.service.decoration.impl.DecorationServiceImpl.lambda$null$1(DecorationServiceImpl.java:316)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at org.springframework.cloud.sleuth.instrument.async.TraceRunnable.run(TraceRunnable.java:65)
	at com.lingzhi.retail.dubhe.thread.DubheDecorator.lambda$decorate$0(DubheDecorator.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisException: java.lang.InterruptedException
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:115)
	at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:221)
	... 24 common frames omitted
Caused by: java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:218)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:110)
	at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:35)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:112)
	... 25 common frames omitted

redisson version : 3.15.2

**Comment by huangshaobb** [comment] 2024-04-11 13:18
help!!

**Comment by huangshaobb** [comment] 2024-04-11 13:35
> what is the Redisson config? can you share Redisson logs? did Redis failover happen?

just have some relative logs, when error happen,  but if throws error, its no hangs

config
timeout:5000
max-redirects:3
other config by default~

2024-04-04 16:02:29,912 ERROR [redisson-healthDetector] [com.lingzhi.retail.dubhe.redis.component.CountFailRedissonProxy:158] -   - ***:{class org.redisson.client.WriteRedisConnectionException=[org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=11760, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1672465010 [redisClient=[addr=redis://192.2.33.25:7502], channel=[id: 0xa8416ea4, L:/192.2.82.34:46118 ! R:/192.2.33.25:7502], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@7721d0d7(failure: java.util.concurrent.CancellationException)], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (GET), params: [[53, 48, 51]] after 3 retry attempts, org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=12202, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@2104419738 [redisClient=[addr=redis://192.2.33.25:7502], channel=[id: 0xab68ceb8, L:/192.2.82.34:46140 ! R:/192.2.33.25:7502], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@42b5d5b(failure: java.util.concurrent.CancellationException)], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (GET), params: [[53, 49, 56]] after 3 retry attempts], class org.redisson.client.RedisTimeoutException=[org.redisson.client.RedisTimeoutException: Unable to acquire connection! RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@42e6679b(failure: java.util.concurrent.CancellationException)]Increase connection pool size. Node source: NodeSource [slot=13135, addr=null, redisClient=null, redirect=null, entry=null], command: (GET), params: [[53, 53, 57]] after 0 retry attempts]}

**Comment by huangshaobb** [comment] 2024-04-11 13:35
> what is the Redisson config? can you share Redisson logs? did Redis failover happen?

we use redis cluster

**Comment by huangshaobb** [comment] 2024-04-11 13:38
> failover

we have 4 pods, just happen in one pod. we have 20 thread pool size, 17 thread hangs~ until pod restart

**Comment by mrniko** [comment] 2024-04-11 14:14
Do you use Spring Data Redis only or RedissonClient methods as well?

**Comment by huangshaobb** [comment] 2024-04-12 02:03
> Do you use Spring Data Redis only or RedissonClient methods as well?

user spring data redis api, connect is redisson

**Comment by huangshaobb** [comment] 2024-04-12 03:00
> Redis failover happen

![17128905339935](https://github.com/redisson/redisson/assets/9313190/d2e2ce63-eea1-4729-af56-64b9a2c26062)

**Comment by mrniko** [comment] 2024-04-12 04:41
method invocation hangs after failover was fixed in 3.25.1 version. Can you try it?

**Comment by huangshaobb** [comment] 2024-04-12 05:01
> method invocation hangs after failover was fixed in 3.25.1 version. Can you try it? 3.25.2 is better

ok, Could you explain the general reason

**Comment by huangshaobb** [comment] 2024-04-12 05:06
> method invocation hangs after failover was fixed in 3.25.1 version. Can you try it? 3.25.2 is better

Fixed - method invocation hangs after failover if retryInterval = 0, means config  retryInterval = 0 happend ?

**Comment by mrniko** [comment] 2024-04-12 05:45
yes

**Comment by huangshaobb** [comment] 2024-04-12 07:30
> yes

but our config retry_interval=1500

private int retryAttempts = 3;
private int retryInterval = 1500;

**Comment by mrniko** [comment] 2024-04-12 07:37
which Redisson Spring data redis module used?

**Comment by mrniko** [comment] 2024-04-13 18:05
there are many fixes of failover issues between 3.15.2 and 3.25.2 version. Fix of which may fix this one as well. I can't reproduce it.

**Comment by huangshaobb** [comment] 2024-04-18 10:26
If I upgrade directly from 3.15.2 to 3.25.2, will there be any new risks due to the large version gap?

**Comment by mrniko** [comment] 2024-04-18 11:10
You need to review breaking changes in https://github.com/redisson/redisson/blob/master/CHANGELOG.md

**Closed** 2024-05-01 06:53 UTC
Labels: question
