### ISSUE TITLE
Spring boot Redisson client: Exception while unlocking a lock, attempt to unlock lock, not locked by current thread

### ISSUE THREAD

**Issue by abhisekharh1988** [redisson/redisson#5000] opened 2023-04-28 10:49 UTC
We are using the below dependency - 
**implementation 'org.redisson:redisson:3.17.7'**
**Spring boot version: 2.7.2**

### Code snippet
```
String lockName = lockHelper.getLockName("lock_name");
RLock lock = redisson.getLock(lockName);
boolean isLockAvailable = lock.tryLock(30, 120, TimeUnit.SECONDS);
if (isLockAvailable) {
    try {
        //do some work
    }
    catch (Exception ex) {
        log.error("Failed to process", ex);
    }
    finally {
        if(lock.isLocked() && lock.isHeldByCurrentThread()) {
            lock.unlock();
        }
    }
}
```

We are still getting the below exception though we have put the safe guard: **_lock.isLocked() && lock.isHeldByCurrentThread()_** -
`java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: c83ab765-ddca-42d0-9890-f465ccfe41d3 thread-id: 1`

Could you please let me know how can we avoid this exception?

**Comment by andreas-ajaib** [comment] 2023-06-20 02:09
I am wondering the same. I am getting similar exception on my code base.

**Comment by mrniko** [comment] 2023-06-20 05:07
unable to reproduce. Can you set `trace` logging level for `org.redisson` package and share output?

**Comment by Mars-Shen** [comment] 2023-09-01 12:56
any update? I got  similar exception on prod

**Comment by mrniko** [comment] 2023-09-04 12:22
@Mars-Shen 

Are there any logs or code to reproduce it?

**Comment by 929775875** [comment] 2023-09-04 13:26
The same problem was encountered when using thread pools，Same code as the owner

**Comment by Mars-Shen** [comment] 2023-09-04 13:43
> @Mars-Shen
> 
> Are there any logs or code to reproduce it?

Almost same code as the owner, use springboot 2.6 and redission version 3.17.0, and also use `lock.isLocked() && lock.isHeldByCurrentThread()` before unlock()

got the error stack, not sure if is helpful
```
[{
	"className": "org.redisson.RedissonBaseLock",
	"fileName": "RedissonBaseLock.java",
	"lineNumber": 329,
	"methodName": "lambda$unlockAsync$2",
	"nativeMethod": false
}, {
	"className": "java.util.concurrent.CompletableFuture",
	"fileName": "CompletableFuture.java",
	"lineNumber": 822,
	"methodName": "uniHandle",
	"nativeMethod": false
}, {
	"className": "java.util.concurrent.CompletableFuture$UniHandle",
	"fileName": "CompletableFuture.java",
	"lineNumber": 797,
	"methodName": "tryFire",
	"nativeMethod": false
}, {
	"className": "java.util.concurrent.CompletableFuture",
	"fileName": "CompletableFuture.java",
	"lineNumber": 474,
	"methodName": "postComplete",
	"nativeMethod": false
}, {
	"className": "java.util.concurrent.CompletableFuture",
	"fileName": "CompletableFuture.java",
	"lineNumber": 1962,
	"methodName": "complete",
	"nativeMethod": false
}, {
	"className": "org.redisson.misc.RedissonPromise",
	"fileName": "RedissonPromise.java",
	"lineNumber": 83,
	"methodName": "trySuccess",
	"nativeMethod": false
}, {
	"className": "org.redisson.command.CommandBatchService",
	"fileName": "CommandBatchService.java",
	"lineNumber": 324,
	"methodName": "lambda$executeAsync$7",
	"nativeMethod": false
}, {
	"className": "java.util.concurrent.CompletableFuture",
	"fileName": "CompletableFuture.java",
	"lineNumber": 760,
	"methodName": "uniWhenComplete",
	"nativeMethod": false
}, {
	"className": "java.util.concurrent.CompletableFuture$UniWhenComplete",
	"fileName": "CompletableFuture.java",
	"lineNumber": 736,
	"methodName": "tryFire",
	"nativeMethod": false
}, {
	"className": "java.util.concurrent.CompletableFuture",
	"fileName": "CompletableFuture.java",
	"lineNumber": 474,
	"methodName": "postComplete",
	"nativeMethod": false
}, {
	"className": "java.util.concurrent.CompletableFuture",
	"fileName": "CompletableFuture.java",
	"lineNumber": 1962,
	"methodName": "complete",
	"nativeMethod": false
}, {
	"className": "org.redisson.command.RedisCommonBatchExecutor",
	"fileName": "RedisCommonBatchExecutor.java",
	"lineNumber": 162,
	"methodName": "handleResult",
	"nativeMethod": false
}, {
	"className": "org.redisson.command.RedisExecutor",
	"fileName": "RedisExecutor.java",
	"lineNumber": 476,
	"methodName": "checkAttemptPromise",
	"nativeMethod": false
}, {
	"className": "org.redisson.command.RedisExecutor",
	"fileName": "RedisExecutor.java",
	"lineNumber": 172,
	"methodName": "lambda$execute$3",
	"nativeMethod": false
}, {
	"className": "java.util.concurrent.CompletableFuture",
	"fileName": "CompletableFuture.java",
	"lineNumber": 760,
	"methodName": "uniWhenComplete",
	"nativeMethod": false
}, {
	"className": "java.util.concurrent.CompletableFuture$UniWhenComplete",
	"fileName": "CompletableFuture.java",
	"lineNumber": 736,
	"methodName": "tryFire",
	"nativeMethod": false
}, {
	"className": "java.util.concurrent.CompletableFuture",
	"fileName": "CompletableFuture.java",
	"lineNumber": 474,
	"methodName": "postComplete",
	"nativeMethod": false
}, {
	"className": "java.util.concurrent.CompletableFuture",
	"fileName": "CompletableFuture.java",
	"lineNumber": 1962,
	"methodName": "complete",
	"nativeMethod": false
}, {
	"className": "org.redisson.client.handler.CommandDecoder",
	"fileName": "CommandDecoder.java",
	"lineNumber": 318,
	"methodName": "decodeCommandBatch",
	"nativeMethod": false
}, {
	"className": "org.redisson.client.handler.CommandDecoder",
	"fileName": "CommandDecoder.java",
	"lineNumber": 210,
	"methodName": "decodeCommand",
	"nativeMethod": false
}, {
	"className": "org.redisson.client.handler.CommandDecoder",
	"fileName": "CommandDecoder.java",
	"lineNumber": 137,
	"methodName": "decode",
	"nativeMethod": false
}, {
	"className": "org.redisson.client.handler.CommandDecoder",
	"fileName": "CommandDecoder.java",
	"lineNumber": 113,
	"methodName": "decode",
	"nativeMethod": false
}, {
	"className": "io.netty.handler.codec.ByteToMessageDecoder",
	"fileName": "ByteToMessageDecoder.java",
	"lineNumber": 510,
	"methodName": "decodeRemovalReentryProtection",
	"nativeMethod": false
}, {
	"className": "io.netty.handler.codec.ReplayingDecoder",
	"fileName": "ReplayingDecoder.java",
	"lineNumber": 366,
	"methodName": "callDecode",
	"nativeMethod": false
}, {
	"className": "io.netty.handler.codec.ByteToMessageDecoder",
	"fileName": "ByteToMessageDecoder.java",
	"lineNumber": 279,
	"methodName": "channelRead",
	"nativeMethod": false
}, {
	"className": "io.netty.channel.AbstractChannelHandlerContext",
	"fileName": "AbstractChannelHandlerContext.java",
	"lineNumber": 379,
	"methodName": "invokeChannelRead",
	"nativeMethod": false
}, {
	"className": "io.netty.channel.AbstractChannelHandlerContext",
	"fileName": "AbstractChannelHandlerContext.java",
	"lineNumber": 365,
	"methodName": "invokeChannelRead",
	"nativeMethod": false
}, {
	"className": "io.netty.channel.AbstractChannelHandlerContext",
	"fileName": "AbstractChannelHandlerContext.java",
	"lineNumber": 357,
	"methodName": "fireChannelRead",
	"nativeMethod": false
}, {
	"className": "io.netty.channel.DefaultChannelPipeline$HeadContext",
	"fileName": "DefaultChannelPipeline.java",
	"lineNumber": 1410,
	"methodName": "channelRead",
	"nativeMethod": false
}, {
	"className": "io.netty.channel.AbstractChannelHandlerContext",
	"fileName": "AbstractChannelHandlerContext.java",
	"lineNumber": 379,
	"methodName": "invokeChannelRead",
	"nativeMethod": false
}, {
	"className": "io.netty.channel.AbstractChannelHandlerContext",
	"fileName": "AbstractChannelHandlerContext.java",
	"lineNumber": 365,
	"methodName": "invokeChannelRead",
	"nativeMethod": false
}, {
	"className": "io.netty.channel.DefaultChannelPipeline",
	"fileName": "DefaultChannelPipeline.java",
	"lineNumber": 919,
	"methodName": "fireChannelRead",
	"nativeMethod": false
}, {
	"className": "io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe",
	"fileName": "AbstractNioByteChannel.java",
	"lineNumber": 166,
	"methodName": "read",
	"nativeMethod": false
}, {
	"className": "io.netty.channel.nio.NioEventLoop",
	"fileName": "NioEventLoop.java",
	"lineNumber": 722,
	"methodName": "processSelectedKey",
	"nativeMethod": false
}, {
	"className": "io.netty.channel.nio.NioEventLoop",
	"fileName": "NioEventLoop.java",
	"lineNumber": 658,
	"methodName": "processSelectedKeysOptimized",
	"nativeMethod": false
}, {
	"className": "io.netty.channel.nio.NioEventLoop",
	"fileName": "NioEventLoop.java",
	"lineNumber": 584,
	"methodName": "processSelectedKeys",
	"nativeMethod": false
}, {
	"className": "io.netty.channel.nio.NioEventLoop",
	"fileName": "NioEventLoop.java",
	"lineNumber": 496,
	"methodName": "run",
	"nativeMethod": false
}, {
	"className": "io.netty.util.concurrent.SingleThreadEventExecutor$4",
	"fileName": "SingleThreadEventExecutor.java",
	"lineNumber": 986,
	"methodName": "run",
	"nativeMethod": false
}, {
	"className": "io.netty.util.internal.ThreadExecutorMap$2",
	"fileName": "ThreadExecutorMap.java",
	"lineNumber": 74,
	"methodName": "run",
	"nativeMethod": false
}, {
	"className": "io.netty.util.concurrent.FastThreadLocalRunnable",
	"fileName": "FastThreadLocalRunnable.java",
	"lineNumber": 30,
	"methodName": "run",
	"nativeMethod": false
}, {
	"className": "java.lang.Thread",
	"fileName": "Thread.java",
	"lineNumber": 748,
	"methodName": "run",
	"nativeMethod": false
}]
```

**Comment by mrniko** [comment] 2023-09-04 17:32
Did you try to increase leaseTime parameter?

**Comment by 929775875** [comment] 2023-09-15 02:05
Is there a way to solve this problem, the use of the thread pool occurs, but also leads to deadlocks, watchdogs keep renewing, fatal problems

**Comment by mrniko** [comment] 2023-09-15 05:58
@929775875 

Is there any code example to reproduce it?

**Comment by mrniko** [comment] 2023-09-27 13:03
Fixed in https://github.com/redisson/redisson/issues/4871

**Closed by mrniko** 2023-09-27 13:03 UTC
Labels: question, lock
