### ISSUE TITLE
Thread ends up stuck when redis command is sent while the redisson client is disconnected from the redis cluster 

### ISSUE THREAD

**Issue by fkolberg-verint** [redisson/redisson#4723] opened 2022-12-07 10:45 UTC
**Expected behavior**
redisson should throw an exception that the command was not successful, and earlier than when the redisson client gets reconnected to the redis cluster

**Actual behavior**
the thread hangs and gets stuck

**Steps to reproduce or test case**
a blackhole attack is started to block all traffic to and from a redis cluster (Elasticache on AWS version 6.2.6), and lasts for three minutes.
the log is as follow, in this example, the attack started at 9:51:10 until 9:54:10 (Gremlin is used to run the attack)
caches are instances of RLocalCachedMap

[2022-12-07 09:51:28.761+0000] ExecuteThread: '16' [org.redisson.cluster.ClusterConnectionManager]  slot 71 for A90:witness/usermanager
[2022-12-07 09:51:28.761+0000] ExecuteThread: '16' [org.redisson.command.RedisExecutor] acquired connection for command (EVAL) and params [if ARGV[4] == '1' then redis.call('publish', KEYS[2], ARGV[3]); end;if ARGV[4] == '2' then redis.call('zadd', KEYS[3], ARGV[5], ARGV[6]);redis.call('publish', KEYS[2], ARGV[3]); end;if redis.call('hset', KEYS[1], ARGV[1], ARGV[2]) == 0 then return 0; end; return 1; , 3, A90:witness/usermanager, {A90:witness/usermanager}:topic, redisson__cache_updates_log:{A90:witness/usermanager}, PooledUnsafeDirectByteBuf(ridx: 0, widx: 19, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 318, cap: 512), PooledUnsafeDirectByteBuf(ridx: 0, widx: 37, cap: 256), 1, 1670406688761, ...] from slot NodeSource [slot=71, addr=null, redisClient=null, redirect=null, entry=null] using node 10.x.x.x/10.x.x.x:6379... RedisConnection@1466869015 [redisClient=[addr=rediss://10.x.x.x:6379], channel=[id: 0x537b5bf6, L:/10.x.x.x:53709 - R:10.x.x.x/10.x.x.x:6379], currentCommand=null, usage=1]
[2022-12-07 09:51:36.538+0000] -- the Redis connection listener gets onDisconnect from the redis node 10.x.x.x
[2022-12-07 09:51:47.693+0000] [redisson-timer-4-1] [org.redisson.client.handler.ConnectionWatchdog] reconnecting RedisConnection@1466869015 [redisClient=[addr=rediss://10.x.x.x:6379], channel=[id: 0x537b5bf6, L:/10.x.x.x:53709 ! R:10.x.x.x/10.x.x.x:6379], currentCommand=null, usage=1] to 10.x.x.x/10.x.x.x:6379 -- that is the first occurrence of this message
[2022-12-07 09:54:12.995+0000] [redisson-timer-4-1] -- last occurence of the message reconnecting...
[2022-12-07 09:54:10.914+0000] -- the Redis connection listener gets onConnect to the redis node 10.x.x.x
[2022-12-07 09:54:13.007+0000] [redisson-netty-2-3] [org.redisson.client.handler.ConnectionWatchdog] RedisConnection@1466869015 [redisClient=[addr=rediss://10.x.x.x:6379], channel=[id: 0x537b5bf6, L:/10.x.x.x:53709 ! R:10.x.x.x/10.x.x.x:6379], currentCommand=null, usage=1] connected to 10.x.x.x/10.x.x.x:6379, command: null

ExecuteThread: '16' is hogged and get eventually stuck.
note that the command for RedisConnection@1466869015 is null also, and we only got an onDisconnect at 9:51:36, while the attack started at 9:51:10

Are there any configs that would help triggering an exception for commands sent when the client is disconnected from the remote cache? 
What config relates to the notification of a disconnection/connection from redisson to redis?

**Redis version**
Elasticache on AWS version 6.2.6

**Redisson version**
3.18.1
netty jars used are of version 4.1.79.Final

**Redisson configuration**
useClusterServers()
setRetryAttempts(1)
everything else are defaults

**Comment by fkolberg-verint** [comment] 2022-12-09 15:36
that is the extract of a stuck thread:
            "[STUCK] ExecuteThread: '26' for queue: 'weblogic.kernel.Default (self-tuning)'" #90 daemon prio=1 os_prio=-2 tid=0x0000000042d2e800 nid=0xa5c waiting on condition [0x0000000046abb000]
          
               java.lang.Thread.State: WAITING (parking)
          
            	at sun.misc.Unsafe.park(Native Method)
          
            	- parking to wait for  <0x00000007a40a4d90> (a java.util.concurrent.CompletableFuture$Signaller)
          
            	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
          
            	at java.util.concurrent.CompletableFuture$Signaller.block(Unknown Source)
          
            	at java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
          
            	at java.util.concurrent.CompletableFuture.waitingGet(Unknown Source)
          
            	at java.util.concurrent.CompletableFuture.get(Unknown Source)
          
            	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:109)
          
            	at org.redisson.RedissonObject.get(RedissonObject.java:82)

in RedisExecutor, we get to
 writeFuture = connection.send(new CommandData<>(attemptPromise, codec, command, params));
but the attemptPromise never seems to complete

**Comment by fkolberg-verint** [comment] 2022-12-13 09:05
@mrniko I think there maybe a mistake in one method:

` @Override
    public void channelInactive(ChannelHandlerContext ctx) throws Exception {
        Queue<QueueCommandHolder> queue = ctx.channel().attr(COMMANDS_QUEUE).get();
        Iterator<QueueCommandHolder> iterator = queue.iterator();
        while (iterator.hasNext()) {
            QueueCommandHolder command = iterator.next();
            if (command.getCommand().isBlockingCommand()) {
                continue;
            }

            iterator.remove();
            command.getChannelPromise().tryFailure(
                    new WriteRedisConnectionException("Channel has been closed! Can't write command: "
                                + LogHelper.toString(command.getCommand()) + " to channel: " + ctx.channel()));
        }

        super.channelInactive(ctx);
    }`

I think command.getChannelPromise().tryFailure should instead be command.getCommand().tryFailure as it is the command's attemptPromise we are trying to complete

**Comment by mrniko** [comment] 2022-12-13 13:53
> while the redisson client was not connected to the redis cluster, the command will never be executed and the promise never completed

Is there any code to reproduce it?

**Comment by fkolberg-verint** [comment] 2022-12-19 12:37
@mrniko I am having difficulties creating a simple program that would recreate the situation I am getting in the application,in which the connection does not get released.
Could you give me some pointers and tell me if I am making the wrong assumptions?

One of the application servers is disconnected from the redis cluster (two nodes).
An example of redis command being sent while the server is disconnected from the redis cluster is like this: (I changed the debug log messages so I could see more details about the connection and command sent)

####[ProductionServer]-[] [2022-12-16 16:00:05.203+0000] [DEBUG] [[ACTIVE] ExecuteThread: '20' for queue: 'weblogic.kernel.Default (self-tuning)'] [org.redisson.cluster.ClusterConnectionManager] <##[{user=mst-scheduler-05}]##> - slot 14399 for A90:witness/uif/sessionAttributes
####[ProductionServer]-[] [2022-12-16 16:00:05.203+0000] [DEBUG] [[ACTIVE] ExecuteThread: '20' for queue: 'weblogic.kernel.Default (self-tuning)'] [org.redisson.command.RedisExecutor] <##[{user=mst-scheduler-05}]##> - acquired connection for command (INFO REPLICATION) and params [] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:44:queue:0, freeConnectionsAmount=21, freeConnectionsCounter=value:61:queue:0, freezeReason=null, client=[addr=rediss://10.50.71.120:6379], nodeType=MASTER, firstFail=0]]] using node 10.50.71.120/10.50.71.120:6379... RedisConnection@2124380504 [redisClient=[addr=rediss://10.50.71.120:6379], channel=[id: 0xb9b538ba, L:/10.50.71.96:62447 - R:10.50.71.120/10.50.71.120:6379], currentCommand=null, usage=1]
####[ProductionServer]-[] [2022-12-16 16:00:05.203+0000] [DEBUG] [[ACTIVE] ExecuteThread: '20' for queue: 'weblogic.kernel.Default (self-tuning)'] [org.redisson.command.RedisExecutor] <##[{user=mst-scheduler-05}]##> - sendCommand: attemptPromise java.util.concurrent.CompletableFuture@7593062f[Not completed], connection RedisConnection@2124380504 [redisClient=[addr=rediss://10.50.71.120:6379], channel=[id: 0xb9b538ba, L:/10.50.71.96:62447 - R:10.50.71.120/10.50.71.120:6379], currentCommand=null, usage=1]
####[ProductionServer]-[] [2022-12-16 16:00:05.203+0000] [DEBUG] [redisson-netty-2-4] [org.redisson.client.handler.CommandsQueue] <##   ##> - write - command CommandData [promise=java.util.concurrent.CompletableFuture@7593062f[Not completed], command=(INFO REPLICATION), params=[], codec=null], channel [id: 0xb9b538ba, L:/10.50.71.96:62447 - R:10.50.71.120/10.50.71.120:6379], channel promise DefaultChannelPromise@5d1024ca(incomplete)
####[ProductionServer]-[common] [2022-12-16 16:00:24.115+0000] [INFO] [redisson-netty-2-4] [com.bluepumpkin.common.cache.redis.RedisConnectionListener] <##   ##> - Disconnecting from: hostString= 10.50.71.120, client: redisson-34288@APP1-A62-USE1
####[ProductionServer]-[] [2022-12-16 16:00:24.115+0000] [DEBUG] [redisson-netty-2-4] [org.redisson.client.handler.ConnectionWatchdog] <##   ##> - channelInactive [id: 0xb9b538ba, L:/10.50.71.96:62447 ! R:10.50.71.120/10.50.71.120:6379], connection RedisConnection@2124380504 [redisClient=[addr=rediss://10.50.71.120:6379], channel=[id: 0xb9b538ba, L:/10.50.71.96:62447 ! R:10.50.71.120/10.50.71.120:6379], currentCommand=CommandData [promise=java.util.concurrent.CompletableFuture@7593062f[Not completed, 1 dependents], command=(INFO REPLICATION), params=[], codec=null], usage=1]
####[ProductionServer]-[] [2022-12-16 16:00:24.116+0000] [DEBUG] [redisson-netty-2-4] [org.redisson.client.handler.CommandsQueue] <##   ##> - channelInactive [id: 0xb9b538ba, L:/10.50.71.96:62447 ! R:10.50.71.120/10.50.71.120:6379], queue size 1
####[ProductionServer]-[] [2022-12-16 16:00:24.116+0000] [DEBUG] [redisson-netty-2-4] [org.redisson.client.handler.CommandsQueue] <##   ##> - non-blocking command - removing CommandData [promise=java.util.concurrent.CompletableFuture@7593062f[Not completed, 1 dependents], command=(INFO REPLICATION), params=[], codec=null]
####[ProductionServer]-[] [2022-12-16 16:00:24.209+0000] [DEBUG] [redisson-timer-4-1] [org.redisson.client.handler.ConnectionWatchdog] <##   ##> - reconnecting RedisConnection@2124380504 [redisClient=[addr=rediss://10.50.71.120:6379], channel=[id: 0xb9b538ba, L:/10.50.71.96:62447 ! R:10.50.71.120/10.50.71.120:6379], currentCommand=null, usage=1] to 10.50.71.120/10.50.71.120:6379
####[ProductionServer]-[] [2022-12-16 16:00:34.310+0000] [DEBUG] [redisson-timer-4-1] [org.redisson.client.handler.ConnectionWatchdog] <##   ##> - reconnecting RedisConnection@2124380504 [redisClient=[addr=rediss://10.50.71.120:6379], channel=[id: 0xb9b538ba, L:/10.50.71.96:62447 ! R:10.50.71.120/10.50.71.120:6379], currentCommand=null, usage=1] to 10.50.71.120/10.50.71.120:6379 
####[ProductionServer]-[] [2022-12-16 16:00:44.410+0000] [DEBUG] [redisson-timer-4-1] [org.redisson.client.handler.ConnectionWatchdog] <##   ##> - reconnecting RedisConnection@2124380504 [redisClient=[addr=rediss://10.50.71.120:6379], channel=[id: 0xb9b538ba, L:/10.50.71.96:62447 ! R:10.50.71.120/10.50.71.120:6379], currentCommand=null, usage=1] to 10.50.71.120/10.50.71.120:6379 
####[ProductionServer]-[] [2022-12-16 16:00:54.509+0000] [DEBUG] [redisson-timer-4-1] [org.redisson.client.handler.ConnectionWatchdog] <##   ##> - reconnecting RedisConnection@2124380504 [redisClient=[addr=rediss://10.50.71.120:6379], channel=[id: 0xb9b538ba, L:/10.50.71.96:62447 ! R:10.50.71.120/10.50.71.120:6379], currentCommand=null, usage=1] to 10.50.71.120/10.50.71.120:6379 
####[ProductionServer]-[] [2022-12-16 16:01:04.610+0000] [DEBUG] [redisson-timer-4-1] [org.redisson.client.handler.ConnectionWatchdog] <##   ##> - reconnecting RedisConnection@2124380504 [redisClient=[addr=rediss://10.50.71.120:6379], channel=[id: 0xb9b538ba, L:/10.50.71.96:62447 ! R:10.50.71.120/10.50.71.120:6379], currentCommand=null, usage=1] to 10.50.71.120/10.50.71.120:6379 
####[ProductionServer]-[] [2022-12-16 16:01:04.623+0000] [DEBUG] [redisson-netty-2-32] [org.redisson.client.handler.ConnectionWatchdog] <##   ##> - RedisConnection@2124380504 [redisClient=[addr=rediss://10.50.71.120:6379], channel=[id: 0xb9b538ba, L:/10.50.71.96:62447 ! R:10.50.71.120/10.50.71.120:6379], currentCommand=null, usage=1] connected to 10.50.71.120/10.50.71.120:6379, command: null

We are seeing:
sendCommand: attemptPromise java.util.concurrent.CompletableFuture@7593062f[Not completed], connection RedisConnection@2124380504 

I am expecting to get the attemptPromise completed exceptionally and the connection released.

Instead, I end up in ConnectionWatchdog, at line log.debug("{} connected to {}, command: {}", connection, connection.getRedisClient().getAddr(), connection.getCurrentCommand()); where current command is null.

I need to be able to verify that on channelInactive, the command gets removed from the queue and should get exceptionally completed, which does not happen in our case. 
You mentioned earlier that any failure will be propagated to the writeFuture in RedisExecutor. This would mean the attemptPromise in RedisExecutor would be completed exceptionally, yes?

**Comment by mrniko** [comment] 2022-12-21 06:07
> I am expecting to get the attemptPromise completed exceptionally and the connection released.

This happens only if max attempts were reached.

> This would mean the attemptPromise in RedisExecutor would be completed exceptionally, yes?

Exactly.

**Comment by fkolberg-verint** [comment] 2022-12-21 14:31
@mrniko 
If a command is removed from the queue in CommandsQueue inactiveChannel, we are expecting that the attemptPromise for that command be completed exceptionally, yes?
Where/When would that happen? In our case, it is never completed and the thread is stuck

**Comment by mrniko** [comment] 2022-12-23 07:03
> If a command is removed from the queue in CommandsQueue inactiveChannel, we are expecting that the attemptPromise for that command be completed exceptionally, yes?

Since getChannelPromise() it's a writeFuture field in RedisExecutor which in turn checked in `checkWriteFuture` method.

**Comment by fkolberg-verint** [comment] 2022-12-23 11:06
@mrniko 
thanks for the reply.

the "problem" is that in CommandsQueue channelInactive method, the command.getChannelPromise() is a "success" (command.getChannelPromise() = DefaultChannelPromise@30fb6c76(success))

**Comment by fkolberg-verint** [comment] 2022-12-23 12:58
@mrniko I think I have identified the problem - I am seeing scheduleResponseTimeout timeout of 3600000 ms!

I added log.debug("scheduleResponseTimeout timeout of " + timeoutTime + " for " + attemptPromise.toString() + ", connection "+connection.toString());
        timeout = Optional.of(connectionManager.newTimeout(timeoutResponseTask, timeoutTime, TimeUnit.MILLISECONDS));

timeoutTime is initialised with responseTimeout, that is meant to be 3000ms....

**Comment by fkolberg-verint** [comment] 2022-12-23 14:29
@mrniko the issue was the timeout - it was being set to 1 hour in our application code!

thanks for the responses

**Closed** 2022-12-23 14:28 UTC

**Comment by yinyansheng** [comment] 2024-06-27 02:25
> @mrniko I think I have identified the problem - I am seeing scheduleResponseTimeout timeout of 3600000 ms!
> 
> I added log.debug("scheduleResponseTimeout timeout of " + timeoutTime + " for " + attemptPromise.toString() + ", connection "+connection.toString()); timeout = Optional.of(connectionManager.newTimeout(timeoutResponseTask, timeoutTime, TimeUnit.MILLISECONDS));
> 
> timeoutTime is initialised with responseTimeout, that is meant to be 3000ms....

hi, i met the similar issue, i guess it happened during the network not stable , how did  you solve your  problem , thanks 
my issue: https://github.com/redisson/redisson/issues/5944

**Comment by mrniko** [comment] 2024-06-27 03:53
@yinyansheng 

Right
