### ISSUE TITLE
Java 9 warning - illegal reflective access

### ISSUE THREAD

**Issue by giantninja** [redisson/redisson#1174] opened 2017-12-01 17:43 UTC
Just wanted to report this warning I'm seeing now since I am giving Java 9 a go (for native alpn/ssl stuff that's not directly related to Redisson).

This warning is shown on stdout when I start up my runnable/uber jar:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.redisson.config.ConfigSupport (file:/opt/rt_deploy/ej_test/target/rt-push-server.jar) to method java.net.URI.lowMask(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.redisson.config.ConfigSupport
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

So far it appears everything is working fine, but figured it might be worth reporting, since it says it will eventually be denied in a future Java 9 release.

**Comment by jackygurui** [comment] 2017-12-06 23:43
Thanks for reporting. The usage you are referring to was an hack we have to employ to make underscores accepted in URI. The problem is while underscore is not valid for being part of URI but people are still use them in host names.

**Comment by giantninja** [comment] 2017-12-06 23:55
Gotcha.  Figured it may or may have not been a known warning for Java 9... It's still doing it's job just fine however, so keep up the good work!

**Comment by jackygurui** [comment] 2017-12-07 10:37
Thank you very much. I shall close this ticket for now.

**Comment by mattayres** [comment] 2018-09-26 03:27
After this I discovered that Netty (which Redisson depends on) also has a warning about illegal reflective access. I filed netty/netty#8318 for that and submitted netty/netty#8319 as a fix.

**Closed** 2019-04-09 05:38 UTC
