### ISSUE TITLE
Redisson sessions that never dies - missing TTL

### ISSUE THREAD

**Issue by kfh** [redisson/redisson#2023] opened 2019-04-03 07:56 UTC
For the record, we are using Redisson `3.10.4` with Redisson Tomcat 8.

In som cases we end up with shallow sessions without a TTL that fills up Redis. These `junk` sessions should probably not end up in Redis in the first place, but due to our complex application that is the situation for now. Anyway, there should be a guard in the Redis code that avoid sessions beeing created without a TTL. I'll explain why this happens and a suggestion for a solution which we are running ourselves in production.

This particular case arises when a request includes a session id which is neither stored locally in Tomcat or in Redis and it is immediately abandoned(no more interaction with the session). Then the `public Session findSession(String id) ` code in `RedissonSessionManager` is triggered, it doesn't find the session of course, but a new empty session is created and persisted in Redis where they stay forever. The fix is obviously to `setMaxInactiveInterval` on the session, which we in fact have done. But to accomplish this we have overriden the default `RedissonSessionManager` with out own `custom RedissonSessionManager` and added only `session.setMaxInactiveInterval(getContext().getSessionTimeout() * 60)`, reusing the logic used when creating new sessions. Ideally we wan't to avoid having a `custom RedissonSessionManager` to solve what should probably be part of the `default RedissonSessionManager`. 

@mrniko Could you please add this task to the next milestone?

**Comment by jchobantonov** [comment] 2019-04-25 19:06
I think this is a duplicate of https://github.com/redisson/redisson/issues/2019

**Comment by kfh** [comment] 2019-04-30 08:34
@jchobantonov Great! Just verified by using `3.10.7` in our dev environment. I can't reproduce it anymore :)

**Closed** 2019-04-30 09:16 UTC
