### ISSUE TITLE
tomcat session replication with non-sticky session not working, multiple issues

### ISSUE THREAD

**Issue by gabydinu** [redisson/redisson#974] opened 2017-07-19 13:23 UTC
Hi, 
I'm trying to setup a Tomcat 8 cluster with 2 nodes without sticky session.
Issues:
1.java.lang.IllegalStateException: setAttribute: Session [F766FB4EAE8FE29451215A67300EF46A] has already been invalidated
2. ```
Caused by: java.io.IOException: java.lang.ClassNotFoundException: xxx.dto.PermissionDTO
	at org.redisson.codec.SerializationCodec$1.decode(SerializationCodec.java:53)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:259)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:289)
	at org.redisson.client.handler.CommandDecoder.decodeFromCheckpoint(CommandDecoder.java:154)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:101)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
```


3. From RedissonSessionManager and RedissonSession i can't understand how this solution replicates in real time( no sticky sessions) the same session from one node to another.I was expecting that method getAttribute should use the map also. If someone can explain this.

And a feature if it is possible:
can we filter some session attributes from going into RMap?

Thanks.

**Comment by mrniko** [comment] 2017-07-19 13:38
Hi

1. I need a test case to reproduce it. Could you describe it?
2. Issue arises since you didn't copy jar with your dto objects to tomcat/lib directory.
3. session store maintained by Redis and not Redisson.

> can we filter some session attributes from going into RMap?

It's not implemented yet.

**Comment by gabydinu** [comment] 2017-07-19 13:56
2. my dto is in tomcat webapp folder

**Comment by gabydinu** [comment] 2017-07-19 14:04
2 tomcat nodes in a cluster no sticky session.
  - first request hit node1, create a session and store some data
  - second request with same jsessionid hit node2. node2 ask for session by hitting method findSession on RedissonSessionManager. ReddisonSessionManager loads session from redis. 
something new is saved on session
  - third request hit node1 again with same jsessionid. 
    at this point what node2 have written on session is not visible, as session is not reloaded from redis

**Comment by mrniko** [comment] 2017-07-19 16:58
> my dto is in tomcat webapp folder

It should be in `tomcat/lib` too because these jars are loaded by different ClassLoader it's not used to load classes from /webapp folder.

**Comment by gabydinu** [comment] 2017-07-20 08:16
application war file should reside in webapp folder , and tomcat-session-manager should be aware of all classes.
i think the solution is to use the WebappClassLoader: getContext().getLoader().getClassLoader().
Maybe this would work, but I have bot tested it.
config = Config.fromYAML(new File(configPath), getContext().getClass().getClassLoader());

**Comment by mrniko** [comment] 2017-07-20 08:40
Interesting idea. It would be great if you could you test that. Could you?

**Comment by gabydinu** [comment] 2017-07-20 11:19
i have tested it.
seems that getContext().getLoader().getClassLoader() resturns correct class loader, but...
my configuration is using "codec: !<org.redisson.codec.SerializationCodec> {}" and this codec has 2 constructors 
`    public SerializationCodec() {
        this(null);
    }
    
    public SerializationCodec(ClassLoader classLoader) {
        this.classLoader = classLoader;
    }`
**it seems that default constructor with null class loader is always called.**
this is my YAML config :
---
singleServerConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://127.0.0.1:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 10
  connectionPoolSize: 64
  database: 0
  dnsMonitoring: false
  dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.SerializationCodec> {}
useLinuxNativeEpoll: false

**Comment by miriamccp** [comment] 2017-07-25 05:50
This problem bothered me before. Try Thread.currentThread().getContextClassLoader(), it works perfectly for me.

**Comment by miriamccp** [comment] 2017-07-25 05:54
I mean Thread.currentThread().getContextClassLoader() resolved the ClassLoader issue, but it didn't resolve the non-sticky issue.

**Comment by mrniko** [comment] 2017-07-25 09:20
Fixed issue with ContextClassLoader. I'm unable to reproduce non-sticky issue. Please re-check it with version from 'master' banch.

**Comment by miriamccp** [comment] 2017-07-25 11:19
try the steps for reproduce the non-sticky issue:
1. having 2 tomcat server with one non-sticky load balancer.
2. login the web application.
3. do some actions, make sure that both tomcat servers already have your session in their memory.
3. perform one action which will change the session attributes, assume session attributeA being changed from "A" to "B" by tomcat server 1. and this change is sent to Redis server.
4. try to read the session attributeA from tomcat server 2, you will find it's still "A".
5. because though attributeA's new value already sent to Redis server, but tomcat server 2 is not notified, so it keep on reading the value of attributeA from its memory, instead of reloading it from the Redis server.

**Comment by mrniko** [comment] 2017-07-25 17:26
> though attributeA's new value already sent to Redis server, but tomcat server 2 is not notified, so it keep on reading the value of attributeA from its memory, instead of reloading it from the Redis server.

Tomcat server doesn't store sessions in memory if you setup RedissonSessionManager properly. It read values directly from Redis and not own memory.

**Comment by iakko** [comment] 2017-07-27 14:04
I have the same exactly configuration and behavior as @miriamccp. My instances are on Azure, this is my redisson.conf:

```
{
   "singleServerConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "password":"<redis_password>",
      "subscriptionsPerConnection":5,
      "clientName":"<node_name_#>",
      "address": "redis://<my_azure_redis>.redis.cache.windows.net:6379",
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":10,
      "connectionPoolSize":64,
      "database":0,
      "dnsMonitoring":false,
      "dnsMonitoringInterval":5000
   },
   "threads":0,
   "nettyThreads":0,
   "codec":null,
   "useLinuxNativeEpoll":false
}
```

Any idea how to debug the issue on a low level?

**Comment by iakko** [comment] 2017-07-27 16:12
Ok, I've tested it also on version 3.4.5-SNAPSHOT and same behavior.

My test case is this one:
1. I have a first service that retrieves data from DB and puts it on session.
2. The second service checks in session if some data is stored in the session. If yes, good, otherwise returns an error.

As I'm using a load balancer, I can clearly see that each request on the second service is served from both servers, in a round robin scenario (Server 1, Server 2, Server 1, Server 2, ...). Also, I'm sure that the cookie ID sent to the server is the same (I'm putting it in the output of the service as echo).

When the request 2 is served from the same Tomcat that received the service on point 1, no problem at all. Otherwise, when served from the other instance, I got an error. To be more sure, I've removed one server from the load balancer and in that case, I have no issue at all (of course).

It's driving me crazy, any suggestion on how to debug this is much appreciated.

Thanks,
IP

**Comment by mrniko** [comment] 2017-07-28 11:56
@iakko Which tomcat version do you use?

**Comment by hans123456** [comment] 2017-07-28 12:57
Hi @mrniko , @gabydinu , and @iakko 

By reading the RedissonSession class, the Session doesn't retrieve any values from the Redis after the first load inside RedissonSessionManager calling the RedissonSession#load.

I solved the non-stickiness issue by creating my own RedissonSession class and overriding the getAttribute method of StandardSession to directly get from the RMap.

```
@override
public Object getAttribute(String name) {
  return map.get(name);
}
```

**Comment by mrniko** [comment] 2017-07-28 13:08
I think I have fixed invalidated session problem. Problem was in order of loading attributes - `isValid` attribute should always be read before set any attribute to local Session object.

**Comment by iakko** [comment] 2017-07-30 08:37
@mrniko I'm using Tomcat 8.

Anyway, I've started using redisson 3.5.0 and seems like the problem has being solved (partially in my case). 

No more exceptions, everything is good, but I'm noticing a delay on updating the session. This is the scenario:

Service A is used to populate the session, service B needs data populated by service A, so the right way to use them is using Service A and after service B (similar to a login phase). 

The clients calls service A, that is served fron Tomcat #1, the the clients calls service B immediately after, but it goes on error because service B cannot find data populated by service A.

Reproducing the scenario manually, with Postman for example, no problem at all. 

I realized that the problem seems to be a delay of tomcat #1 synchronizing the redis server. I was expecting that the setAttribute() call would be synchronous on putting data in cache, but apparently it is not (in my expectation, when the setAttribute() returns, I should be sure that data have been stored on redis server).

To solve this issue, i have to use sticky sessions. 

Any idea on this?

Thanks a lot.

**Comment by miriamccp** [comment] 2017-07-30 20:15
@iakko,look at hans123456's comment, override the getAttribute method will resolve the issue, but meanwhile, i think the RedissonSession load() method would be meaningless，as that method is to load all session attrs from redis server into tomcat server memory, which according to @mrniko's comment, should not happen.(he mentioned server won't read attrs from memory, but from redis server directly) i think the load method should load only the basic session attrs( isValid, isNew...something like that.)

**Comment by mrniko** [comment] 2017-07-31 07:38
@miriamccp my mistake, currently Redisson Manager loads all attributes to minimize access time to them.

**Comment by mrniko** [comment] 2017-07-31 07:55
@iakko 

> I was expecting that the setAttribute() call would be synchronous on putting data in cache, but apparently it is not. In my expectation, when the setAttribute() returns, I should be sure that data have been stored on redis server.
 
Have a look at [RedissonSession.setAttribute](https://github.com/redisson/redisson/blob/3c0449eda7d426a879a10f6121d3c214525c54aa/redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSession.java#L133) method, Redisson stores attribute in synchronous mode.

**Comment by iakko** [comment] 2017-07-31 16:48
@mrniko actually, I see this code:

```
    @ Override
    public void setAttribute(String name, Object value, boolean notify) {
        super.setAttribute(name, value, notify);
        
        if (map != null && value != null) {
            map.fastPut(name, value);
        }
    }
```
But I usually use the function with signature public void `setAttribute(String name, Object value)`, which is not handled in [https://github.com/redisson/redisson/blob/3c0449eda7d426a879a10f6121d3c214525c54aa/redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSession.java#L34](RedissonSession), thus it calls the implementation of the extended object (which frankly, I don't know how it handles the setAttribute() in details).

Does it make any difference?

**Comment by iakko** [comment] 2017-07-31 17:11
Ok, I understand that.

Assuming that, and assuming as you sad before that getAttribute never reads from memory, but directly from Redis Server, the only explanation is that maybe the Azure Redis PaaS return a not-fresh version of data just retrieved.

Have you ever heard about this kind of issue before?

**Comment by iakko** [comment] 2017-08-02 11:14
I'm sorry to continue bothering with this, but I have a big issue retrieving cached data with Tomcat 8 and Redisson 3.5.0 (without sticky sessions).

Seems like to me that every time I try to get data from session from within my service (using `HttpServletRequest.getSession().getAttribute()`) Redisson is not going to get it from server.

I've monitored that using MONITOR on Redis server and I never see a HGETALL on the session ID, but only some HSET.

Looking the RedissonSession class, I don't see any `public Object getAttribute(String name)`. I guess this means that it's using the StandardSession getAttribute definition, that is not calling Redis.

Any hints? Thanks.

**Comment by hans123456** [comment] 2017-08-02 11:17
@iakko That's what I said in the comment above, the getAttribute wasn't overriden so all the attributes are retrieved from memory after calling RedissonSession#load inside RedissonSessionManager#findSession.

https://github.com/redisson/redisson/issues/974#issuecomment-318644918

**Comment by iakko** [comment] 2017-08-02 11:23
Ok, sorry guys.

@hans123456: glad to know that I've come to your same conclusion :)
@mrniko: any idea when the fix will be available?

**Comment by mrniko** [comment] 2017-08-07 18:29
@iakko 

https://github.com/redisson/redisson/issues/974#issuecomment-318992217

Could you please describe your case? I thought Session should be used by only one user at a time, but in your case it's not so.

**Comment by iakko** [comment] 2017-08-08 06:40
@mrniko: of course session is supposed to be used by one user at a time, but there might be some circumstances where a web application can invoke several services in parallel for different reasons. In that case, you might need to handle synchronization between calls with some session data.

Although, my concern related that comment is the fact that due to the missing getAttribute, I was having very bad drawbacks and seemed like the Redis session update was not syncronous with the setAttribute call, that would have lead to a non synchronous call between the setAttribute and the next getAttribute. Also, the missing getAttribute on the RedissonSession class, takes Tomcat to store data on the local memory, this is very confusing because when the call landed on the Tomcat with data in memory, everything was working. Instead, when landed on the wrong Tomcat, data on Redis were not updated. Very confusing scenario.

Anyway, do you have any clue when the updated version will be available?

Thanks!

**Comment by maichaojiu** [comment] 2017-08-08 11:23
setAttribute: Session xx has already been invalidated 这个问题还没有解决的吗，我现在使用出现了这个问题 @mrniko ,有临时的解决方法吗

**Comment by mrniko** [comment] 2017-08-08 13:18
@maichaojiu fixed in "master" branch https://github.com/redisson/redisson/commit/056adfa7d5288e2864443b937cdc3cb9234cc9ae

**Comment by maichaojiu** [comment] 2017-08-09 01:19
@mrniko ok,thanks

**Comment by mrniko** [comment] 2017-08-11 08:17
@iakko 

I have added `readMode` property to RedissonSessionManager, it's has two options: MEMORY and REDIS. MEMORY is default, so you should set it to REDIS.

**Comment by iakko** [comment] 2017-08-11 10:46
Hello @mrniko,

Can you kindly explain how to use that?

Also, I've just checked out the 3.0.0 branch to see if the "getAttribute" issue was solved, but I still cannot see it in the RedossonSession.java class for Tomcat 8.

Thank you.

**Comment by mrniko** [comment] 2017-08-11 15:36
@iakko I have just pushed it forward to 3.0.0 branch.

**Comment by mrniko** [comment] 2017-08-29 10:27
Done

**Closed by mrniko** 2017-08-29 10:27 UTC
Labels: bug

**Comment by iakko** [comment] 2017-09-01 12:59
HEllo @mrniko ,

I've updated the version to 3.5.1 but seems like the REDIS session is not updated properly.

I think it's because I've not set readMode from MEMORY to REDIS, but I don't understand where to set it (I've tried on redisson.conf but without success).

Can you explain where should I put that configuration?

Thanks.

**Comment by hans123456** [comment] 2017-09-01 13:13
@iakko based on the code, you put it in the context.xml

Example:
<Manager ... readMode="REDIS" ... />

**Comment by iakko** [comment] 2017-09-01 13:21
Yes, I was writing you that I figured it out, I need some days off :smile: 

Seems to work well now, thank you very much!

Ciao.

**Comment by mrniko** [comment] 2017-09-01 13:43
@hans123456 thanks for support!
@iakko you're welcome!

**Comment by iakko** [comment] 2017-09-25 13:23
Sorry guys, but I have to go back to the "Session has already been invalidated" issue.

I'm using Redisson 3.5.1 on Tomcat 8, and sometimes I get the annoying exception:

```
HTTP Status 500 - setAttribute: Session [<SESSION_ID>] has already been invalidated

type Exception report

message setAttribute: Session [<SESSION_ID>] has already been invalidated

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.lang.IllegalStateException: setAttribute: Session [71C7FE8F05C874E641C094C1909BAB26] has already been invalidated
	org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1462)
	org.redisson.tomcat.RedissonSession.setAttribute(RedissonSession.java:146)
	org.redisson.tomcat.RedissonSession.load(RedissonSession.java:205)
	org.redisson.tomcat.RedissonSessionManager.findSession(RedissonSessionManager.java:115)
	org.apache.catalina.connector.Request.doGetSession(Request.java:2906)
	org.apache.catalina.connector.Request.getSessionInternal(Request.java:2559)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:429)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1504)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1460)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:748)
note The full stack trace of the root cause is available in the Apache Tomcat/8.0.32 (Ubuntu) logs.
```

Should it be fixed on 3.5.1?

Thanks
IP

**Comment by mrniko** [comment] 2017-09-25 14:14
@iakko Due to https://github.com/redisson/redisson/issues/1031 bug I would recommend you to update on 3.5.3

**Comment by iakko** [comment] 2017-09-25 14:19
@mrniko: I've just updated to it, I'm trying to reproduce the issue but it's not so easy. Does the 3.5.3 resolves the session issue or is it just a suggestion?

**Comment by mrniko** [comment] 2017-09-25 14:31
Actually issue you're talking about had been resolved in 3.5.1 But it also introduced a regression bug, which has been solved in 3.5.3

**Comment by mrniko** [comment] 2017-09-25 14:36
You're right Redisson attempts to load session from Redis if it couldn't be located in Tomcat.

**Comment by iakko** [comment] 2017-09-25 14:49
So, is it a bug or a correct behavior? In case it's correct, how should it be treated?

**Comment by mrniko** [comment] 2017-09-25 14:58
It's correct behavior. Since session should be loaded in Tomcat first. As for you bug. Have you checked for presence of "session:isValid" property? Since `StandardSession.isValid` is false by default. I think this is the cause.

**Comment by iakko** [comment] 2017-09-25 15:40
I'm trying to reproduce it, but it's not easy.

Most likely, it's because the session id does not exists in redis anymore.
So, the "session:isValid" ia not present at all.

Scenario:

1. Creating a session, server responds with session cookie. Everything is
working fine.
2. Session timeout expires, tomcat removes session from redis
(sessionDestroy() is triggered).
3. Time passes, many things happen, like server reboot. Also, tomcat might
destroy session because it goes on timeout.
4. the client tries to use the expired session giving the old session
cookie, boom!

Another idea is: what happens if tomcat reboots before session expires?
Does tomcat remembers about sessions created with redisson and triggers the
setDesteoy() or does it loose this?

I'm on short of ideas :(

--
This message has been typed with my mobile device, sorry for typos and/or
missformats.


On Sep 25, 2017 16:58, "Nikita Koksharov" <notifications@github.com> wrote:

It's correct behavior. Since session should be loaded in Tomcat first. As
for you bug. Have you checked for presence of "session:isValid" property?
Since StandardSession.isValid is false by default. I think this is the
cause.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/redisson/redisson/issues/974#issuecomment-331908645>,
or mute the thread

**Comment by mrniko** [comment] 2017-09-26 13:33
I realized what is the problem during `StandardSession.expire` method invocation: `manager.remove` method removes session completely which is correct but next invocation `setValid(false)` recreates it again

**Comment by mrniko** [comment] 2017-09-26 13:53
@iakko I did few changes related to my previous comment. Could you please check your issue again?

**Comment by iakko** [comment] 2017-09-28 13:45
@mrniko: I'm trying to find out where the change is, but I can't see any 3.5.* tag/branch containing the fix, only on master branch.

**Comment by mrniko** [comment] 2017-09-28 13:52
@iakko I have just updated 3.0.0 branch

**Comment by iakko** [comment] 2017-09-28 14:35
@mrniko: ok, I've replaced 3.5.3 with 3.5.4-SNAPSHOT and at first sight, seems working now. I'll perform additional, more reliable, tests in these days, I'll let you know.

Do you have an idea when the official release of version 3.5.4 will be available? If I use a "SNAPSHOT" version in production I'll be killed :)

Thanks.
IP

**Comment by mrniko** [comment] 2017-09-28 14:36
@iakko I'm going to publish it today

**Comment by iakko** [comment] 2017-11-23 14:04
Just to confirm that after a couple of months of testing, this issue has never shown again.

**Comment by mrniko** [comment] 2017-11-24 05:28
@iakko That's great! Thank you!
