### ISSUE TITLE
java.lang.IllegalArgumentException: Redis url should start with redis:// or rediss://

### ISSUE THREAD

**Issue by PC-AKumar** [redisson/redisson#1810] opened 2018-12-19 22:42 UTC
### Expected behavior
Deserialization works as expected when key doesn't exist on given node
### Actual behavior
Exception is thrown,
2018-12-19 14:13:11,442 ERROR redisson-netty-4-7 [org.redisson.client.handler.CommandDecoder] - Unable to decode data. reply: -MOVED 11508 10.212.33.61:6379
, channel: [id: 0x93a583e7, L:/10.215.23.63:36708 - R:10.215.34.16/10.215.34.16:6379], command: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@769675be(incomplete)], command=(DEL), params=[securityInfo:sourceAssetId:YODLEE_DESCR_Vanguard Windsor? II Admiral?], codec=org.redisson.codec.SnappyCodec]
java.lang.IllegalArgumentException: Redis url should start with redis:// or rediss:// (for SSL connection)
	at org.redisson.misc.URIBuilder.create(URIBuilder.java:33)
	at org.redisson.client.RedisRedirectException.<init>(RedisRedirectException.java:36)
	at org.redisson.client.RedisMovedException.<init>(RedisMovedException.java:28)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:316)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:128)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:108)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)

### Redis version
5.0.0
### Redisson version
3.9.1
### Redisson configuration
{
  "clusterServersConfig": {
    "idleConnectionTimeout": 60000,
    "pingTimeout": 1000,
    "connectTimeout": 10000,
    "timeout": 10000,
    "retryAttempts": 3,
    "retryInterval": 1500,
    "subscriptionsPerConnection": 5,
    "clientName": "HighAvailCluster",
    "sslEnableEndpointIdentification": true,
    "sslProvider": "JDK",
    "pingConnectionInterval": 0,
    "keepAlive": true,
    "tcpNoDelay": false,
    "loadBalancer": {
      "class": "org.redisson.connection.balancer.RoundRobinLoadBalancer"
    },
    "slaveConnectionMinimumIdleSize": 1,
    "slaveConnectionPoolSize": 1,
    "failedSlaveReconnectionInterval": 3000,
    "failedSlaveCheckInterval": 180000,
    "masterConnectionMinimumIdleSize": 10,
    "masterConnectionPoolSize": 40,
    "readMode": "MASTER",
    "subscriptionMode": "MASTER",
    "subscriptionConnectionMinimumIdleSize": 1,
    "subscriptionConnectionPoolSize": 50,
    "dnsMonitoringInterval": 5000,
    "nodeAddresses": [
      "redis://some-endpoint:6379"
    ],
    "scanInterval": 5000,
    "slaveSubscriptionConnectionMinimumIdleSize": 1,
    "slaveSubscriptionConnectionPoolSize": 50
  },
  "threads": 0,
  "nettyThreads": 0,
  "codec": {
    "class": "org.redisson.codec.SnappyCodec"
  },
  "referenceCodecProvider": {
    "class": "org.redisson.codec.DefaultReferenceCodecProvider"
  },
  "referenceEnabled": true,
  "transportMode": "NIO",
  "lockWatchdogTimeout": 30000,
  "keepPubSubOrder": true,
  "useScriptCache": false,
  "addressResolverGroupFactory": {
    "class": "org.redisson.connection.DnsAddressResolverGroupFactory"
  },
  "useLinuxNativeEpoll": false
}

**Comment by jackygurui** [comment] 2018-12-19 22:50
duplicate of https://github.com/redisson/redisson/issues/1797#issuecomment-446136675 and it is fixed with https://github.com/redisson/redisson/commit/21ac3d81c17c0488ee33cb87e5e46b3fb893ec93

**Comment by PC-AKumar** [comment] 2018-12-20 02:08
@jackygurui any eta on the release?

**Comment by mrniko** [comment] 2018-12-30 05:58
version 3.10.0 has been released

**Closed by mrniko** 2018-12-30 05:58 UTC
