### ISSUE TITLE
Print the SearchDomainUnknownHostException repeatedly when connected to redis sentinel cluster on the Kubernetes

### ISSUE THREAD

**Issue by zewade** [redisson/redisson#3268] opened 2020-12-07 14:59 UTC
When I use redission 3.13.6 to connect to the redis sentinel cluster on the kubernetes,it will print following logs every few seconds.The address of cluster is redis-cluster:26379 which is the servername on kubernetes. But when I change the address to its IP address which is 172.30.49.77:26379,the error is missing.How to resovle this problem when use servicename address.

2020-12-07 21:45:02,655 INFO  [metrics-infra-ewell] [nioEventLoopGroup-5-4] [o.r.c.SentinelConnectionManager:558] - trace[] sentinel: redis://172.30.49.77:26379 added
2020-12-07 21:45:03,588 WARN  [metrics-infra-ewell] [nioEventLoopGroup-5-2] [o.r.c.SentinelConnectionManager:501] - trace[] sentinel: redis://172.30.151.185:26379 is down
2020-12-07 21:45:04,599 WARN  [metrics-infra-ewell] [nioEventLoopGroup-5-2] [o.r.c.SentinelConnectionManager:501] - trace[] sentinel: redis://172.30.49.77:26379 is down
2020-12-07 21:45:04,604 INFO  [metrics-infra-ewell] [nioEventLoopGroup-5-2] [o.r.c.SentinelConnectionManager:558] - trace[] sentinel: redis://172.30.151.185:26379 added
2020-12-07 21:45:05,886 ERROR [metrics-infra-ewell] [nioEventLoopGroup-2-2] [o.r.c.SentinelConnectionManager:285] - trace[] Unable to resolve redis-cluster
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'redis-cluster' failed to resolve 'redis-cluster.devcommon.svc.cluster.local'
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:845)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:806)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:322)
	at io.netty.resolver.dns.DnsResolveContext.access$500(DnsResolveContext.java:62)
	at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:379)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:33)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:354)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:322)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:909)
	at io.netty.resolver.dns.DnsResolveContext.internalResolve(DnsResolveContext.java:272)
	at io.netty.resolver.dns.DnsResolveContext.doSearchDomainQuery(DnsResolveContext.java:244)
	at io.netty.resolver.dns.DnsAddressResolveContext.doSearchDomainQuery(DnsAddressResolveContext.java:98)
	at io.netty.resolver.dns.DnsResolveContext.resolve(DnsResolveContext.java:211)
	at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached(DnsNameResolver.java:972)
	at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:925)
	at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:893)
	at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:81)
	at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:96)
	at io.netty.resolver.dns.InflightNameResolver.resolveAll(InflightNameResolver.java:71)
	at io.netty.resolver.dns.InflightNameResolver.resolveAll(InflightNameResolver.java:56)
	at io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:75)
	at io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:32)
	at io.netty.resolver.AbstractAddressResolver.resolveAll(AbstractAddressResolver.java:160)
	at org.redisson.connection.SentinelConnectionManager.performSentinelDNSCheck(SentinelConnectionManager.java:280)
	at org.redisson.connection.SentinelConnectionManager.access$200(SentinelConnectionManager.java:54)
	at org.redisson.connection.SentinelConnectionManager$1.run(SentinelConnectionManager.java:273)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.resolver.dns.DnsNameResolverException: [/192.168.190.226:53] failed to send a query (no stack trace available)
Caused by: java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
2020-12-07 21:45:07,659 INFO  [metrics-infra-ewell] [nioEventLoopGroup-5-2] [o.r.c.SentinelConnectionManager:558] - trace[] sentinel: redis://172.30.49.77:26379 added
2020-12-07 21:45:07,831 WARN  [metrics-infra-ewell] [nioEventLoopGroup-5-1] [o.r.c.SentinelConnectionManager:501] - trace[] sentinel: redis://172.30.49.77:26379 is down
2020-12-07 21:45:10,894 ERROR [metrics-infra-ewell] [nioEventLoopGroup-2-2] [o.r.c.SentinelConnectionManager:285] - trace[] Unable to resolve redis-cluster
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'redis-cluster' failed to resolve 'redis-cluster.devcommon.svc.cluster.local'
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:845)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:806)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:322)
	at io.netty.resolver.dns.DnsResolveContext.access$500(DnsResolveContext.java:62)
	at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:379)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:216)
	at io.netty.resolver.dns.DnsQueryContext.onQueryWriteCompletion(DnsQueryContext.java:151)
	at io.netty.resolver.dns.DnsQueryContext.access$200(DnsQueryContext.java:43)
	at io.netty.resolver.dns.DnsQueryContext$3.operationComplete(DnsQueryContext.java:143)
	at io.netty.resolver.dns.DnsQueryContext$3.operationComplete(DnsQueryContext.java:140)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:869)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1391)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1104)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1151)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1075)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.resolver.dns.DnsNameResolverException: [/192.168.190.226:53] failed to send a query (no stack trace available)
Caused by: java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)

**Comment by mrniko** [comment] 2020-12-08 12:08
Caused by: io.netty.resolver.dns.DnsNameResolverException: [/192.168.190.226:53] failed to send a query

**Comment by zewade** [comment] 2020-12-09 06:31
> Caused by: io.netty.resolver.dns.DnsNameResolverException: [/192.168.190.226:53] failed to send a query

Could I set dnsMonitoringInterval = -1 to avoid this error log?

**Comment by mrniko** [comment] 2020-12-09 08:23
I'm afraid no, since `redis-cluster.devcommon.svc.cluster.local` host should be resolved in any way.

**Closed** 2021-01-03 16:04 UTC
Labels: question

**Comment by youdang123** [comment] 2022-04-22 09:01
@zewade @mrniko I also encountered the same problem, how to solve it

**Comment by mrniko** [comment] 2022-04-23 07:41
@youdang123 

Did you try to specify fully qualified name?
