### ISSUE TITLE
Local Embedded Redis does not work with 3.9.1

### ISSUE THREAD

**Issue by slisaasquatch** [redisson/redisson#1750] opened 2018-11-23 16:58 UTC
Here is [the other issue I created](https://github.com/redisson/redisson/issues/1729).
Just like the other ticket, as soon as I downgrade to 3.8.2, everything works just fine.

### Expected behavior
Redisson should be able to connect to local redis running on port 6614.

### Actual behavior
Redisson won't start and throws this error:
```
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6614
        at org.redisson.connection.pool.ConnectionPool$2$1.operationComplete(ConnectionPool.java:160)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:108)
        at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:327)
        at org.redisson.connection.pool.ConnectionPool.access$400(ConnectionPool.java:53)
        at org.redisson.connection.pool.ConnectionPool$4.operationComplete(ConnectionPool.java:291)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:108)
        at org.redisson.client.RedisClient$2$1$2.run(RedisClient.java:250)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: failed to create a new resolver
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:71)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:200)
        at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:49)
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:188)
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:174)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:512)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
        ... 6 common frames omitted
Caused by: java.lang.IllegalStateException: failed to create a new resolver
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:71)
        at org.redisson.connection.dns.MultiDnsAddressResolverGroup.newResolver(MultiDnsAddressResolverGroup.java:68)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:79)
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
        ... 19 common frames omitted
Caused by: io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioDatagramChannel
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320)
        at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:234)
        at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:394)
        at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:430)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newNameResolver(DnsAddressResolverGroup.java:114)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:94)
        at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:79)
        at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
        ... 22 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
        ... 30 common frames omitted
Caused by: io.netty.channel.ChannelException: Failed to open a socket.
        at io.netty.channel.socket.nio.NioDatagramChannel.newSocket(NioDatagramChannel.java:88)
        at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:116)
        ... 34 common frames omitted
Caused by: java.net.SocketException: maximum number of DatagramSockets reached
        at sun.net.ResourceManager.beforeUdpCreate(ResourceManager.java:73)
        at sun.nio.ch.DatagramChannelImpl.<init>(DatagramChannelImpl.java:111)
        at sun.nio.ch.SelectorProviderImpl.openDatagramChannel(SelectorProviderImpl.java:42)
        at io.netty.channel.socket.nio.NioDatagramChannel.newSocket(NioDatagramChannel.java:86)
        ... 35 common frames omitted
```

### Redis version
2.8.19 with [embedded-redis](https://github.com/kstyrc/embedded-redis)

### Redisson version
3.9.1

### Redisson configuration
		final org.redisson.config.Config rConfig = new org.redisson.config.Config()
				.setTransportMode(TransportMode.NIO);
		rConfig.useSingleServer()
				.setAddress("redis://localhost:6614")
				.setPassword(password);

**Comment by Flo354** [comment] 2018-11-23 17:30
Hi there,

I am also still affected by the issue.
I am on Ubuntu 18.04 with Java 8 (Oracle) -> I do not have the issue on an Amazon Linux with OpenJDK 8
I am using play framework latest version

Here is my stack trace

```
Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 127.0.0.1/127.0.0.1:6379
	at org.redisson.connection.pool.ConnectionPool$2$1.operationComplete(ConnectionPool.java:160)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:108)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:327)
	at org.redisson.connection.pool.ConnectionPool.access$400(ConnectionPool.java:53)
	at org.redisson.connection.pool.ConnectionPool$4.operationComplete(ConnectionPool.java:291)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:108)
	at org.redisson.client.RedisClient$2$1$2.run(RedisClient.java:250)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: failed to create a new resolver
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:71)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:200)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:49)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:188)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:174)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:512)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
	... 6 common frames omitted
Caused by: java.lang.IllegalStateException: failed to create a new resolver
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:71)
	at org.redisson.connection.dns.MultiDnsAddressResolverGroup.newResolver(MultiDnsAddressResolverGroup.java:68)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:79)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
	... 19 common frames omitted
Caused by: io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioDatagramChannel
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320)
	at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:234)
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:394)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:430)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newNameResolver(DnsAddressResolverGroup.java:114)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:94)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:79)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
	... 22 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedConstructorAccessor47.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	... 30 common frames omitted
Caused by: io.netty.channel.ChannelException: Failed to open a socket.
	at io.netty.channel.socket.nio.NioDatagramChannel.newSocket(NioDatagramChannel.java:88)
	at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:116)
	... 34 common frames omitted
Caused by: java.net.SocketException: maximum number of DatagramSockets reached
	at sun.net.ResourceManager.beforeUdpCreate(ResourceManager.java:73)
	at sun.nio.ch.DatagramChannelImpl.<init>(DatagramChannelImpl.java:111)
	at sun.nio.ch.SelectorProviderImpl.openDatagramChannel(SelectorProviderImpl.java:42)
	at io.netty.channel.socket.nio.NioDatagramChannel.newSocket(NioDatagramChannel.java:86)
	... 35 common frames omitted
```

**Comment by mrniko** [comment] 2018-11-26 10:47
I restored logic of `org.redisson.connection.DnsAddressResolverGroupFactory`, but `org.redisson.connection.MultiDnsAddressResolverGroupFactory` is still used by default. 

Please update to latest version of `3.0.0` branch and set [addressResolverGroupFactory](https://github.com/redisson/redisson/wiki/2.-Configuration/_edit#addressresolvergroupfactory) setting to `org.redisson.connection.DnsAddressResolverGroupFactory` to make it work

**Comment by Flo354** [comment] 2018-11-26 20:36
Thanks. I will only be able to test that on the week of 10th December

**Comment by mrniko** [comment] 2019-01-11 09:59
@Flo354 

Is there any update?

**Comment by Flo354** [comment] 2019-01-11 11:56
Hi @mrniko,

I am sorry, I forgot to test. 
So I just test and can say that it works perfectly.

I think you can close the issue :)

**Comment by mrniko** [comment] 2019-01-11 11:57
@Flo354 Great! Thanks for help!

**Closed by mrniko** 2019-01-11 11:57 UTC

**Comment by Flo354** [comment] 2019-02-07 16:50
@mrniko Problem came back with 3.10.2
`Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 25 from 32 were initialized. Redis server: 127.0.0.1/127.0.0.1:6379` 

Does it come from here? `Improvement - default values of nettyThreads and threads settings set to 32 and 16 respectively`

Also, `org.redisson.connection.MultiDnsAddressResolverGroupFactory` disappeared.

**Comment by mrniko** [comment] 2019-02-07 17:29
@Flo354 

> Caused by: org.redisson.client.RedisConnectionException: Unable to init enough connections amount! Only 25 from 32 were initialized. Redis server: 127.0.0.1/127.0.0.1:6379

Do you run it locally or some slow vds instance?

> Does it come from here? `Improvement - default values of nettyThreads and threads settings set to 32 and 16 respectively`

I'm afraid no.

> Also, `org.redisson.connection.MultiDnsAddressResolverGroupFactory` disappeared.

I removed it, since issue was resolved in netty

**Comment by Flo354** [comment] 2019-02-07 17:49
The problem only occurs locally and, as it was before, I can "fix it" by setting: `-Dsun.net.maxDatagramSockets=1024`

**Comment by lbispham** [comment] 2019-04-17 17:09
> The problem only occurs locally and, as it was before, I can "fix it" by setting: `-Dsun.net.maxDatagramSockets=1024`

I'm also having this issue on the latest version: 3.10.6. Any chance of a resolution? @Flo354 how do you apply that setting for the workaround?

**Comment by Flo354** [comment] 2019-04-30 09:05
@lbispham just add it as a VM option when you start play framework from the command line

**Comment by 0xadam** [comment] 2019-05-08 06:56
The JVM appears to limit the number of DatagramSockets to 25 by default, and now that Redisson has 32 Netty threads by default it appears that more Netty threads are created than the allowed amount of DatagramSockets (I'm assuming 32 are created). So the other option is to decrease the number of Netty threads that Redisson creates through its configuration.
