### ISSUE TITLE
NullPointerException while caching collection - Rset

### ISSUE THREAD

**Issue by navinvasu** [redisson/redisson#5604] opened 2024-02-01 16:44 UTC
**Expected behavior**
No errors or Null pointer exception when Caching RSet<Object>. Collection of class-objects are saved to cache.

**Actual behavior**
Inconsistently throws NullPointer exception.
`java.lang.NullPointerException: null
	at o.redisson.command.RedisExecutor.handleError(RedisExecutor.java:602)
	at o.redisson.command.RedisExecutor.execute(RedisExecutor.java:202)
	at o.r.command.CommandAsyncService.async(CommandAsyncService.java:564)
	at o.r.command.CommandAsyncService.writeAsync(CommandAsyncService.java:522)
	at org.redisson.RedissonSet.addAllAsync(RedissonSet.java:317)
	at org.redisson.RedissonSet.addAll(RedissonSet.java:305)`

**Steps to reproduce or test case**
val cacheRSet = redissonClient.getSet<CacheRecord>(key, TypedJsonJacksonCodec(CacheRecord::class.java, objectMapper))
cacheRSet.addAll(listOf(Object))
cacheRSet.expire(cacheTtl)

**Redis version**
ElastiCache engine version 7.1.0

**Redisson version**
3.26.0

**Redisson configuration**
`useClusterServers()
timeout = 30000
isCheckLockSyncedSlaves = false`

**Comment by mrniko** [comment] 2024-02-15 08:42
Unable to reproduce. Below is the test

```java
        RSet<String> cacheRSet = redisson.getSet("key", new TypedJsonJacksonCodec(String.class, new ObjectMapper()));
        cacheRSet.addAll(Arrays.asList("1", "2", "3"));
        cacheRSet.expire(Duration.ofSeconds(1));
```

**Comment by mrniko** [comment] 2024-02-19 06:54
Is there any update?

**Comment by navinvasu** [comment] 2024-02-20 16:10
@mrniko the error occurs Inconsistently. Would be difficult to reproduce.
Just an observation, the data type used was a java class vs the string used in the above example. Not sure if it has any impact on the way the redisson client reads the data and throws null pointer ?

**Comment by mrniko** [comment] 2024-02-21 05:09
Fixed in https://github.com/redisson/redisson/issues/5641

**Closed by mrniko** 2024-02-21 05:09 UTC
