### ISSUE TITLE
Dead connection stay in pool forever if server is not responding.

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [redisson/redisson#3395] opened 2021-02-02 11:37 UTC
**Expected behavior**
Dead Connection automatically reconnect after channel inactive.
**Actual behavior**
In `org.redisson.client.handler.CommandsQueue`, we only call sendNextCommand to poll command if server responded with data or write was failed in the first place.
But if client write was successful and server is not responding, our QueueCommand is still staying at the front of queue, next time we call sendData, org.redisson.client.protocol.QueueCommandHolder#trySend will return false and nothing happens.

So eachtime we use that connection to write something, we got  `RedisTimeoutException:  Command still hasn't been written into connection!`
**Redisson version**
3.13.1

**Comment by mrniko** [comment] 2021-02-02 12:13
Try 3.14.1 version since it has fix for connection leak problem.

**Comment by Nick-The-Uncharted** [comment] 2021-02-03 01:17
@mrniko I read the lastest code and the issue should still be there. Its not like #3270 that connection exists but not in allConnection. It's instead dead connection (closed by server) still in allConnections. 
It's expected to causing IOException and trigger reconnect when we write something into it, but becuase last command is not responding `org.redisson.client.handler.CommandsQueue#write` simply add msg to the queue and nothing happens.

**Comment by Nick-The-Uncharted** [comment] 2021-02-03 01:27
@mrniko For 24 connections in my pool, there are only 3 connections will appear in the errormsg of RedisTimeOutException (there are tons of Exception when loads is high and they span through hours). Something they have in common is that their `currentCommand` is not null at anytime(I used debugging tools to inspect objects attributes), and if I call `channel.writeAndFlush(@io.netty.buffer.Unpooled@wrappedBuffer("hello world".getBytes())).get()` they will instantly reconnect. Sadly I ran out of connections in error state when experimenting. So I go through the code and it's seems to be caused by server not responding so previous command can never complete (Maybe we should close channel when throwing `RedisTimeoutException`?).
`

**Comment by mrniko** [comment] 2021-02-03 06:59
did you try to set `pingConnectionInterval` setting?

**Comment by Nick-The-Uncharted** [comment] 2021-02-03 08:36
@mrniko Ping is also wrapped in CommandData which is still a instance of QueueCommand, so I think that may not works.

**Comment by mrniko** [comment] 2021-02-03 08:52
connection is reconnected if pong response isn't get. I recommend to try it

**Comment by Nick-The-Uncharted** [comment] 2021-02-03 09:07
@mrniko Thanks a lot, I think that will work. But I think close channel in org.redisson.command.RedisExecutor#scheduleRetryTimeout before throwing `RedisTimeoutException` is not a bad idea becuase it requires no extra configuration.

**Comment by mrniko** [comment] 2021-02-11 06:22
RedisTimeoutException might be caused not only by broken channel, so we can't close it

**Closed** 2021-02-11 06:21 UTC

**Comment by mrniko** [comment] 2026-05-16 05:40
The issue is not relevant to the current code for normal commands. The root cause was eliminated by replacing the gated write model with direct pipelined writes, not by the channel-close fix that was debated in the issue.
