### ISSUE TITLE
Elasticache : Unable to use cluster configuration endpoint

### ISSUE THREAD

**Issue by jainyash** [redisson/redisson#5190] opened 2023-07-20 14:26 UTC
Hello @mrniko 

We are using redisson version 3.18.0 on our production application and are using Elasticache in cluster mode.

As per the recommendation from AWS we need to use cluster configuration endpoint. However when we tested with the same it is not able to connect to the cluster. We see the below error when using the cluster configuration endpoint.

org.redisson.client.RedisException: MOVED redirection loop detected. Node rediss://10.1.22.76:6379 has further redirect to rediss://qaw01-appcontext-esse-s001-0001-002.qaw01-appcontext-esse-s001.gzreim.usw1.cache.amazonaws.com:6379

Can you please help to let us know if the cluster configuration endpoint is being supported or not. Please note that AWS documentation states that we should be using cluster configuration endpoint for connection.

https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Endpoints.html

**Comment by mrniko** [comment] 2023-07-21 05:53
> Can you please help to let us know if the cluster configuration endpoint is being supported or not

Yes, it's supported.

Can you share the logs with `trace` logging level for `org.redisson` package to understand the cause?

**Comment by jainyash** [comment] 2023-07-23 19:10
[TraceLogsRedisson.txt](https://github.com/redisson/redisson/files/12139773/TraceLogsRedisson.txt)
@mrniko  Attached trace logs for connection failure with cluster configuration endpoint

**Comment by mrniko** [comment] 2023-07-24 04:49
I don't see output from ClusterConnectionManager

**Comment by jainyash** [comment] 2023-07-24 09:32
@mrniko I am not sure what you mean exactly. Actually we use the below code to create a connection

Config config = new Config();
config.useClusterServers().addNodeAddress(redisNodes.toArray(new String[0]));
config.useClusterServers().setPassword(redisPassword);
Redisson.create(config);

Let me know if we need to explicitly use ClusterConnectionManager here

**Comment by mrniko** [comment] 2023-07-24 14:17
In this ClusterConnectionManager is used by Redisson, but I don't see any output in logs. Can you check if you set correctly trace logging level for all Redisson classes?

**Comment by jainyash** [comment] 2023-07-26 09:57
@mrniko I am attaching the logs again. 
[ClusterConfigTrace.log](https://github.com/redisson/redisson/files/12170910/ClusterConfigTrace.log)
Kindly let me know if this is sufficient.

**Comment by mrniko** [comment] 2023-07-27 08:59
Still don't see any output from ClusterConnectionManager

**Comment by mrniko** [comment] 2023-10-20 04:08
Fixed in https://github.com/redisson/redisson/issues/4656

**Closed by mrniko** 2023-10-20 04:08 UTC
