### ISSUE TITLE
"RedisConnectionException: SlaveConnectionPool no available Redis entries" even when the slaves are reachable and connections established

### ISSUE THREAD

**Issue by mghegde** [redisson/redisson#2535] opened 2020-01-10 22:54 UTC
**Expected behavior**
We are using Redisson with AWS elasticache redisson cluster. Redisson client throws exception from some of the hosts. Only way to recover is to reboot the EC2 instances/restart the application. Slaves are reachable from the EC2. 

**Actual behavior**
Redisson client fails with the following exception eventhough slaves are reachable from EC2.

**Caused by: org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries.  Disconnected hosts: [10.0.129.98/10.0.129.98:6379]**
        at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:219) ~[Redisson-3.11.x.jar:?]
        at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30) ~[Redisson-3.11.x.jar:?]
        at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:248) ~[Redisson-3.11.x.jar:?]
        at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:464) ~[Redisson-3.11.x.jar:?]
        at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:607) ~[Redisson-3.11.x.jar:?]
        at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:645) ~[Redisson-3.11.x.jar:?]
        at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:116) ~[Redisson-3.11.x.jar:?]
        at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:245) ~[Redisson-3.11.x.jar:?]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663) ~[netty-common-4.1.21.Final.jar:?]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738) ~[netty-common-4.1.21.Final.jar:?]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466) ~[netty-common-4.1.21.Final.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.21.Final.jar:?]

**Steps to reproduce or test case**
Exception happens very randomly in production. 

**Redis version**
5.0.6
**Redisson version**
3.11.6
**Redisson configuration**
config.setNettyThreads(256)
                .useClusterServers()
                .addNodeAddress(redisUrl)
                .setTimeout(200)
                .setRetryInterval(50)
                .setMasterConnectionPoolSize(128)
                .setMasterConnectionMinimumIdleSize(32)
                .setSlaveConnectionPoolSize(128)
                .setSlaveConnectionMinimumIdleSize(32)
                .setPingConnectionInterval(5000)
                .setKeepAlive(true);

**Comment by mghegde** [comment] 2020-01-10 22:59
All the connections are in established state

**netstat -an | grep 10.0.129.98:6379 | wc -l
68**

**Comment by mrniko** [comment] 2020-01-11 05:35
Increase `setFailedSlaveCheckInterval` setting which controls that

**Comment by mghegde** [comment] 2020-01-12 21:01
> Check you network and increase `setFailedSlaveCheckInterval` setting which controls that. Also you may set `pingConnectionInterval` setting

Thanks for the reply @mrniko . Network connection is fine since the EC2 instance is properly communicating with other external dependencies like DynamoDB and Elastic Search. Only one or two socket connections seems to fail from redisson. Strange thing is it happens during the application deployment and redisson never recovers from it. Only way to recover is to restart the application. I see that the default **failedSlaveReconnectionInterval** is 3 seconds. But the application throws disconnected host exception indefinitely till the application restart.

I tried **PingConnectionInterval** setting with 1 second and 5 seconds values. But it didn't help to resolve this problem.

**Comment by mghegde** [comment] 2020-01-15 00:50
@mrniko - I increased the **setFailedSlaveCheckInterval** to 180 seconds. But I'm still getting the same issue

**Comment by xingan** [comment] 2020-02-25 18:42
I just ran into this issue and fixed it by increasing thread pool size.

**Comment by xingan** [comment] 2020-04-02 05:14
I'm running into the same issue with Elasticache. What I observed is that I have 100 pods and every pod talks to 4 different redis clusters with different redisson clients. After each deployment, 1 or 2 pods will have this error talking to 1~2 redis clusters. My current work around is to use master for all the commands. This type of issue only happens to slave.

**Comment by mrniko** [comment] 2020-04-02 14:33
@xingan 

Could you share your Redisson configuration?

**Comment by xingan** [comment] 2020-04-02 21:44
config
    .useClusterServers()
    .addNodeAddress(assembleAddress(config.getHost(), config.getPort()))
    .setConnectTimeout(500)
    .setTimeout(300)
    .setRetryAttempts(1)
    .setRetryInterval(100)
    .setSubscriptionsPerConnection(10)
    .setMasterConnectionMinimumIdleSize(16)
    .setMasterConnectionPoolSize(512)
    .setSlaveConnectionMinimumIdleSize(16)
    .setSlaveConnectionPoolSize(512)
    .setDnsMonitoringInterval(5000)
    .setSubscriptionConnectionMinimumIdleSize(1)
    .setSubscriptionConnectionPoolSize(50)
    .setNettyThreads(512);

Version is 3.10.3

**Comment by mrniko** [comment] 2020-04-03 08:29
@xingan 

Do you have Redisson logs during period of time when that issue happened?

**Comment by xingan** [comment] 2020-04-03 17:19
@mrniko 

stacktrace: [java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292), java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308), java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593), java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577), java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474), java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977), org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:97), org.redisson.command.CommandBatchService.lambda$executeAsync$2(CommandBatchService.java:238), org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183), io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577), io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570), io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549), io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490), io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615), io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608), io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117), org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96), org.redisson.command.RedisCommonBatchExecutor.handleResult(RedisCommonBatchExecutor.java:129), org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:445), org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:163), org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183), io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577), io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551), io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490), io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615), io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608), io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117), org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:96), org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:228), io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672), io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747), io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.lang.Thread.run(Thread.java:748)], message: org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries.

**Comment by KouLouYiMaSi** [comment] 2020-04-23 09:27
I met the same problem.  3 master pod and 3 slave pod in k8s, 2 business pod call redis use redisson.  but only one business pod export Exception.   we execute a ping command in our business pod to ping those 'bad slave' but pings are all lower than 1ms。org.redisson.client.RedisException: 5 keys has been deleted. But one or more nodes has an error
        at org.redisson.RedissonKeys.checkExecution(RedissonKeys.java:377)
        at org.redisson.RedissonKeys.access$200(RedissonKeys.java:56)
        at org.redisson.RedissonKeys$6.operationComplete(RedissonKeys.java:239)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:98)
        at org.redisson.command.CommandAsyncService.checkAttemptFuture(CommandAsyncService.java:801)
        at org.redisson.command.CommandAsyncService.access$300(CommandAsyncService.java:80)
        at org.redisson.command.CommandAsyncService$9.operationComplete(CommandAsyncService.java:610)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
        at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:98)
        at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:540)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:625)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:700)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:428)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries.  Disconnected hosts: [/10.233.68.86:6379, /10.233.66.120:6379]
        at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:190)
        at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
        at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:159)
        at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:413)
        at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:714)
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:501)
        at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:552)

**Comment by mrniko** [comment] 2020-04-23 09:31
Could you set `TRACE` logging level for `org.redisson` and share output during this issue. To realize how these slaves there put into Disconnected hosts list.

**Comment by KouLouYiMaSi** [comment] 2020-04-23 09:52
sorry,  I cannot reproduce this error again.  It happened 2 weeks ago in our production environment. I restarted the 'bad business pod' then everything was ok.  what i can provide is that the error happened when the 'bad biz pod' called redis lock, and when it happened the pings were all lower than 1ms between the 'bad biz pod' and 'bad slave'.

**Comment by ThxGodNovember** [comment] 2020-05-13 00:57
i met same problem. so ,this problem had been resolved?

**Comment by mrniko** [comment] 2020-05-22 05:54
@ThxGodNovember 

https://github.com/redisson/redisson/issues/2535#issuecomment-618293018

**Comment by mrniko** [comment] 2020-06-04 09:23
Fixed in https://github.com/redisson/redisson/issues/2750

**Closed by mrniko** 2020-06-04 09:23 UTC
Labels: bug, redis-cluster

**Comment by AshwinRamesh** [comment] 2021-05-06 09:42
Hi @mrniko - I am experiencing the same issue as @mghegde.

We are running Elasticache and only a few ec2 machines fail with the same error on startup. Never recovering. 

We are on 3.13.3. 

Any advice?

**Comment by mrniko** [comment] 2021-05-06 11:47
@AshwinRamesh 

Can you share redisson logs with `debug` logging level?

**Comment by AshwinRamesh** [comment] 2021-05-20 22:55
@mrniko Apologies for the delay. Since this isn't easily reproducable and we didn't want to leave DEBUG logging on for days on end, we had to build a mechanism to turn on the DEBUG log at run time when we saw this occur. Here is a weird log where we see NULLs being passed into string formatting:

```
log:connection released for command null and params null from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=4, freeConnectionsCounter=value:9:queue:0, freezeReason=null, client=[addr=rediss://prod-items-0003-002.prod-items.yyvvk2.use1.cache.amazonaws.com:6379], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@564150698 [redisClient=[addr=rediss://prod-search-sot-items-0003-002.prod-items.yyvvk2.use1.cache.amazonaws.com:6379], channel=[id: 0xa059182e, L:/10.0.99.47:33954 - R:prod-items-0003-002.prod-items.yyvvk2.use1.cache.amazonaws.com/10.0.33.240:6379], currentCommand=null] log_level:DEBUG logger:org.redisson.command.RedisExecutor source:stdout thread_name:redisson-netty-9-32
```


As discussed:
- Running Cluster mode on AWS Elasticache
- 3.13.3

Thanks in advance

**Comment by AshwinRamesh** [comment] 2021-05-25 21:18
@mrniko friendly ping on above ^ :)

**Comment by mrniko** [comment] 2021-05-26 05:17
> Here is a weird log where we see NULLs being passed into string formatting:

Which Redisson objects do you use?

**Comment by AshwinRamesh** [comment] 2021-05-26 21:28
Our code looks like this and fails with the errors above on the `getBuckets()` call

```
RedissonConfig clusterConfig = config.useClusterServers();
        clusterConfig //
            .setConnectTimeout(connectionTimeout)
            .addNodeAddress(nodes)
            .setIdleConnectionTimeout(IDLE_CONNECTION_TIMEOUT_MS)
            .setMasterConnectionMinimumIdleSize(
                min(clusterConfig.getMasterConnectionMinimumIdleSize(), connections))
            .setMasterConnectionPoolSize(maxConnections)
            .setSlaveConnectionMinimumIdleSize(
                min(clusterConfig.getSlaveConnectionMinimumIdleSize(), connections))
            .setSlaveConnectionPoolSize(maxConnections)
            .setRetryAttempts(retryAttempts)
            .setRetryInterval(retryInterval)
            .setPassword(password)
            .setTimeout(responseTimeout);
RedissonClient redis = Redisson.create(clusterConfig);
final Map<String, String> batchedResult = redis.getBuckets().get(cachedKeys.toArray(new String[0]));
```

Thanks in advance!

**Comment by mrniko** [comment] 2021-05-27 06:16
In cluster configuration case Buckets uses RBatch object. So object with nulls represents RBatch object. Can you share full stacktrace you get?

**Comment by B-Janson** [comment] 2021-06-08 00:12
Just following up on the above, the debug log we can see is 
```
connection released for command null and params null from slot NodeSource 
[slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry 
[masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, 
freeConnectionsAmount=10, freeConnectionsCounter=value:10:queue:0, freezeReason=null, 
client=[addr=rediss://prod-items-0003-002{...}.cache.amazonaws.com:6379], nodeType=MASTER, firstFail=0]]] 
using connection RedisConnection@2124340836 
[redisClient=[addr=rediss://prod-items-0003-002.{...}.cache.amazonaws.com:6379], 
channel=[id: 0x996b54ee, L:/10.0.75.174:52046 - R:prod-items-0003-002.{...}.cache.amazonaws.com/10.0.33.240:6379],
 currentCommand=null]
```
And the error log we can see is 
```
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. 
Master entry host: prod-items-0003-002.{...}.cache.amazonaws.com/10.0.33.240:6379 
Disconnected hosts: [prod-items-0003-002.{...}.cache.amazonaws.com/10.0.33.240:6379] at 
org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:218) at 
org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30) at 
org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:253) at 
org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:500) at 
org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:639) at 
org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:640) at 
org.redisson.command.RedisExecutor.execute(RedisExecutor.java:115) at 
org.redisson.command.CommandBatchService.executeAsync(CommandBatchService.java:303) at 
org.redisson.command.CommandAsyncService.executeBatchedAsync(CommandAsyncService.java:691) at 
org.redisson.command.CommandAsyncService.readBatchedAsync(CommandAsyncService.java:621) at 
org.redisson.RedissonBuckets.getAsync(RedissonBuckets.java:85) at 
org.redisson.RedissonBuckets.get(RedissonBuckets.java:61) at 
com.{...}.cache.RedisCache.batchGet(RedisCache.java)
```

**Comment by mrniko** [comment] 2021-06-09 04:45
Can you provide full log before this error?

**Comment by B-Janson** [comment] 2021-06-10 05:35
We don't have anymore to this log. We call `redis.getBuckets().get(cachedKeys.toArray(new String[0]))` and the exception that we catch is the one above.

**Comment by namratansk** [comment] 2022-10-12 13:42
Hi @mrniko ,
I am using redisson-3.17.6.jar in my application, but whenever my EC2 instances are restarted, I get this error. Kindly help.

" SlaveConnectionPool no available Redis entries"

**Comment by mrniko** [comment] 2022-10-12 13:58
@namratansk

Please share the logs in `trace` logging level for `org.redisson` package since app start till the error appearance.

**Comment by mrniko** [comment] 2022-10-13 08:16
@namratansk

Sorry, I asked for the logs in trace logging level for `org.redisson` package **since app start till the error appearance**. I need more information to understand the cause.

**Comment by miteshjain24** [comment] 2024-05-01 13:29
Hi @mrniko ,

I am also getting the issue : **org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries.  Disconnected hosts:**

I am using Redisson 2.15.2. May i know if this issue is resolved in any higher version of redission?

**Comment by arulned** [comment] 2024-10-03 14:52
We also face this issue randomly in prod and we are very much dependent on the redis data for our business functionality. Once the connection is lost it is lost forever, the redisson reconnection is not working. So when we get the RedisConnectionException, we simply close the existing client and create a brand new client on the fly. Ofcourse this creates a latency problem in our application but we could not find a better way.

**Comment by arulned** [comment] 2024-10-03 21:21
@mrniko We are already at 3.27.2

**Comment by mrniko** [comment] 2024-10-04 05:45
@arulned 

Can you set `trace` logging level for `org.redisson` package and share the log output since the application start moment?

**Comment by arulned** [comment] 2024-10-12 18:51
@mrniko Unfortunately I cannot enable the debug on prod. If I find a consistent way to reproduce this, I will try my best to get the logs.
