### ISSUE TITLE
Transaction does not execute

### ISSUE THREAD

**Issue by kitkars** [redisson/redisson#3674] opened 2021-06-20 22:59 UTC
This transaction works just great 1 time. I tried to execute in a loop just for 10 times!! I get the exception for the remaining 9 times.

```
org.redisson.transaction.TransactionTimeoutException: Transaction was discarded due to timeout 30000 milliseconds
```

```
        for (int counter = 0; counter < 10; counter++) {
            RTransactionReactive transaction = this.client.createTransaction(TransactionOptions.defaults().timeout(30, TimeUnit.SECONDS));
            RBucketReactive<Long> entry1 = transaction.getBucket("entry:1", LongCodec.INSTANCE);
            RBucketReactive<Long> entry2 = transaction.getBucket("entry:2", LongCodec.INSTANCE);
            entry1.get().map(i -> i + 1).flatMap(entry1::set).block();
            entry2.get().map(i -> i - 1).flatMap(entry2::set).block();
            transaction.commit()
                    .doOnError(System.out::println)
                    .onErrorResume(ex -> transaction.rollback())
                    .block();
        }
```

**Comment by mrniko** [comment] 2021-06-23 06:02
Unable to reproduce it.

**Comment by kitkars** [comment] 2021-06-24 19:50
@mrniko I can understand why you think it works!!

Do you have this property set in redis first?? Ensure that you have those keys first in redis. Otherwise it will show like it works. but actually not!

set entry:1 100
set entry:2 100

**Comment by mrniko** [comment] 2021-07-01 12:59
Fixed in https://github.com/redisson/redisson/commit/f7fbb9fbf7b15ab43d6efed5fbff8b25c2687b4f

Thanks for report!

**Closed by mrniko** 2021-07-01 12:59 UTC
Labels: bug
