### ISSUE TITLE
RLock.unlock() results in ERR hash value is not an integer

### ISSUE THREAD

**Issue by dvysotskiy** [redisson/redisson#2551] opened 2020-01-20 20:45 UTC
**Redis**: 5.0.12
**Redisson**: 3.12.0

The following code snippet will successfully create and lock RLock and will throw RedisException unlocking the lock. 

```
   RLock lock = client.getLock("lock-test");
   lock.lock();
   lock.unlock();
```

```
org.redisson.client.RedisException: ERR Error running script (call to f_3ffe249c16dee540ac8ab32e39bd408626b9aff7): @user_script:1: ERR hash value is not an integer . channel: [id: 0x7c579845, L:/my-ip:port - R:host/my-ip:port] command: (EVAL), params: [if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('h..., 2, lock-test, redisson_lock__channel:{lock-test}, 0, 30000, 62ad3063-9ff4-4a24-bfe1-bd08254b2968:1]

	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:351)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:199)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:139)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:114)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by mrniko** [comment] 2020-01-21 05:39
Unable to reproduce. Make sure you don't use other object under the same name.

**Comment by dvysotskiy** [comment] 2020-01-21 18:09
Unfortunately, clearing Redis doesn't help. I've ran your unit tests as well, and the outcome was the same. More so, atomic counter exhibits the same behavior when running getAndSet method. In the test below, the lock is created and lock() call is successful. 

**Output:** 

Locked...
org.redisson.client.RedisException: ERR Error running script (call to f_3ffe249c16dee540ac8ab32e39bd408626b9aff7): @user_script:1: ERR hash value is not an integer . channel:.............



    @Test
    public void testIsHeldByCurrentThread() {
        RLock lock = client.getLock(UUID.randomUUID().toString());
        Assert.assertFalse(lock.isHeldByCurrentThread());
        lock.lock();
        Assert.assertTrue(lock.isHeldByCurrentThread());
        System.out.println("Locked...");
        lock.unlock();
        System.out.println("Unlocked...");
        Assert.assertFalse(lock.isHeldByCurrentThread());
    }

**Comment by mrniko** [comment] 2020-01-22 05:57
Unable to reproduce this. `RAtomicLong.getAndSet` also works. I'm pretty sure that there is a problem with environment. Which Redis version do you use? The latest one is 5.0.7 and not 5.0.12 you defined.

**Comment by dvysotskiy** [comment] 2020-01-22 06:25
Sorry about the typo. Redis version is 5.0.2. Don't know what to say other than the issue has been reported and can be closed because it is not reproducible? Are there any config settings you can think of?

**Comment by mrniko** [comment] 2020-01-22 06:29
Could you share your Redis config?

**Comment by mrniko** [comment] 2020-01-22 06:30
Or maybe whole test app?

**Comment by dvysotskiy** [comment] 2020-01-22 06:35
> Could you share your Redis config?

singleServerConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: "my-password-NOT-NULL"
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://vip:port"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 10
  connectionPoolSize: 64
  database: 0
  keepAlive: true
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"

**Comment by dvysotskiy** [comment] 2020-01-22 06:37
> Or maybe whole test app?

Please giv

**Comment by dvysotskiy** [comment] 2020-01-22 06:38
Sorry, didn't mean to close this. I will provide a clean test app that fails.

**Comment by dvysotskiy** [comment] 2020-01-22 21:56
Below is the simplified/sanitized version with the same issue. The contents of default-redis.yaml are posted above. 

**pom.xml**

```<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.redisson</groupId>
  <artifactId>redisson-test</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>redisson-test</name>

  <properties>
    <redisson.version>3.12.0</redisson.version>
    <io.commons.version>2.6</io.commons.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.redisson</groupId>
      <artifactId>redisson</artifactId>
      <version>${redisson.version}</version>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>${io.commons.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
```



```package com.redisson;

import org.apache.commons.io.IOUtils;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.redisson.Redisson;
import org.redisson.api.RLock;
import org.redisson.api.RedissonClient;
import org.redisson.config.Config;

import java.nio.charset.Charset;
import java.util.UUID;


public class RLockTests {

    protected RedissonClient client;

    @Before
    public void init() {
        try {
            String redisConfig = IOUtils.resourceToString("/default-redis.yaml", Charset.defaultCharset());
            client = Redisson.create(Config.fromYAML(redisConfig));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @After
    public void dispose() {
        client.shutdown();
    }

    @Test
    public void testIsHeldByCurrentThread() {
        RLock lock = client.getLock(UUID.randomUUID().toString());
        Assert.assertFalse(lock.isHeldByCurrentThread());
        lock.lock();
        Assert.assertTrue(lock.isHeldByCurrentThread());
        System.out.println("Locked...");
        lock.unlock();
        System.out.println("Unlocked...");
        Assert.assertFalse(lock.isHeldByCurrentThread());
    }

    @Test
    public void testGetHoldCount() {
        RLock lock = client.getLock(UUID.randomUUID().toString());
        Assert.assertEquals(0, lock.getHoldCount());
        lock.lock();
        Assert.assertEquals(1, lock.getHoldCount());
        lock.unlock();
        Assert.assertEquals(0, lock.getHoldCount());

        lock.lock();
        lock.lock();
        Assert.assertEquals(2, lock.getHoldCount());
        lock.unlock();
        Assert.assertEquals(1, lock.getHoldCount());
        lock.unlock();
        Assert.assertEquals(0, lock.getHoldCount());
    }
}
```

**Comment by mrniko** [comment] 2020-01-23 06:53
`IOUtils.resourceToString` gives compile time error.

Anyway here is whole app. I run redis server using: `redis-server --requirepass 123`
No errors.

[testapp2.zip](https://github.com/redisson/redisson/files/4101683/testapp2.zip)

**Comment by dvysotskiy** [comment] 2020-01-23 16:18
The tests in your **testapp2** failed for me the same way mine did. Are you running the same version of Redis? The replicated cluster I connect to is behind a VIP.

**Comment by mrniko** [comment] 2020-01-23 17:08
I used the latest one. natMap setting for sentinel and cluster mode allows to set ip address translation.

**Comment by dvysotskiy** [comment] 2020-01-23 17:47
Thank you for your assistance. I've setup a local cluster without replication, and all the tests are passing. I will route this issue to Redis support.

**Comment by mrniko** [comment] 2020-01-24 06:26
I'm closing this then.

**Comment by dvysotskiy** [comment] 2020-01-29 17:59
Just wanted to update this issue with the root cause. The problem manifests itself when running in CRDB. I could not find the original link from Redis Labs but got a snippet from a colleague: 

**Important information for Developers**
An issue has been found when using the SETEX command on a CRDB Instance. The behavior of this command is different that when used with a regular Redis Instance.
As a workaround, please use two separate commands SET first then EXPIRE second to set a key to expire.

**Comment by mrniko** [comment] 2020-01-30 05:45
thanks for reposponse! I'll take it.

**Comment by mrniko** [comment] 2020-02-06 06:39
@dvysotskiy 

Could you clarify where do you use setex command? It's not used in RLock object.

**Comment by dvysotskiy** [comment] 2020-02-06 17:51
I am not explicitly using it anywhere in code. Perhaps, there's another command that exhibits the same behavior. The test app you've provided and the one I've attached fail when pointed at CRDB but both succeed when connected to regular instance of Redis. 

Here's the trace level logs

**Create lock:**
```
if 
    (redis.call('exists', KEYS[1]) == 0) 
then 
    redis.call('hset', KEYS[1], ARGV[2], 1); 
    redis.call('pexpire', KEYS[1], ARGV[1]); 
    return nil; 
end; 
if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) 
then 
    redis.call('hincrby', KEYS[1], ARGV[2], 1); 
    redis.call('pexpire', KEYS[1], ARGV[1]); 
    return nil; 
end; 
    return redis.call('pttl', KEYS[1]);
```

**Release lock:**
```
if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) 
then 
    return nil;end; 
    
local counter = redis.call('hincrby', KEYS[1], ARGV[3], -1); 
if (counter > 0) 
then 
    redis.call('pexpire', KEYS[1], ARGV[2]); 
    return 0; 
else 
    redis.call('del', KEYS[1]); 
    redis.call('publish', KEYS[2], ARGV[1]); 
    return 1; 
end; 
    return nil;
```
**Error:**
ERR hash value is not an integer . channel:.... [if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('h..., 2, my-lock, redisson_lock__channel:{my-lock}, 0, 30000, 27728906-8c98-425c-b166-81a6dcf3b9fe:1]

I am suspecting **_pexpire_** modifies the counter data type causing _**hincrby**_ to fail. This is just an assumption based on what I see. I will run these commands directly against Redis and will post an update.

**Comment by mrniko** [comment] 2020-02-08 07:53
@dvysotskiy 

Thank you for your help!

**Comment by dvysotskiy** [comment] 2020-02-11 22:35
@mrniko, per vendor, this is expected behavior in Redis version < 5.4.2
`Fields in hashes can be initialized as a string using HSET or HMSET or can be used to initialize counter types that are numeric integers using HINCRBY or floats using HINCRBYFLOAT.`

**Comment by dvysotskiy** [comment] 2020-02-12 02:21
Worth mentioning, [this](https://github.com/redisson/redisson/files/4189544/lock-unlock.zip) has been tested against non-CRDB and CRDB instances of Redis.

**Comment by mrniko** [comment] 2020-02-12 05:05
Thanks for response! Will fix that

**Comment by mrniko** [comment] 2020-02-20 07:19
Fixed

**Closed by mrniko** 2020-02-20 07:19 UTC
Labels: redis vendor bug
